### ISSUE TITLE
Add support for non-zipped downloads + citation service

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-service#1]
Support for non-zipped downloads + citation service.

**Comment by nickdos** [comment]
Looking at sprint - not enough information here to know whether to include this issue. What is the use case?

**Comment by djtfmartin** [comment]
This was a request from Paul Giola of WA. He wanted to access the downloads without the CSV being zipped.

This could lead to a very large file so it might make sense to only allow for a smaller number of records.

**Comment by adam-collins** [comment]
If required this can be done with &zip=false on the index/download service. Default limit is 10000 records. It has the same content as the zip but with a plain text separator that contains the file name.
