### ISSUE TITLE
KML download format for map data

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#100]
A user has requested a KML file so they can visualise in Google Earth.

There are some issues with this as there could be very large numbers of points which could make Google Earth very slow. Their suggestions were:

> Yes, downloadable as a kml file - yes please!!!
> 
> Many thanks for the earthpoint link, I'll give that a try (while I await ALA implementing downloadable kml files! Ha! :-) )
> 
> Many thanks also for the contacts to talk to (cc'd herewith).
> 
> Yes, I can see that heatmaps are very useful to provide a clear overview. Unfortunately, I still need the full data for each and every data record for a taxon.
> 
> Yes you are right, the more data records the slower Google earth will take to display them, and may even run out of resources and hang. But as computers increase in speed and memory that is will be less of a problem in the future, though perhaps still 10 years away. Therefore, in the interim may I suggest...
> 
> (1) add a warning advising that the more records in the one kml file the slower Google earth will take to display them, and may well hang, and
> 
> (2) provide the ability to download the data in user-definable chunks. For example, the user knows how many records their computer can handle, and advises the number of records per chunk for a taxon by selecting for a list of variables in a drop-down list. I suggest the download chunk options be made available as follows:
> 
> '500 records per kml file'
> '1000 records per kml file',
> '2000 records per kml file',
> '5000 records per kml file',
> '10,000 records per kml file',
> '20,000 records per kml file',
> '50,000 records per kml file',
> '100,000 records per kml file'
> 'All records'.
> 
> Then, ALA divides up the taxon's records according to the user's selection above and makes them available in the requested chunks, and list them 'Chunk 1', Chunk 2' etc for downloading separately. I don't think this would be hard to implement.

I'm not convinced there is enough demand at this stage so parking this as a low priority, pending other users asking for it.

**Comment by adam-collins** [comment]
Google Earth Pro, now free, supports import of CSV and Shapefiles. This appears to work with our downloaded CSV and Shapefile files without issue. We could add the Shapefile export option to the download UI.

I do not think a KML export option for use with Google Earth is necessary.

**Comment by nickdos** [comment]
TODO - add this to documentation

**Comment by adam-collins** [comment]
added to documentation on api.ala.org.au
