### ISSUE TITLE
Missing data providers list in offline download README

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#101]
Just parking this issue so its not forgotten. WE will be putting the new downloads live soon (1-2 weeks) so will need attention before then.

![image](https://cloud.githubusercontent.com/assets/532845/17124575/6fab43f0-532f-11e6-815a-3380ae9bd80d.png)

Also need to expand/fix the missing `[downloadUrl]` template var.

**Comment by adam-collins** [comment]
fixed
