### ISSUE TITLE
Strange LSID serch result

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#102]
http://biocache.ala.org.au/ws/occurrences/search?q=lsid:ALA_Myrmecia_sp._17

returns plant records despite the GUID being a valid ant name - see

http://bie.ala.org.au/species/ALA_Myrmecia_sp._17

**Comment by adam-collins** [comment]
Looks like left/right values have changed in the names index and biocache has older left right values.

**Comment by nickdos** [comment]
I see the map - not sure if someone fixed this or is a browser specific issue?

![image](https://cloud.githubusercontent.com/assets/532845/17279940/302c3112-57c6-11e6-920f-0ccf031d3480.png)
