### ISSUE TITLE
Species checklist download - scientificName issue

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#104]
Since swirching to the new BIE (I think) the species checklist (CSV) downloads are providing the scientificName field with authority, which is posing a problem for some people.

Ryonen suggests it would be better to have:

>  1) binomial + authority; 2) binomial only; 3) authority only. The least useful of these is obviously ‘authority only’, but having that column just covers all the bases of how other people will use the data in their manifestly varied systems. Is that do-able?

If this is a BIE issue, then move it to bie-index...

**Comment by adam-collins** [comment]
The species checklist currently contains the split fields, 2) and 3)
