### ISSUE TITLE
Allow adding images to a resource

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#110]
From profile-hub#419

> **Publishing to external repositories**
> Publishing an image externally (to biocache) will override any previous images.
> This is at least true for a Biocache instance storing images locally.

The service used is this:
http://biocache-test.ala.org.au/ws/occurrence/
Biocache should
1. Provide an additional service to add images, keeping existing ones
2. For images stored locally a UUID rather than a path should be returned as image identifier

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
