### ISSUE TITLE
Incorrect match for 'matched_name_children' search

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#115]
Searching for `acacia dealbata` in simple search gives the correct match but using the AVH advanced search, which uses the `matched_name_children:acacia dealbata` returns the wrong taxon and shows `No records found for Unknown Rank: Acacia dealbata`

The incorrect match is: http://bie.ala.org.au/species/http://id.biodiversity.org.au/instance/apni/845052
The correct match is: http://bie.ala.org.au/species/http://id.biodiversity.org.au/node/apni/2903532#names

Note the first match shows: `heterotypic` and `nom. illeg.` so is a misused name.

**Comment by nickdos** [comment]
Another support email reported this:

>> There is an issue with the advanced search for some species names. I’ve got an open ticket for it, so it should be fixed before the end of the year. Thanks for reporting this.

> I've just been searching AVH for records of  various **Schoenus** species.
> I had no trouble with **S. apogon** and **S. melanostachys**, but for **S.
> kennyi** and **S. imberbis** I got the message 'No records found: unknown
> rank'.
> Maybe the records for these two taxa are being updated right now, but
> there may be a more general problem with the index links for those two
> names?

**Comment by adam-collins** [comment]
Moved to bie-index
