### ISSUE TITLE
Offline downloads email "Occurrence Download Failed" but download file is OK 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#117]
Offline downloads are sending through emails saying "Occurrence Download Failed" even though the UI provides a link to the download file that seems fine. 

```The download has failed. uniqueId:dd0dfc2b-2e11-30ce-91bb-ca8afff9715e-1479949931853 path:/dd0dfc2b-2e11-30ce-91bb-ca8afff9715e/1479949931853/orthobula-records-2016-11-24.zip```

Note: UI provides this URL: http://biocache.ala.org.au/biocache-download/dd0dfc2b-2e11-30ce-91bb-ca8afff9715e/1479949931853/orthobula-records-2016-11-24.zip

**Comment by adam-collins** [comment]
This is now fixed.
