### ISSUE TITLE
query cache does not support cross domain request

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocache-service#12]
Cross domain queries are not supported as the server rejects them. It will be nice to have this feature since it can help standalone web applications.

**Comment by nickdos** [comment]
Already done in bie-service here:

https://github.com/AtlasOfLivingAustralia/bie-service/commit/347e9985fae530952a99552638fc4edaf8510295

So should be straightforward port.

**Comment by nickdos** [comment]
Closing this one for the better named #49
