### ISSUE TITLE
geodeticDatumOriginal instead of geodeticDatum?

### ISSUE THREAD

**Issue by raymondben** [AtlasOfLivingAustralia/biocache-service#124]
(Transferred from https://github.com/AtlasOfLivingAustralia/ALA4R/issues/22)

For a record such as [this](http://biocache.ala.org.au/occurrences/b9022246-de53-43a2-952d-5f85bd9948c0), where supplied geodetic datum is not WGS84, `occurrences` returns the supplied datum (epsg:4202 for the record above) in the `geodeticDatum` element. 

Would this be better returned as `geodeticDatumOriginal`, with the processed datum given in `geodeticDatum` instead (since the coordinates given in `latitude` and `longitude` seem to correspond to WGS84)?

**Comment by djtfmartin** [comment]
Both datums are there - the raw and the processed.

http://biocache.ala.org.au/ws/occurrences/b9022246-de53-43a2-952d-5f85bd9948c0

raw.location. geodeticDatum = epsg:4202
processed.location. geodeticDatum = EPSG:4326
