### ISSUE TITLE
Use common download infrastructure for online and offline

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#128]
There are two separate infrastructures in place for online and offline downloads. It may be simpler for maintenance if these were driven by the same architecture, with online being blocking before returning the result, and offline being a non-blocking/asynchronous return.

**Comment by ansell** [comment]
A common infrastructure would also make it simpler to identify and fix bottlenecks. Refs https://github.com/AtlasOfLivingAustralia/maintenance/issues/35

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
