### ISSUE TITLE
Fish or Fishes

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#13]
_From @djtfmartin on August 19, 2014 10:31_

_migrated from:_ https://code.google.com/p/ala/issues/detail?id=98
_date:_ Thu Aug  8 16:27:28 2013
_author:_ moyesyside

---

Original Issue reported by Reported by john.t...@austmus.gov.au, Today (16 hours ago) - [https://code.google.com/p/ala-portal/issues/detail?id=300](https://code.google.com/p/ala-portal/issues/detail?id=300)

Reported by john.tann@austmus.gov.au, Today (16 hours ago) 
I have been told that when we refer to 'fish' as a lifeform we should use the word 'fishes'
See [http://australianmuseum.net.au/fish-and-fishes](http://australianmuseum.net.au/fish-and-fishes)

The word 'fish' should be changed to 'fishes' when referring to a lifeform.

**What steps will reproduce the problem?**
An example:
Australian Museum Ichthyology collection. in the graph of records by higher level group:  
Axis is Arthropods Fish Insects Reptiles

**What is the expected output? What do you see instead?**
Axis is Arthropods **_Fishes**_ Insects Reptiles 

What version of the product are you using? On what operating system?
2013

Please provide any additional information below.
The term 'fish' is probably incorrectly used in a bunch of places.

This is a low priority fix.
 fish or fishes.png 4.7 KB   View   Download

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#14_

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 10:31_


*date:* Thu Aug  8 22:28:50 2013
*author:* moyesyside
 ---

*(No comment was entered for this change.)*

 ---
**UPDATES:**
*Cc:* john.t...@austmus.gov.au

**Comment by adam-collins** [comment]
Would a message.properties change to display Fishes instead of Fish be enough of a fix for this issue?

**Comment by adam-collins** [comment]
Changed biocache-store https://github.com/AtlasOfLivingAustralia/biocache-store/commit/89acfb30fc0dbba26997d11bc25fcd23b548f407

**Comment by djtfmartin** [comment]
fixed
