### ISSUE TITLE
Download URL not encoded in email

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#132]
The download file filename is via input from the user, so they are able to type anything. The URL in the email is not currently encoding the URL, so spaces are coming through "as is" and it causes the URL to "break" over the space.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/commit/9d9ca1ca1551cf65de2355a22e15c6ded064f2b4
