### ISSUE TITLE
Restarting web application resets progress on downloads

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#133]
Restarting the biocache-service web application currently resets progress on downloads. This provides surety that the download is consistent, but it allows large downloads to sit in the queue if the application is restarted often.

The DevOps backup strategy is to take applications down temporarily each night to take snapshots. This, along with the general biocache instability, may be resulting in some very large downloads (>10 million records) being restarted repeatedly and not completely finished before subsequent restarts.

The changes in #125 do not fix this issue in its current state.

**Comment by ansell** [comment]
Note, as an interim fix, the backup strategy for biocache-b3 has been changed from nightly restarts to weekly restarts.

**Comment by ansell** [comment]
The keys right now for this are the use of a file-based persistence for the download queue, along with a local-directory as the storage location.

The file-based persistence is being done by https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/dao/JsonPersistentQueueDAOImpl.java

For the downloads to be handled by multiple network nodes, the persistence would need to be handled by a transactional database, and the storage would need to be done using shared network locations (Amazon S3 Buckets for example, or a mounted network drive)

**Comment by ansell** [comment]
Restarting also immediately restarts any download queries, adding extra load during the application warmup period that may be part of the cause in cases where the application crashes again within minutes after restart. Refs https://github.com/AtlasOfLivingAustralia/maintenance/issues/35

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
