### ISSUE TITLE
download header descriptions and extra line to be removed

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-service#136]
Descriptions of exported headers is inadequate. We must use (automatic) links to http://tdwg.github.io/dwc/terms and ensure that any ALA added terms are well described. Particularly bad is "Raw header from data provider".

Download CSV contain a blank line after header. Please remove.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/commit/e926e0913a3b37840459ca78889522cc68e306ea

message.properties https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/webapp/WEB-INF/messages.properties

The "Raw header from data provider" can now be changed in message.properties by editing the `description.=` line. 

CSV blank line is removed.

Inadequate descriptions can be changed in message.properties by adding or changing the description.* entries: 
e.g. description.name=a useful description. The `name` can be found in the `Requested field` column of headers.csv.

DwC URL is now included at the end of the description field in the exported headers file for all dwc.* message.properties entries. Adding URLs to other descriptions can be done by editing the description.* entries.
