### ISSUE TITLE
Add a configuration option for query timeouts for online/search queries

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#138]
There are a small number of very long (multi-minute) Solr queries regularly reported when tracking the Solr JMX metrics for 99th and 999th percentile query latency. Although the ALA wants to allow arbitrary queries, we should restrict these queries as offline downloads and time them out if they are attempted to be run as online/search queries.

**Comment by ansell** [comment]
Refs https://github.com/AtlasOfLivingAustralia/maintenance/issues/35

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
