### ISSUE TITLE
Consolidate mapping and offline downloads under single high level /ws/ paths

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#139]
In the process of implementing an AWS load balancer to evenly and redundantly direct traffic flow for biocache.ala.org.au/ws/ sub-paths, there are limitations based on the number of path rules that each load balancer can be configured with. This is causing issues with the number of distinct paths used for the offline downloads, and the two distinct paths used for mapping related queries (/ws/mapping/ and /ws/webportal/)

In a future API revision, we should reconcile this to have a single base path for mapping and a single base path for offline downloads. This relates to the requirement that offline downloads must be hosted on a single physical machine at this point: https://github.com/AtlasOfLivingAustralia/biocache-service/issues/133

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
