### ISSUE TITLE
Support for SOLR 4.4

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#14]
_From @djtfmartin on August 19, 2014 10:31_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=112
*date:* Thu Aug  8 16:34:11 2013
*author:* moyesyside
 ---

Original Issue reported by Project Member Reported by natasha....@csiro.au, Aug 4 (3 days ago) - [https://code.google.com/p/ala-portal/issues/detail?id=299](https://code.google.com/p/ala-portal/issues/detail?id=299)

Project Member Reported by natasha.carter@csiro.au, Aug 4 (3 days ago) 
Attached to this issue is the patch required to upgrade to SOLR4.4.0.  This code base will not be committed into the trunk until we are ready to release biocache-service at SOLR 4.4 level.
 Aug 4 (3 days ago) Project Member `#1` moyesyside@gmail.com 
(No comment was entered for this change.)
 Labels: SOLR Aug 5 (2 days ago) Project Member `#2` natasha.carter@csiro.au 
I didn't realise that there was a bug in one of my files. Here is that works
 SOLR4.4-integration.patch 31.1 KB   View   Download

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#15_

**Comment by djtfmartin** [comment]
closing. this is old
