### ISSUE TITLE
Missing user_assertions values in SOLR index

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#140]
It appears there are records with a user_assertions that have a `assertion_user_id` value in the index but no `user_assertions` value. 

http://biocache.ala.org.au/occurrences/search?q=text%3AColluricincla+%28Colluricincla%29+harmonica&fq=multimedia%3A%22Image%22

the assertions filters show:

![image](https://cloud.githubusercontent.com/assets/532845/23144684/6ca24e22-f81d-11e6-9de7-a48bdf21ec9e.png)

I'd expect there to be entries for the `user_assertions` field shown as well (facet is being requested).  

I wonder if this is an issue related to the fact that the values for `user_assertions` were changed from a Boolean to "unconfirmed", "verified", etc.?

**Comment by nickdos** [comment]
The record in question http://biocache.ala.org.au/occurrences/4fffed25-0bb4-4886-a10a-4663293850de has "User Assertion Status: [user_assertions.]" - which looks wrong.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
