### ISSUE TITLE
Checklist download issue

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#148]
The download option for "Species checklist" is returning just the GUID and no other fields. E.g. http://biocache.ala.org.au/ws/occurrences/facets/download?reasonTypeId=10&file=records-2017-03-13&dwcHeaders=true&email=nick.dosremedios%40csiro.au&qa=none&sourceTypeId=2&q=species_group%3AAngiosperms+cl1048%3APilbara&qc=data_hub_uid:dh9&facets=species_guid&lookup=true

is returning a CSV file with correct headers but data lines contain only the GUID and no other fields. E.g.

`Species	Species Name	Scientific Name Authorship	Taxon Rank	Kingdom	Phylum	Class	Order	Family	Genus	Vernacular Name`

`urn:lsid:biodiversity.org.au:afd.taxon:0c826b9b-6863-4845-b851-35864ec2ebb5										`

**Comment by nickdos** [comment]
This used to work but I'm wondering if something has changed, e.g. the endpoint in the download options code, as the URL looks to be doing the right thing - facet download for speciess_guid.

**Comment by ryonen** [comment]
Thanks everyone! Works perfectly now.
