### ISSUE TITLE
Offline download email report "failed" status URL OK

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#149]
A recent offline download resulted in an email with subject "Occurrence Download Failed - records-2017-03-14" and body:

`The download has failed. uniqueId:dd0dfc2b-2e11-30ce-91bb-ca8afff9715e-1489459659889 path:/dd0dfc2b-2e11-30ce-91bb-ca8afff9715e/1489459659889/records-2017-03-14.zip`

Yet the status URL used by the UI: http://biocache.ala.org.au/ws/occurrences/offline/status/dd0dfc2b-2e11-30ce-91bb-ca8afff9715e-1489459659889 eventually returned:

`{
status: "finished",
downloadUrl: "http://biocache.ala.org.au/biocache-download/dd0dfc2b-2e11-30ce-91bb-ca8afff9715e/1489459659889/records-2017-03-14.zip"
}`

Why is the failed download being reported?

**Comment by adam-collins** [comment]
There were several failures due to Cassandra going down. Changed behaviour to retry the download later instead of sending an email.
