### ISSUE TITLE
Quality tests failed to pick up Citizen Science record in wrong hemishpere

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#15]
_From @djtfmartin on August 19, 2014 10:32_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=113
*date:* Thu Aug  8 16:34:23 2013
*author:* moyesyside
 ---

Original Issue reported by Reported by john.t...@austmus.gov.au, Jul 9, 2013 - [https://code.google.com/p/ala-portal/issues/detail?id=298](https://code.google.com/p/ala-portal/issues/detail?id=298)

Reported by john.tann@austmus.gov.au, Jul 9, 2013 
User flagged an issue on 9 July 2013 
[http://biocache.ala.org.au/occurrences/4e9cbb3d-c152-4971-b9b3-f0724820e89c#userAnnotations](http://biocache.ala.org.au/occurrences/4e9cbb3d-c152-4971-b9b3-f0724820e89c#userAnnotations)

Comment: Lat and Long are correct for this but Lat should be SOUTHERN hemisphere. i.e. -29.93... Does anyone check this stuff??

Note that this is a fish, and so may be a cause for not checking for marine/non-marine 

**What steps will reproduce the problem?**
1. Citizen Science data is entered. Lat-long is given wrong hemisphere.
(I know that Google Maps will show you where you are on the planet, but for some reason, this didn't work properly this time. The location given was too descriptive for Google Maps, so the marker would have had to be manually moved. Probably where the first error came in.)

2. ALA Data quality tests do not detect any problems
Failed quality tests: 0
Data warnings: 0
Passed quality tests: 24
Missing record properties: 11
Test not ran (lack of data): 42 

Some of the tests not run include
Latitude is negated 	Unchecked (lack of data)
Coordinates dont match supplied country 	Unchecked (lack of data)

What is the expected output? 
A validity check that picks up wrong hemisphere, or out-of-country.

What do you see instead?
All tests passed.

What version of the product are you using? On what operating system?
N/a

Please provide any additional information below.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#16_

**Comment by djtfmartin** [comment]
closing. i dont see how this can be resolved without other locality infromation
