### ISSUE TITLE
Enhancement: add conservation status values to checklist 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#153]
E.g. http://biocache.ala.org.au/ws/occurrences/facets/download?email=nick.dosremedios%40csiro.au&qa=none&sourceTypeId=0&reasonTypeId=10&file=records-2017-03-17&dwcHeaders=true&q=qid%3A1489459556676&facets=species_guid&lookup=true

Possibly via an optional param. Not sure whether to use both state_conservation and aus_conservation or just the former.

**Comment by nickdos** [comment]
Closing as this was intended for SP - not biocache.

**Comment by nickdos** [comment]
Still an issue for facets download (what the `checklist` download uses. 

Currently the column called `Conservation` returns values like:

```csv
"Conservation"
"South Australia : Conservation Status|Queensland : Conservation Status"
"Queensland : Conservation Status|Northern Territory : Conservation Status"
"Western Grey Kangaroo","Queensland : Conservation Status"
```

Note: it shows an `array` of state conservation list titles but does not show the actual conservation `status` values (threatened, endangered, extinct, etc). Would it possible to add a second column that has pipe separated list of the values (or simialr)?

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
