### ISSUE TITLE
Remove calls to AUTH for all "auth user names"

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#154]
Currently the code is disabled via this config var:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/e926e0913a3b37840459ca78889522cc68e306ea/config/biocache-config.properties#L166

Called at: https://github.com/AtlasOfLivingAustralia/biocache-service/blob/8cf5de4094ae08648b9a985fa22f0c4a906adec0/src/main/java/au/org/ala/biocache/service/AuthService.java#L151

but there is a chance this could be unintentionally reactivated and cause performance issues on http://auth.ala.org.au due to userdetails trying to load the entire list of users into memory.

So, this code should be removed or replaced with a more memory-optimised version (paging maybe)?

**Comment by adam-collins** [comment]
These calls are required by biocache-service. 

In userdetails, the number of SQL queries not the memory usage was a problem. User.findAll() was doing up to 2*numberOfUsers additional SQL queries. Now only 1 SQL query is required, improving performance in userdetails.   https://github.com/AtlasOfLivingAustralia/userdetails/commit/4007fc50e6cac3ebc7ca2cf1a565827dbfc07436
