### ISSUE TITLE
Large offline downloads get split mid-record into multiple CSV files

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#159]
Reported by John:

>I'm loving the offline downloads, and the ability to request them from ALA4R. 
>
>I requested a large offline occurrence download from ALA - about 35GB when unzipped. It was delivered as 8 separate csv files (data.csv, data_part2.csv, etc.). 
>
>I've noticed that for each csv other than the last, the final record is split, with the end of that record given at the start of the next csv. 
>
>For example, the last record of my data.csv is:
>
>"3408a168-c1b7-4844-b3de-7aa6f1bb47a9"  "SIXRI1486607"  "urn:lsid:biodiversity.org.au:afd.taxon:e079f94d-3d7f-4deb-ae29-053fec4d1b53"   "Vombatus ursinus"      "Common Wombat" "Vombatus ursinus"      "species"       "Common Wombat" "Animalia"      "Chordata"      ""      "Diprotodontia" "Vombatidae"    "Vombatus"      "Vombatus ursinus"      ""      "NSW Office of Environment and Heritage"        "BioNet Atlas of NSW Wildlife"  "locality withheld"     "-34.458967019" "150.204732958" "GDA94" "-34.458967018" "150.204732958" "10.0"  "Australia"     "Sydney Basin"  ""      "New South Wales""Wingecarribee (A)"    ""      ""      ""      ""
>"OIXR14052303"  "2014"  "06"    "2014-06-03"    "HumanObservation""HumanObservation"    ""      ""      "noIssue"       "true"  "false" "false" "false" "false" "false" "false" "false" "false""false"  "false" "true"  "false" "false" "true"  "false" "false" "false" "false" "false" "false" "false" "false" "false""false"  "fal
>
>and the first record of my data_part2.csv is:
>
>se"     "false" "false" "false" "false" "false" "false" "false" "false" "false" "false" "false" "false" "false" "false" "false" "false" "true"  "true"  "false" "false"   "false" "false" "false" "false"
>
>Would you consider changing that behaviour, so that the separate files can be read independently?

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
