### ISSUE TITLE
Produce an HTML version of /ws/index/fields

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#160]
Main purpose is to be able to point users to the list of fields and not have to rely on them knowing JSON. Similar to what the SP does with its layer info pages, e.g. http://spatial.ala.org.au/layers-service/layers/view/more/794

Should have the following features:
- similar URL pattern to `/ws/index/fields` (so guessable)
- hash bookmarks so we can line to specific fields (must support linking to DwC, download and SOLR versions (somehow)

Nice to have:
- automatically link through the DwC version on http://rs.tdwg.org/dwc/terms/
- better description text via i18n properties file (or lookup to somewhere else)
- sorting & filtering (in page search)
- grouping (similar to sorting & filtering) maybe via a simple tree structure on left side?

**Comment by ben3000** [comment]
http://projects.spring.io/spring-restdocs/ perhaps?

**Comment by nickdos** [comment]
I just consumed the JSON and did it in Grails in the end:

<img width="1281" alt="occurrence_record_fields" src="https://cloud.githubusercontent.com/assets/532845/26137830/2003081c-3b08-11e7-97c7-50e94835dcf4.png">

**Comment by djtfmartin** [comment]
Done

**Comment by djtfmartin** [comment]
In case it helps, theres now also a CSV download here:

http://biocache-clustered.ala.org.au/ws/index/fields.csv
