### ISSUE TITLE
Error displayed as in-page text with 200 response code - should be 5xx

### ISSUE THREAD

**Issue by matthewandrews** [AtlasOfLivingAustralia/biocache-service#161]
When biocache-service gets a timeout trying to get ws results from cassandra, it displays an error message like this as text on the response page:

> Error: Failed to get json from web service (http://biocache.ala.org.au/ws/occurrence/77852f0f-7149-4ac5-a6b3-87a1ec32e1ad?apiKey=api-key-to-use). class java.io.IOException Server returned HTTP response code: 500 for URL: http://biocache.ala.org.au/ws/occurrence/77852f0f-7149-4ac5-a6b3-87a1ec32e1ad?apiKey=api-key-to-use, java.io.IOException: Server returned HTTP response code: 500 for URL: http://biocache.ala.org.au/ws/occurrence/77852f0f-7149-4ac5-a6b3-87a1ec32e1ad?apiKey=api-key-to-use

This is returned with a 200 html response code, which means that monitoring and load balancers don't detect a problem.  I think this kind of error page should have a 5xx response code.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
