### ISSUE TITLE
matched_name search not returning expected results

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#166]
Reported by Aaron:

http://biocache.ala.org.au/ws/occurrences/search?q=genus:Luzula&fq=data_resource_uid:dr2153&facets=species&facets=subspecies_name&fq=subspecies_name:%22Luzula+crinita+Hook.f.+var.+crinita%22

71 results

http://biocache.ala.org.au/ws/occurrences/search?q=genus:Luzula&fq=data_resource_uid:dr2153&facets=species&facets=subspecies_name&fq=matched_name:%22Luzula+crinita%22

46 results

The second (`matched_name` version) should return at least the same or more results than the `subspecies_name` version, I'd have thought. Seems to indicate that `scientificName` is not being `copyTo` `matched_name` when a subspecies rank.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
