### ISSUE TITLE
Autocomplete service bugs

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#167]
http://biocache.ala.org.au/ws/autocomplete/search?q=eucalyptus (1015 results)
returns fewer results than
http://biocache.ala.org.au/ws/autocomplete/search?q=eucalyp (1020 results)
which you'd expect.
But 
http://biocache.ala.org.au/ws/autocomplete/search?q=eucalyptus&fq=state_conservation:Vulnerable
returns 1 result and
http://biocache.ala.org.au/ws/autocomplete/search?q=eucalypt&fq=state_conservation:Vulnerable
returns zero results.

This doesn't seem right. At the least, the second hit should show the same single result.

Also, the "1 result" URL reports `totalRecords: 1015` but only shows a single element in the `results` array. Is this also a bug?

**Comment by djtfmartin** [comment]
this is now fixed. the first URL returns 1025
