### ISSUE TITLE
Ideas for map styles

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#169]
https://blog.mapbox.com/right-way-visualize-data-945d6010fab0

I'd like to see us provide:
- hexbin style grid density (both WMS and WFS)
- region-based colour density e.g. states, IBRA, IMCRA, LGA (both WMS and WFS)

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
