### ISSUE TITLE
Download file name needs character filtering

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#170]
The download file name needs character filtering. Currently being used as file name, so essential that it is a safe subset of the possible characters.

**Comment by ansell** [comment]
A fix for this could also include changing to using a fixed filename on disk, while keeping the current Content-DIsposition header to give the user their desired filename. This may however require backwards compatibility or a migration script for old downloads.

**Comment by ansell** [comment]
The change I made doesn't seem to have been picked up in all of the necessary places, as I was able to get a download file name with the unsanitised characters in it ``testing-downloads-!@`` should have been rewritten to ``testing-downloads-__``, but wasn't for some currently unknown reason.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
