### ISSUE TITLE
wkt searching not working?

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#172]
_From @raymondben on August 10, 2017 5:15_

Hi guys. I think occurrence searching with WKT is not working correctly:

In R:
```
occurrences("species_guid:\"urn:lsid:biodiversity.org.au:afd.taxon:26d93abf-b5bf-43ea-91f3-4187e30619c5\"",wkt="POLYGON((-180 -45,180 -45,180 0,-180 0,-180 -45))",download_reason=10)
```
gives me zero records. The equivalent direct API call:
```
wget "http://biocache.ala.org.au/ws/occurrences/index/download?q=species_guid%3A%22urn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A26d93abf-b5bf-43ea-91f3-4187e30619c5%22&wkt=POLYGON%28%28-180%20-45%2C180%20-45%2C180%200%2C-180%200%2C-180%20-45%29%29&reasonTypeId=10&sourceTypeId=2001&esc=%5C&sep=%09&file=data"
```

But if I drop the WKT part I get data back, and inspecting their lats and longs there are data within my WKT bounds.
```
x <- occurrences("species_guid:\"urn:lsid:biodiversity.org.au:afd.taxon:26d93abf-b5bf-43ea-91f3-4187e30619c5\"",download_reason=10)
nrow(x$data)
## 3683
range(x$data$latitude,na.rm=TRUE)
## -41.45000 -10.73052
range(x$data$longitude,na.rm=TRUE)
## 114.2667 153.5000
```
or equivalently
```
wget "http://biocache.ala.org.au/ws/occurrences/index/download?q=species_guid%3A%22urn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A26d93abf-b5bf-43ea-91f3-4187e30619c5%22&reasonTypeId=10&sourceTypeId=2001&esc=%5C&sep=%09&file=data"
```

Same thing happens with occurrence searching (via API `http://biocache.ala.org.au/ws/occurrences/search?q=...`)

Is it busted? Or am I doing something stupid?

_Copied from original issue: AtlasOfLivingAustralia/bie-index#155_

**Comment by nickdos** [comment]
_From @raymondben on August 17, 2017 5:22_

Minor update: this works, if that helps trace the issue.

```
xy <- specieslist(wkt="POLYGON((-180 -45,180 -45,180 0,-180 0,-180 -45))")
```

(it hits `http://biocache.ala.org.au/ws/occurrences/facets/download?wkt=...`)

**Comment by nickdos** [comment]
_From @raymondben on September 5, 2017 3:48_

Update again: it's got something to do with negative longitudes:

Confirm original issue:
```
> x <- occurrences(wkt="POLYGON((-180 -45,180 -45,180 -44,-180 -44,-180 -45))",download_reason=10)
> 
> nrow(x$data)
[1] 0
```

Just use positive longitudes:
```
> x <- occurrences(wkt="POLYGON((0 -45,180 -45,180 -44,0 -44,0 -45))",download_reason=10)
## API call: http://biocache.ala.org.au/ws/occurrences/index/download?wkt=POLYGON%28%280%20-45%2C180%20-45%2C180%20-44%2C0%20-44%2C0%20-45%29%29&reasonTypeId=10&sourceTypeId=2001&esc=%5C&sep=%09&file=data

> nrow(x$data)
[1] 184397
```

Change the westernmost longitude bound from 0 to -1 (i.e. enlarge the area slightly, so should get more records):
```
> x <- occurrences(wkt="POLYGON((-1 -45,180 -45,180 -44,-1 -44,-1 -45))",download_reason=10)

http://biocache.ala.org.au/ws/occurrences/index/download?wkt=POLYGON%28%28-1%20-45%2C180%20-45%2C180%20-44%2C-1%20-44%2C-1%20-45%29%29&reasonTypeId=10&sourceTypeId=2001&esc=%5C&sep=%09&file=data

> 
> nrow(x$data)
[1] 8477
```
But we get less records ... and inspecting the longitudes of the results they lie between -180 and -6, and +178 and +180.

**Comment by nickdos** [comment]
Getting Adam to look into this...

Looks like issue might be due to polygon crossing date line. Adding WKT to map via UI has similar issues:

http://biocache.ala.org.au/occurrences/search?q=*%3A*&qc=&wkt=POLYGON((-180+-45,180%20-45,180%200,-180%200,-180%20-45))#tab_mapView

**Comment by adam-collins** [comment]
-180 == 180 and the default dateline handling was setting the width to 0.

Switched to always use counter clockwise regions and it appears to be working.

**Comment by raymondben** [comment]
Thanks Adam, will give it a go later today and report back ...

**Comment by raymondben** [comment]
Yup, looks good to me. Thanks chaps!

**Comment by djtfmartin** [comment]
from the conversation above this is fixed? closing - please reopen if not
