### ISSUE TITLE
Download "qa=includeall" missing userQualityAssertion

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#177]
When an offline download requests `qa=includeall`, the resulting download does not contain the field `userQualityAssertion`.

Can be tested with this search:

http://biocache.ala.org.au/occurrences/search?q=state%3A*&fq=%28user_assertions%3A%2250005%22+OR+user_assertions%3A%2250003%22+OR+user_assertions%3A%2250002%22+OR+user_assertions%3A%2250001%22%29&qc=data_hub_uid:dh9

`userVerified` appears but not `userQualityAssertion`. Is this a bug or a limitation of index/cassandra?

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
