### ISSUE TITLE
Download documentation - needs an edit

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#18]
_From @nickdos on January 20, 2015 2:50_

_From @mbohun on August 19, 2014 11:16_

_migrated from:_ https://code.google.com/p/ala/issues/detail?id=230
_date:_ Mon Aug 12 03:24:21 2013
_author:_ johntan...@gmail.com

---

Records downloaded through the BioCache come with a README file which contains a link to information about the Download Fields:
[https://docs.google.com/spreadsheet/ccc?key=0AjNtzhUIIHeNdHhtcFVSM09qZ3c3N3ItUnBBc09TbHc#gid=0](https://docs.google.com/spreadsheet/ccc?key=0AjNtzhUIIHeNdHhtcFVSM09qZ3c3N3ItUnBBc09TbHc#gid=0)

Some of the fields have explanations that are not helpful. For example:
Coordinate Precision    The precision of the coordinates
Coordinate Uncertainty In Meters    Distance from the occurrence

Although there is a link to the Darwin Core Terms for the fields, the description could be more helpful for a person needing to understand what they have downloaded.

Other editing requirements
ACRONYMS need explaining eg GUID, IBRA, IMCRA
Spelling 
Links to further assistance
Some issue flags missing definitions

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#39_

_Copied from original issue: AtlasOfLivingAustralia/bie-service#2_

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 11:16_


*date:* Mon Aug 12 17:08:14 2013
*author:* moyesyside
 ---

*(No comment was entered for this change.)*

 ---
**UPDATES:**
*Owner:* moyesyside

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 11:16_


*date:* Wed Jul 16 22:46:34 2014
*author:* moyesyside
 ---

*(No comment was entered for this change.)*

 ---
**UPDATES:**
*Labels:* Biocache

**Comment by nickdos** [comment]
Lee has done some work on this doc... needs reviewing to see if we can close this issue.

**Comment by adam-collins** [comment]
Downloads now include headings.csv, a list of the fields in the download with descriptions from message.properties.
