### ISSUE TITLE
Failed download still generates DOI 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#181]
One of my test downloads failed and I got an error email:

> The download has failed. uniqueId:dd0dfc2b-2e11-30ce-91bb-ca8afff9715e-1512953391552 path:/dd0dfc2b-2e11-30ce-91bb-ca8afff9715e/1512953391552/records-2017-12-11.zip

However, the download still appears in my download list, via the DOI service but has an empty download file value.

I think the DOI should not be generated if the download fails.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
