### ISSUE TITLE
Shapefiles must have 255 fields or less

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#188]
There is a known restriction that shapefiles must have 255 fields or less. The GeoTools API however seems happy to write a shapefile with more fields, but can't necessarily read the result back in. Isn't clear whether the actual shapefile is corrupted or whether it is an inbuilt limitation in the reader to 255 fields which the writer may not have.

Either way, we should be rejecting downloads in shapefile format if the user requests more than 255 fields so we are not generating incompatible/unreadable shapefiles.

**Comment by djtfmartin** [comment]
No longer supporting SHP file downloads. Closing
