### ISSUE TITLE
Support shape file friendly spreadsheet export

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#19]
_From @djtfmartin on August 19, 2014 11:23_

_migrated from:_ https://code.google.com/p/ala/issues/detail?id=244
_date:_ Sun Aug 18 18:42:16 2013
_author:_ moyesyside

---

Support shape file friendly spreadsheet export

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#41_

**Comment by nickdos** [comment]
Not enough details to implement (by me anyway). We've not had another request for this since it was suggested in 2013 so leaving in backlog for now.

**Comment by djtfmartin** [comment]
FIne by me. This was an old request from WA state dept.

Essentially it just requires field names  of no more than 10 characters.
This is a limitation on the DBF file format which a lot of GIS tools work with.

https://www.google.com.au/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=dbf%20field%20name%20length&es_th=1

**Comment by adam-collins** [comment]
Enabling the Shapefile export format in the download UI should satisfy this issue. Any GIS tools will be able to use the shapefile instead of the csv with shorter field names.

**Comment by adam-collins** [comment]
Added shapefile option to download plugin https://github.com/AtlasOfLivingAustralia/downloads-plugin/commit/703db21ba6e610336c16b423e42fd36c035b9230

**Comment by adam-collins** [comment]
Documentation api.ala.org.au lists SHAPE.
