### ISSUE TITLE
Remove/replace use of Graphics2D APIs that are internally synchronized

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#191]
We are currently using the standard Java Graphics2D API implementation which is based on a single-threaded rendering to screen model. Hence, there are places internally where the entire JVM is synchronized on an operation. This is causing blocking to occur between otherwise independent WMS tile rendering threads.

Need to explore an alternative renderer that takes advantage of the multi-core resources we are using for biocache service when generating WMS tiles. The JAI libraries that we already have on the classpath may not have the impediment, although I haven't looked into it.

**Comment by adam-collins** [comment]
I cannot find any blocking when running with the default java.awt.headless=true.

**Comment by ansell** [comment]
The blocking was observed in `jvisualvm` over JMX with multiple threads blocked on acquiring locks for the same object inside of the graphics API classes. It was then verified in a debugger by stepping through the calls to verify where the global synchronisation points occurred.

From memory the culprit's included the implementations of `drawOval` but were not limited to those methods. Sorry for not including replication details in the original report.

Some examples of calls to that method are the following:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/web/WMSController.java#L1840

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/web/WMSController.java#L1904

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
