### ISSUE TITLE
Index downloads only showing first value when field is 'multiValued'

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#195]
See https://github.com/AtlasOfLivingAustralia/ALA4R/issues/31

The "index" download is providing a column called "Outlier for layer" which only includes a single value in the data rows. In SOLR this field is a `multiValued`.

Fix is to dump all the values either as pipe delimited or as a JSON array string (is there a precedence with other `multiValued` fields?).

We should also include the `outlier_layer_count` field in the default set of fields (`outlier_layer` is in this set), which would make it easier for users to correlate the expected number of values.

**Comment by nickdos** [comment]
How about make it a comma (or semicolon) joined string?

**Comment by ansell** [comment]
Semi-colons aren't widely used in other contexts, but may still need to check the contents of the fields, or create an escape sequence if people are worried that they could be splitting contents up further than necessary. Comma would probably cause more issues than it solves given its use in general prose.

Getting access to the full content of ``multiValued`` fields is important so definitely want to keep working on a solution for it.

**Comment by adam-collins** [comment]
To retrieve multiple values use the parameter ```includeMultivalues=true```

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/dto/SearchRequestParams.java#L65

The current delimiter is ```|```

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
