### ISSUE TITLE
Headings metadata file in downloads does not contain the 10 character shapefile field names

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#196]
The downloads that are generated with the headings.csv file do not currently contain the 10 character shapefile field names. It isn't always easy to translate the 10 character names back to the regular field names. Even though it is possible for humans the do the translation with some effort, it would be great to have a systematic translation from the 10 character names. The 10 character names can change per download because of the nature of the uniqueness algorithm used to create the field names and the dynamic field selection for downloads.

**Comment by ansell** [comment]
Refs ticket 15364

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
