### ISSUE TITLE
Static map generation error

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#198]
The call below produces the error shown further below.

https://biocache-clustered.ala.org.au/ws/mapping/wms/image?pradiusmm=1&extents=96.173828125,-47.11468820158343,169.826171875,-2.5694811631203973&scale=on&outline=true&fileName=MyMap.jpg&pcolour=3531FF&outlineColour=0x000000&q=Macropus+rufus&dpi=300&format=jpg&baselayer=world&popacity=1

Error:

```
{
"message": "Can't get input stream from URL!",
"errorType": "Server error"
}
```

The same call in current production works fine.

**Comment by djtfmartin** [comment]
this is working. closing
