### ISSUE TITLE
include indication of annotations in downloads

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#20]
_From @djtfmartin on August 19, 2014 11:54_

_migrated from:_ https://code.google.com/p/ala/issues/detail?id=271
_date:_ Wed Oct  2 21:36:30 2013
_author:_ moyesyside

---

Additional download fields to indicate the presence of user provided annotations.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#46_

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 11:54_


*date:* Wed Jul 16 22:46:44 2014
*author:* moyesyside
 ---

*(No comment was entered for this change.)*

 ---
**UPDATES:**
*Labels:* Biocache

**Comment by nickdos** [comment]
Is this related to issue #21?

**Comment by djtfmartin** [comment]
yes i think so

**Comment by adam-collins** [comment]
For index downloads use field user_assertions. Descriptions are in i18n.

For offline downloads use field userQualityAssertionColumn to include user assertion details.
