### ISSUE TITLE
GeoTools resource leak

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#202]
GeoTools is emitting resource leak warnings on the logs on biocache-clustered that will need to be fixed in code:

```
2018-04-10 16:08:55,059 [org.geotools.data] There's code leaving transaction unclosed. Call Transaction.close() after using them to ensure they do not hold state such as JDCB connections or file handles
2018-04-10 16:08:55,059 [org.geotools.data] Unclosed transaction handle is 'create'
```

**Comment by ansell** [comment]
The ``Transaction`` is opened at:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/325088c96cf68bf68ce8367e0ddcb4fdce4e3510/src/main/java/au/org/ala/biocache/writer/ShapeFileRecordWriter.java#L78

And should be closed by the ``finalise`` method at:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/325088c96cf68bf68ce8367e0ddcb4fdce4e3510/src/main/java/au/org/ala/biocache/writer/ShapeFileRecordWriter.java#L218

The ``finalise`` method is called from the following location that isn't in a try-finally, and hence may not be called consistently:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/325088c96cf68bf68ce8367e0ddcb4fdce4e3510/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L647

The following calls look okay, as they are in try-finally blocks:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/325088c96cf68bf68ce8367e0ddcb4fdce4e3510/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L869

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/325088c96cf68bf68ce8367e0ddcb4fdce4e3510/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L1269

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/325088c96cf68bf68ce8367e0ddcb4fdce4e3510/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L1763

There is a call in a try-finally block but not on its own, so it is not guaranteed to be called:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/325088c96cf68bf68ce8367e0ddcb4fdce4e3510/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L1469

**Comment by javier-molina** [comment]
#213 is a blocker to test this

Neither latitude and longitude nor decimallatitude.p and decimallongitude.p are present in the current field list.

**Comment by djtfmartin** [comment]
ive removed the references to `decimallatitude.p` and `decimallongitude.p` on the 2.x branch

https://github.com/AtlasOfLivingAustralia/biocache-service/commit/850005d41a72047174512b4e7fd8bbc5aa9840e2

this is possible the result of a bad merge.

Any `decimallatitude.p` and `decimallongitude.p` references should be replaced with `decimallatitude_p` and `decimallongitude_p`.

Cassandra 3 had a problem with field names with periods.

**Comment by ansell** [comment]
There is also a design issue, in that the field is allocated to a final field during construction, but if the constructor fails (as it can with its non-trivial operations), there is no way that the ``finalise`` method can be called, because the object reference is never fully constructed. It would be ideal to allocate the Transaction (and the other non-trivial fields) in an ``initialise`` method after the constructor completes, so that we have an object reference on which to call ``finalise`` if something goes wrong.

**Comment by djtfmartin** [comment]
Can this be closed ?

**Comment by ansell** [comment]
Yes, I fixed this issue
