### ISSUE TITLE
clustered: Download won'd mint DOI

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#204]
Despite including the mintDoi=true the download request below will generate a zip file without DOI.

https://biocache-clustered.ala.org.au/ws/occurrences/offline/download?hubName=Atlas+of+Living+Australia&file=records-2018-04-13&extra=dataResourceUid%2CdataResourceName.p%2Crecord_number&mintDoi=true&reasonTypeId=10&constraintsMap=%7BtotalRecords%3D%5BConstrainedProperty%4030a701eeDownloadParams%27totalRecords%27Longmap%5B%27nullable%27+-%3E+%5BNullableConstraint%40645e4572false%5D%5D%5D%2C+dwcHeaders%3D%5BConstrainedProperty%40599f9465DownloadParams%27dwcHeaders%27Booleanmap%5B%27nullable%27+-%3E+%5BNullableConstraint%4078d597c6false%5D%5D%5D%2C+customHeader%3D%5BConstrainedProperty%4070f55143DownloadParams%27customHeader%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%406696fffafalse%5D%5D%5D%2C+downloadFormat%3D%5BConstrainedProperty%40438f73f1DownloadParams%27downloadFormat%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%4017b0b7e1false%5D%5D%5D%2C+mintDoi%3D%5BConstrainedProperty%404d15831dDownloadParams%27mintDoi%27Booleanmap%5B%27nullable%27+-%3E+%5BNullableConstraint%401caddc6afalse%5D%5D%5D%2C+searchParams%3D%5BConstrainedProperty%40248534f5DownloadParams%27searchParams%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%403618803bfalse%5D%5D%5D%2C+sourceTypeId%3D%5BConstrainedProperty%405774f08eDownloadParams%27sourceTypeId%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%4025482886false%5D%5D%5D%2C+customClasses%3D%5BConstrainedProperty%4028678246DownloadParams%27customClasses%27Listmap%5B%27nullable%27+-%3E+%5BNullableConstraint%405a0cd629true%5D%5D%5D%2C+qa%3D%5BConstrainedProperty%402a8cbd66DownloadParams%27qa%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%404e64bca9false%5D%5D%5D%2C+layersServiceUrl%3D%5BConstrainedProperty%405a857291DownloadParams%27layersServiceUrl%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%4066844a76false%5D%5D%5D%2C+file%3D%5BConstrainedProperty%40292cac4dDownloadParams%27file%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%4042c6cc35false%5D%5D%5D%2C+reasonTypeId%3D%5BConstrainedProperty%4033263f06DownloadParams%27reasonTypeId%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%4077b514eefalse%5D%5D%5D%2C+includeMisc%3D%5BConstrainedProperty%403b379091DownloadParams%27includeMisc%27Booleanmap%5B%27nullable%27+-%3E+%5BNullableConstraint%404f6444a6false%5D%5D%5D%2C+extra%3D%5BConstrainedProperty%404db89c43DownloadParams%27extra%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%401275e37efalse%5D%5D%5D%2C+targetUri%3D%5BConstrainedProperty%4015c15ab9DownloadParams%27targetUri%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%4078ed7dd3false%5D%5D%5D%2C+layers%3D%5BConstrainedProperty%40713ebc09DownloadParams%27layers%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%404c6dcf43false%5D%5D%5D%2C+downloadType%3D%5BConstrainedProperty%4053e640e5DownloadParams%27downloadType%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%404076bcaffalse%5D%5D%5D%2C+hubName%3D%5BConstrainedProperty%40442c9e5cDownloadParams%27hubName%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%406619464dfalse%5D%5D%5D%2C+searchUrl%3D%5BConstrainedProperty%40719d303DownloadParams%27searchUrl%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%40727f848bfalse%5D%5D%5D%2C+doiDisplayUrl%3D%5BConstrainedProperty%4052013ae6DownloadParams%27doiDisplayUrl%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%407e0635c5false%5D%5D%5D%2C+fields%3D%5BConstrainedProperty%40374e70cdDownloadParams%27fields%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%40391be173false%5D%5D%5D%2C+email%3D%5BConstrainedProperty%4062962abcDownloadParams%27email%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%402d718336false%5D%5D%5D%2C+fileType%3D%5BConstrainedProperty%40697d464dDownloadParams%27fileType%27Stringmap%5B%27nullable%27+-%3E+%5BNullableConstraint%40f0b2268false%5D%5D%5D%7D&searchUrl=https%3A%2F%2Fbiocache-clustered.ala.org.au%2Foccurrences%2Fsearch%3Fq%3Dlsid%253Aurn%253Alsid%253Abiodiversity.org.au%253Aafd.taxon%253Ae6aff6af-ff36-4ad5-95f2-2dfdcca8caff%26fq%3Dmonth%253A%252204%2522&fileType=csv&qa=none&sourceTypeId=0&email=javier.molina%40csiro.au&doiDisplayUrl=https%3A%2F%2Fbiocache-clustered.ala.org.au%2Fdownload%2Fdoi%3Fdoi%3D&q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ae6aff6af-ff36-4ad5-95f2-2dfdcca8caff&fq=month%3A%2204%22

**Comment by djtfmartin** [comment]
assume this fixed now as DOIs are being generated
