### ISSUE TITLE
clustered: biocache-service.log is very quiet

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#205]
The log file /var/log/tomcat7/biocache-service.log seem to be very quiet on bdown-b5 despite testing going on.

The same file on bws-b5 a and b has slightly mose activity though not much as to be useful for diagnosis.

log4j.xml needs to be tweaked for testing and it needs to be confirmed that this file indeed is the one biocache-service uses to load logging configuration.

**Comment by djtfmartin** [comment]
closing  - the log file seems fine to me and im seeing the expected output
