### ISSUE TITLE
Search Query activeFacetMap shows only last facet query

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/biocache-service#209]
activeFacetMap does not output values correctly - only seem to pick the last excluded facet query
For eg: 
[https://biocache.ala.org.au/ws/occurrences/search?q=data_resource_uid:dr341&fq=-basis_of_record:"HumanObservation"&fq=-basis_of_record:"MachineObservation"&fq=-basis_of_record:"FossilSpecimen"&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&flimit=10](https://biocache.ala.org.au/ws/occurrences/search?q=data_resource_uid:dr341&fq=-basis_of_record:%22HumanObservation%22&fq=-basis_of_record:%22MachineObservation%22&fq=-basis_of_record:%22FossilSpecimen%22&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&flimit=10)

Currently activeFacetMap shows only the last excluded fq
![image](https://user-images.githubusercontent.com/1606595/38968811-5f3e1540-43d0-11e8-9d8f-066f28011d7b.png)

Expected result should have activeFacetMap showing 3 excluded fq

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
