### ISSUE TITLE
Improved Biocache download metadata and documentation

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#21]
_From @mbohun on August 19, 2014 11:55_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=277
*date:* Tue Oct 15 21:17:05 2013
*author:* natasha....@csiro.au
 ---

At the moment the metadata for the download is based on the default fields that are included in the download. It would be nice if it could include all the fields that were requested in the download.

Very apparent when users are constructing the download URL using customised field lists.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#48_

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 11:55_


*date:* Tue Oct 15 21:43:37 2013
*author:* natasha....@csiro.au
 ---

Hi Natasha,
 
I was thinking that a complete listing of fields should be provided regardless of the requested subset or the default set, so that users are aware of all the fields that could be accessed?
 
regards,
Kristen

 ---
**UPDATES:**
*Cc:* Kristen....@csiro.au
*Labels:* Biocache

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 11:55_


*date:* Tue Oct 15 21:44:07 2013
*author:* natasha....@csiro.au
 ---

The downloads are extremely flexible, the number of possible fields that can be included is in excess of 100. I can see a situation where a user would get confused if they were presented with a metadata for all the fields. 

Maybe we need a link on the [http://biocache.ala.org.au/ws](http://biocache.ala.org.au/ws) page that has the metadata for all the fields. This would be separate from the metadata that is included with the download.

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 11:55_


*date:* Tue Oct 15 22:58:40 2013
*author:* natasha....@csiro.au
 ---

Comments from Mike:

There seem to be several places to get ALA metadata, with some overlap:

(1) The one Natasha lists below ([https://docs.google.com/spreadsheet/ccc?key=0AjNtzhUIIHeNdHhtcFVSM09qZ3c3N3ItUnBBc09TbHc#gid=0](https://docs.google.com/spreadsheet/ccc?key=0AjNtzhUIIHeNdHhtcFVSM09qZ3c3N3ItUnBBc09TbHc#gid=0)), which matches the default fields.  It would be useful if this list of metadata could be downloaded via a link at [http://biocache.ala.org.au/ws](http://biocache.ala.org.au/ws) and also contained the (?database) field names that appear in (2) and (3) below. Only Default columns and Issue flags — no Environmental and Contextual columns.

(2) Via the help page for Occurrence web services there is a list of fields ([http://biocache.ala.org.au/ws/index/fields](http://biocache.ala.org.au/ws/index/fields)), which doesn't explain the names (see attached — ALA-metadata-list-type2-biocache-ws-index-fields.csv).  It includes only the list of field names as they should  be specified in a biocache URL, and not any of the descriptions or DC links included per (1). A human-readable form of the cryptic field names (eg. el760) seem to be available via (3) below. Only Environmental and Contextual columns — no default columns  or issue flags in this metadata. 

(3) The fields associated with the spatial web services ([http://spatial.ala.org.au/ws/fields](http://spatial.ala.org.au/ws/fields)) I presume are shared with those in the biocache, and use the same cryptic field names eg. cl1049 (see attached — ALA-metadata-list-type3-spatial-ws-fields.csv). The field names are not given directly (eg. cl1049 has to be reassembled via the id and type columns).  Only Environmental and Contextual columns — no default columns  or issue flags in this metadata (eg. genus or 'Genus - matched').

(4) The fields associated with the spatial web layers ([http://spatial.ala.org.au/ws/layers](http://spatial.ala.org.au/ws/layers)) also seem to overlap with the biocache metadata. In this set of metadata the field id is split across two columns — id and type. Only Environmental and Contextual columns — no default columns  or issue flags in this metadata.  Also column names vary from (3) and columns such as description vary in content for the same field (eg. cl927). 

I apologise for seeming pedantic. The above was to document this issue and so hone in on my data needs. 

I think what we're seeking are:
(a) consistent sources of metadata, where ever in ALA they are accessed,
(b) a means to specify any set of fields and flags to download from biocache, and 
(c) a way to know how the specified download field names (eg. genus) will appear in the downloaded data (eg. `Genus – matched').


 ---
**UPDATES:**
*Summary:* Improved Biocache download metadata and documentationWAS:(was: Make metadata for biocache download dynamic)

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 11:55_


*date:* Tue Apr 29 16:48:24 2014
*author:* natasha....@csiro.au
 ---

The index field documentation now includes the header values (i18n) that they use when they are included in a download: [http://biocache.ala.org.au/ws/index/fields](http://biocache.ala.org.au/ws/index/fields)

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 11:55_


*date:* Thu May  1 21:33:12 2014
*author:* natasha....@csiro.au
 ---

This may need some more work to consolidate and provide a consistent view of download field names.

Some of the custom fields are not included in the [https://docs.google.com/spreadsheet/ccc?key=0AjNtzhUIIHeNdHhtcFVSM09qZ3c3N3ItUnBBc09TbHc#gid=0](https://docs.google.com/spreadsheet/ccc?key=0AjNtzhUIIHeNdHhtcFVSM09qZ3c3N3ItUnBBc09TbHc#gid=0)

 ---
**UPDATES:**
*Owner:* moyesyside

**Comment by nickdos** [comment]
Suggestion: to include a third CSV file in the downloads ZIP, which is a file with more details about the "headings" data - e.g. use a simple code in the headings row and then provide additional info and any field mappings, etc. It would effectively provide the info in the second Google doc sheet.
Headings column in main data.csv file could then used SOLR codes or some other code (cassandra) (instead of the sometimes long-winded headings).

**Comment by adam-collins** [comment]
Adding a headers.csv that lists the headers in the data.csv, the corresponding requested field, and some additional information from indexed/fields.

headers.csv column headers:
```
Column name,Requested field,DwC Name,Field name,Field description,Download field name,Download field description,More information
```

To have less readable headings in the downloads there is the option of &dwcHeaders=true to use dwc or SOLR field names if no dwc mapping is provided.

Is more required on this issue?
