### ISSUE TITLE
Cluster: Missing id field

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#214]
In current [prod](https://biocache.ala.org.au/ws/index/fields)   the field id is present however it is no longer available in the cluster.

```
{
"name": "id",
"dataType": "string",
"indexed": true,
"stored": true,
"multivalue": false,
"description": "Record ID",
"info": "ALA ID for this record.",
"jsonName": "uuid",
"downloadName": "uuid",
"downloadDescription": "Record ID"
},
```

Nick suggested we still need and unique identifier, possibly rowKey however looks like the mapping is not right, the [downloadField is row_key](https://devt.ala.org.au/biocache-service/ws/index/fields), most likely it should be rowKey.

```
{
"name": "row_key",
"dataType": "string",
"indexed": true,
"stored": true,
"multivalue": false,
"downloadName": "row_key"
},
```

If rowKey is not a unique identifier we need to have one.

This is related to #213

**Comment by javier-molina** [comment]
row_key works and it is the new unique identifier.

**Comment by djtfmartin** [comment]
id = uuid = rowkey

They are all the same thing in 2.x. As far as the API is concerned we should standardise on one term and support a legacy mapping.

**Comment by javier-molina** [comment]
See commit above for downloads plugin, now it is possible to specify what is the primary field.

@adam-collins I think you are the best person to address Dave's comments.

**Comment by vjrj** [comment]
Should we add another default value in
https://github.com/AtlasOfLivingAustralia/ala-install/blob/482406a604ea5cdb11baaf1e7f8d3b8669d3a3e7/ansible/roles/biocache-hub/templates/config/config.properties#L189
Because I get
```
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name uuid   
```
