### ISSUE TITLE
Downloads: add param for to include all DwC fields

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#217]
As suggested by @djtfmartin, there is logic in the downloads-plugin that generates a list of `fields` for the "Darwin Core" download option, that should be moved into biocache-service.

- [ ] Add param `includeDwc=true|false`, to be consistent with the existing `includeMisc=true` param
- [ ] Add param `dwcClasses=record,occurrence,identification,...`, which are the values from the `classs`attribute for [fields](https://biocache-clustered.ala.org.au/ws/index/fields) (to lowercase)
- [ ] Rules for selecting fields to be included - both params are set: `dwcClasses` should be checked and only include fields from those classes; only `includeDwc` is set: all fields; only `dwcClasses` is set: include just those fields (so effectively ignore `includeDwc` if `dwcClasses` is set.)

The list of DwC fields to be extracted from the `/index/fields` endpoint (look for the `dwcTerm` attribute) and fields to ordered by `classs` and then alphabetic (or alteratively orderd specified by the DwC spec - see https://raw.githubusercontent.com/tdwg/dwc/master/downloads/SimpleDwCCSVheaderUTF8.txt). There may already be code in biocache-service, which is used for the `/index/fields` endpoint so do a search first.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
