### ISSUE TITLE
OGC getFeatureInfo not working

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#218]
E.g. https://biocache.ala.org.au/ws/ogc/getFeatureInfo?lat=-12.61328125&lon=47.724609375&radius=50&wkt=POLYGON((-31.201171875%20-61.3046875%2C-58.798828125%20-61.3046875%2C-58.798828125%208.3046875%2C-31.201171875%208.3046875%2C-31.201171875%20-61.3046875))

returns 500 error:

```
{
  message: "null",
  errorType: "Server error"
}
```

~~Nothing triggered in logs that I could find.~~ Looking on wrong server it turns out - catalina.out shows this output:

    java.lang.NullPointerException

So it looks like a `system.out.println` message and not using log4j.

I get the same error with biocache-clustered.ala.org.au.

Reported here: https://support.ehelp.edu.au/helpdesk/tickets/16536

**Comment by djtfmartin** [comment]
Fixed in clustered. Closing as we'll make the switch very soon

**Comment by nickdos** [comment]
The service is reporting "No records at this point." for every query I've tried (that work with the search service). So re-opening.

**Comment by nickdos** [comment]
Hi @djtfmartin, here is another issue to look at if you're in the code... see my last comment, I can confirm its still returning the "no records" message, e.g. https://biocache.ala.org.au/ws/ogc/getFeatureInfo?q=*:*

**Comment by djtfmartin** [comment]
this is fixed (tested with QGIS client).

**Comment by ansell** [comment]
@djtfmartin @nickdos This is broken, but I didn't notice this issue and created a new issue for it at #351
