### ISSUE TITLE
Add a 'record verified/corrected' option in the list of assertion categories

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#22]
_From @chrisala on August 19, 2014 11:56_

_migrated from:_ https://code.google.com/p/ala/issues/detail?id=283
_date:_ Tue Nov  5 21:59:40 2013
_author:_ chris.go...@gmail.com

---

Requested via support email on 6/11.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#51_

**Comment by adam-collins** [comment]
User assertion status appears to be implemented and in use; open issue, correct, verified, unconfirmed

http://biocache.ala.org.au/ws/occurrences/search?q=-user_assertions:false&facets=user_assertions&pageSize=0
