### ISSUE TITLE
Record downloads & DOI citation changes

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#222]
`TL;DR` filter citation list to only show lines for "data resources" - e.g. `/show/dr\d+/` in URL.

The `README.html` file contained within the download ZIP file includes a list of all the entities in the Collectory that contributed data to that particular download. The problem is the list is too long, has apparent duplicate entries (same `name` for different DR, DR and CO types in Collectory) and many are missing citation details (empty text inside braces). 

The same problem applies to the DOI landing page with the table showing list of datasets for the download - basically the same data as above.

After talking to Miles, we think that this list can be filtered/truncated to include entries that have a "data resource" type only. For both README.html and the DOI citation list (send to DOI server).

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
