### ISSUE TITLE
Fragile WKT in sites_by_species

### ISSUE THREAD

**Issue by raymondben** [AtlasOfLivingAustralia/biocache-service#225]
This call has an extra space before one of the WKT longitudes (look for the ",%20144"):

```
http://spatial.ala.org.au/alaspatial/ws/sitesbyspecies?speciesq=genus:Eucalyptus&qname=data&area=POLYGON((144%20-43,148%20-43,148%20-40,%20144%20-40,144%20-43))&bs=http://biocache.ala.org.au/ws/&movingaveragesize=1&gridsize=0.1&sitesbyspecies=1
```

That call returns an empty response with a 200 header - i.e. no indication of failure but also no job PID that we would expect if the job had been queued. As far as I'm aware the extra space in the WKT string is not illegal.

Removing the extra space:

```
http://spatial.ala.org.au/alaspatial/ws/sitesbyspecies?speciesq=genus:Eucalyptus&qname=data&area=POLYGON((144%20-43,148%20-43,148%20-40,144%20-40,144%20-43))&bs=http://biocache.ala.org.au/ws/&movingaveragesize=1&gridsize=0.1&sitesbyspecies=1
```
And everything works as expected.

In the first case the server-side WKT parsing must be failing, but the server response gives no indication that I can see that this is the case. Suggest either less fragile parsing or more informative error.
CC @PeggyNewman , this is used in ALA4R  `sites_by_species.R`

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
