### ISSUE TITLE
Randomised sequence of data quality test results in CSV data output

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#23]
_From @pbrenton on August 19, 2014 12:21_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=489
*date:* Wed Dec 18 17:02:01 2013
*author:* CoolDa...@gmail.com
 ---

Reported by user wanting to do periodic manual exports from ALA to import into a local system for mapping and analysis.

The sequence of columns for DQ test results is inconsistent in the CSV output between different download events. Client is finding this makes processing on his end difficult.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#54_

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 12:22_


*date:* Wed Dec 18 19:32:57 2013
*author:* natasha....@csiro.au
 ---

How is the user donwloading the records?

There is a way to stop the DQ from being included in the downloads.  We don't expose it as an option in the biocache/hubs/spatial portal webapps.

The biocache-service allows for the DQ to be turned off using a URL of the following format:
biocache.ala.org.au/ws/occurrences/index/download?q=data_resource_uid:dr364&qa=none&reasonTypeId=10

The &qa=none prevents the data quality from being included in the download.

**Comment by nickdos** [comment]
_From @pbrenton on August 19, 2014 12:22_


*date:* Fri Dec 20 02:41:19 2013
*author:* CoolDa...@gmail.com
 ---

Not sure Natasha. He does find the DQ results useful, so switching off is probably not the best option. He was just asking if we can make the sequence of columns consistent in outputs.

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 12:22_


*date:* Sun Dec 22 13:50:47 2013
*author:* natasha....@csiro.au
 ---

The other option is for him to decide which data quality fields he wishes to include and specifying them in the order he wishes to see them:

Example:
[http://biocache.ala.org.au/ws/occurrences/index/download?q=data_resource_uid:dr364&reasonTypeId=10&qa=decimalLatLongConverted,invalidCollectionDate,speciesOutsideExpertRange,stateCoordinateMismatch,invalidScientificName](http://biocache.ala.org.au/ws/occurrences/index/download?q=data_resource_uid:dr364&reasonTypeId=10&qa=decimalLatLongConverted,invalidCollectionDate,speciesOutsideExpertRange,stateCoordinateMismatch,invalidScientificName)


This is not exposed in the biocache/hubs UI.  At the moment it is only available as a webservice call. This field is documented in the download section of the biocache documnetation: 
[http://biocache.ala.org.au/ws](http://biocache.ala.org.au/ws)

Maybe we need to expose this in the Download dialog to allow users to decide which QA fields it include.

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 12:22_


*date:* Sun Dec 22 16:00:16 2013
*author:* natasha....@csiro.au
 ---

There are 2 components to this issue:

1) Ensure that when no &qa param is provided the DQ fields are in the same order each time the exact same download is performed. 

2) In hubs-webapp expose a selection of download fields and QA's for the user to select in the Download dialog.

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 12:22_


*date:* Mon Dec 23 17:44:30 2013
*author:* natasha....@csiro.au
 ---

Component 1) in comment `#4` is on dev

**Comment by adam-collins** [comment]
There is an option qa=includeall that will not remove empty columns like qa=all does. But if assertions ever change in biocache-store the columns returned will change. 

As 2) above suggests is best if qa columns are specified so they do not change over time.

**Comment by adam-collins** [comment]
List of valid qa fields as mentioned above. http://biocache.ala.org.au/ws/assertions/codes

**Comment by adam-collins** [comment]
Is any more required for this issue?
