### ISSUE TITLE
Require HTTP POST to start offline downloads

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#231]
Offline downloads can currently be started using both HTTP GET and HTTP POST. We need to switch to requiring HTTP POST to avoid duplicate downloads being triggered by users browsers refreshing tabs or recently used site buttons after restarting.

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/2.x/src/main/java/au/org/ala/biocache/web/DownloadController.java#L116

Refs ticket 17839

**Comment by nickdos** [comment]
The offline download supports GET and we've advertised this on the API page, so removing it could upset people (ALA4R, et al.).

I made a change to downloads-plugin that prevented the download being triggered via reloading the confirmation page and tested it with Chrome and Safari. https://github.com/AtlasOfLivingAustralia/downloads-plugin/commit/d4ee625cad05c6dac039019bf03828c0d13933eb but this was included in v 1.2 of the plugin and avh is using 1.3.3 so maybe IE is still an issue. At this stage we don't definitively know this is the cause of Anna's issue in the support ticket, so I'm not sure we should proceed without other examples/reports of this. Or unless we can reproduce it manually.

**Comment by ansell** [comment]
I am sure people would understand us switching it to POST-only if they had notice. Since both are supported currently, there would already be a switchover period available if we notified ALA4R about it today.

It is very unusual to support HTTP GET for operations like this. HTTP GET is defined in the HTTP Semantics as idempotent and HTTP User Agents and proxies are free to repeat HTTP GET requests as many times as necessary without expecting side effects.

I have personally had issues in the past where biocache downloads have been retriggered by my browser somehow, and I wouldn't have known about it if it weren't for the repeat emails, but that may have been with older code.

**Comment by ansell** [comment]
A downloads-plugin issue for switching from GET to POST that is blocking this is: 

https://github.com/AtlasOfLivingAustralia/downloads-plugin/issues/24

**Comment by nickdos** [comment]
I couldn't get the offline download to work with POST when I tried it earlier this year - using POSTman and another plugin. I tried a bunch of different request headers but had no luck... Does this need a separate issue or just keep it in here for now?

**Comment by ansell** [comment]
Which content type were you trying it with, ``application/x-www-form-urlencoded`` or ``multipart/form-data``?

Not sure which is required in this case, as I haven't tried it yet myself.

**Comment by nickdos** [comment]
I tried `application/x-www-form-urlencoded` for sure, might've tried the other one as well

**Comment by ansell** [comment]
Also possible that POST doesn't work with ``DownloadRequestParams`` out of the box, or when there are other parameters in addition to it:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/2.x/src/main/java/au/org/ala/biocache/web/DownloadController.java#L118-L121
