### ISSUE TITLE
Legacy download includes two fields only.

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#234]
Using legacy fields in the cluster, a download includes only these two fields:

dataResourceUid
record_number

Probably not the expected behaviour.

**Comment by javier-molina** [comment]
@djtfmartin can you cast an eye on this?

**Comment by djtfmartin** [comment]
I fixed this in the downloads-plugin

https://github.com/AtlasOfLivingAustralia/downloads-plugin/blob/master/grails-app/conf/plugin.groovy#L80

previously ``downloads.legacy.defaultFields`` was not being used.

I think we need to release biocache-hubs / ala-hubs

**Comment by djtfmartin** [comment]
fixed now
I made the following change in ansible

https://github.com/AtlasOfLivingAustralia/ala-install/commit/e3171a8d7a0ccdd86f6b6dcd8b3f0b7ebfb4166c
