### ISSUE TITLE
Download caching - force new download

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#235]
A couple of users have commented that if they run 2 downloads with the same query but change some other parameters for the second one, then they get the first download twice (same path to download file). So the downloads are being cached but in some cases, we'd want to override this caching and force a new download to run. 

Is there a param or simple way of doing this?

If not, then add such a mechanism - maybe a param like `forcedownload=true` or some such.

Linked to ticket https://support.ehelp.edu.au/helpdesk/tickets/18052

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
