### ISSUE TITLE
Add HTTP cache headers to occurrence search

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#239]
To reduce the load on biocache-service and solr, cache headers with configurable lifetimes should be added to the occurrence search web services.

**Comment by ansell** [comment]
The current state where HTTP 200 is used for error responses in some cases also needs to be fixed to ensure that temporary request timeouts or other transient errors are not cached: https://github.com/AtlasOfLivingAustralia/biocache-service/issues/161

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
