### ISSUE TITLE
Conservation status facet not reflecting species status

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#24]
_From @Tasilee on August 19, 2014 12:58_

_migrated from:_ https://code.google.com/p/ala/issues/detail?id=597
_date:_ Tue Feb 25 19:13:40 2014
_author:_ leebel...@gmail.com

---

Add to Map | Species | Mogurnda clivicola

This species is listed as "Vulnerable" (AU) in the species page but not in the facets.

State conservation
State conservation status (unprocessed)

This seems to imply that a species listed under the EPBC act will not reflect in either of the two conservation status facets? If so, not nice.

This issue was raised by a user from SA (via Robyn Lawrence) who was attempting to find out what fish species in SA had a conservation status.

Apparently there are 16 fish species in SA with some conservation status while the ALA reports 2 as far as I can tell. If I use the SP to facet on lifeform=fish, area=SA with coastal zone, conservation=some status I get 2.

I assume it is a biocache issue.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#60_

**Comment by nickdos** [comment]
I can't make sense of this issue but it appears to be biocache-service related.

**Comment by adam-collins** [comment]
A task for biocache-store.

**Comment by adam-collins** [comment]
On further review, update bie to use http://lists.ala.org.au/ws/speciesList?isBIE=eq:true and update lists to include additional fields from https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/bie-index/files/conservation-lists.json

biocache-store uses http://lists.ala.org.au/ws/speciesList?isThreatened=eq:true&isAuthoritative=eq:true and if updated, running `biocache update-conservation-data` followed by re-running `LocationProcessor`  (reprocess all) is required.

A review of conservation lists should be done before any reprocessing to align http://lists.ala.org.au/ws/speciesList?isThreatened=eq:true&isAuthoritative=eq:true and  https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/bie-index/files/conservation-lists.json

**Comment by nickdos** [comment]
Reminder - lists with least concerned values shoudl be ignored by biocache-store but still used by bie-index...

**Comment by djtfmartin** [comment]
i think this is now fixed
