### ISSUE TITLE
By decade chart showing the total search count for each decade

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#241]
After the fix for #238, the By decade chart controller is now showing the total search count as the value for each decade.

### Eucalyptus gunni

Broken:

```
https://biocache-clustered.ala.org.au/occurrences/search?taxa=eucalyptus+gunni#tab_chartsView
```

![screen shot 2018-06-19 at 6 40 16 am](https://user-images.githubusercontent.com/82365/41560916-de0bd642-738b-11e8-9503-35dc21ac4052.png)

Works:

```
https://biocache.ala.org.au/occurrences/search?q=text:eucalyptus%20OR%20gunni#tab_chartsView
```

![screen shot 2018-06-19 at 6 45 27 am](https://user-images.githubusercontent.com/82365/41561137-66d0f64c-738c-11e8-8229-f11306932682.png)

### Wombat

Broken:

```
https://biocache-clustered.ala.org.au/occurrences/search?taxa=wombat#tab_chartsView
```

![screen shot 2018-06-19 at 6 42 52 am](https://user-images.githubusercontent.com/82365/41561000-16883a24-738c-11e8-9bc6-8f0c2abe4cf9.png)

Works:

```
https://biocache.ala.org.au/occurrences/search?taxa=wombat#tab_chartsView
```

![screen shot 2018-06-19 at 6 46 32 am](https://user-images.githubusercontent.com/82365/41561193-8939d35c-738c-11e8-8df5-5ef1038a4673.png)

**Comment by javier-molina** [comment]
Fix deployed to cluster.

**Comment by djtfmartin** [comment]
looks good. thanks @javier-molina
