### ISSUE TITLE
Very large legend files being generated for mapping with large diverse facets

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#242]
Some of the ``legend`` JSON files that are generated for mapping with large diverse facets can be very large, which impacts the responsiveness of the application, and adds to the ALA bandwidth costs.

Using the ``Scientific Name`` facet on the default search requests the following JSON file
``https://biocache.ala.org.au/occurrence/legend?q=*%3A*&cm=taxon_name&type=application/json`` which is 31.4MB

Using the ``Collectors`` facet on the default search requests the following JSON file ``https://biocache.ala.org.au/occurrence/legend?q=*%3A*&cm=collectors&type=application/json`` which is 78.3MB

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
