### ISSUE TITLE
Search on qid returns data out of the given bbox 

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/biocache-service#244]
By given a qid that has a bbox, biocache return species out of the given bbox.  Seems the starting and ending latitudes of bbox are reversed.

Here are an example:

https://biocache.ala.org.au/ws/webportal/params/details/1529976304853
https://biocache.ala.org.au/occurrences/search?fq=qid:1529988611191#tab_mapView

![screen shot 2018-06-27 at 10 55 54 am](https://user-images.githubusercontent.com/31238531/41947086-f0cfa952-79f8-11e8-97b8-54f9445102d4.png)

**Comment by ansell** [comment]
This is fixed for me on biocache-clustered.ala.org.au, but testing will depend on whether we have switched to clustered or not so ask in Hipchat if you are testing it out. The following URL:

https://biocache-clustered.ala.org.au/occurrences/search?fq=qid%3A1529988611191#tab_mapView

Will redirect you to:

https://biocache.ala.org.au/occurrences/search?fq=qid%3A1529988611191#tab_mapView

So replicating may depend on which system is in production at that point.

**Comment by djtfmartin** [comment]
Closing. As i understand this is fixed in production
