### ISSUE TITLE
Improve email contents when downloads fail

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#246]
Currently when downloads fail the email contents only contains debugging information, which is useful for development but not for end users. It needs to contain text that explains the failure to them and what they should do and then enough information for them to give us an idea of which download failed.

Example of an email I received when my download failed:

```
The download has failed. uniqueId:ad425ee9-ad26-309f-80ec-bf0a27da52de-1530495113290 path:/ad425ee9-ad26-309f-80ec-bf0a27da52de/1530495113290/records-2018-07-02.zip
```

**Comment by Rita-C** [comment]
Updated email as:

> Your download has failed. Please contact support@ala.org.au for assistance.
> 
> searchUrl: https://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ae9d6fbbd-1505-4073-990a-dc66c930dad6&fq=state%3A%22Australian%20Capital%20Territory%22
> uniqueId: eeedb1c7-2072-3149-bf38-a060c973a844-1567489142473 
> path: /eeedb1c7-2072-3149-bf38-a060c973a844/1567489142473/records-2019-08-22.zip

**Comment by ansell** [comment]
Some minor tweaks to that could be the following, with the relevant bits templated the same as the other templates. The path can be identified based on the uniqueId so it isn't necessary to include both:

```
Your Atlas of Living Australia download has failed. Please contact support@ala.org.au by replying to this email and we will investigate the cause.

Your search URL was:

https://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ae9d6fbbd-1505-4073-990a-dc66c930dad6&fq=state%3A%22Australian%20Capital%20Territory%22

The reference to quote is:

eeedb1c7-2072-3149-bf38-a060c973a844-1567489142473

Your successful downloads can be found at:

https://doi.ala.org.au/myDownloads
```

**Comment by Rita-C** [comment]
More changes as suggested @ansell

**Comment by ansell** [comment]
Closing and moving to Ready for CAB on project board
