### ISSUE TITLE
Inconsistent response content types for occurrences/search.json with callbacks

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#247]
Calls to occurrences/search.json when accompanied with a callback paramter (``JSONP``) should be returned with the response content type set to ``text/javascript``. Some calls are, but some are not.

Example the following:

``https://biocache.ala.org.au/ws/occurrences/search.json?q=image_url:c698a927-9256-4fd4-b110-5230e66d2f4a&fq=-assertion_user_id:*&im=true&facet=off&pageSize=1&start=0&callback=jQuery1124030778266592240733_1531186629490&_=1531186629491``

returns its content type correctly as ``text/javascript``

However, the following:

``
https://biocache.ala.org.au/ws/occurrences/search.json?q=lsid:http://id.biodiversity.org.au/node/apni/9387396&fq=multimedia:"Image"&fq=-assertion_user_id:*&im=true&facet=off&pageSize=5&start=0&callback=jQuery1124030778266592240733_1531186629492&_=1531186629493
``

returns its content type incorrectly as ``application/json``

This issue was revealed by switching on the security header ``X-Content-Type: nosniff``, which makes browsers that recognise it fail to load the incorrect content type responses.

This issue appears in both the 1.x and 2.x versions of biocache-service.

**Comment by ansell** [comment]
This is low priority because there is a workaround. 

Another part of testing/fixing this is verifying that when there is no ``callback`` parameter, all responses from ``occurrences/search.json`` return ``application/json`` as their content type. It would also be great to deprecate ``JSONP`` in favour of using ``CORS`` headers, but we need to support ``JSONP`` until that transition is complete.

The original context that triggered this was the failure to load the results for image galleries in BIE in Safari and Chrome (Firefox ignored the security header for some reason). If we want to work on transitioning away from ``JSONP`` to ``CORS`` that could be a good first place to work on.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
