### ISSUE TITLE
Institution name and collection name blanks in downloads when specified (Cassandra download)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#25]
_From @djtfmartin on August 19, 2014 12:59_

_migrated from:_ https://code.google.com/p/ala/issues/detail?id=602
_date:_ Tue Mar  4 20:36:05 2014
_author:_ moyesyside

---

[http://biocache.ala.org.au/ws/occurrences/download?q=red+kangaroo&fields=institution_name,collection_name&reasonTypeId=1](http://biocache.ala.org.au/ws/occurrences/download?q=red+kangaroo&fields=institution_name,collection_name&reasonTypeId=1)

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#62_

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 12:59_


*date:* Tue Mar  4 20:46:46 2014
*author:* moyesyside
 ---

doesnt seem to work for other fields:

e.g

[http://biocache.ala.org.au/ws/occurrences/download?q=Mountain+thornbill&fields=latitude,longitude&reasonTypeId=9](http://biocache.ala.org.au/ws/occurrences/download?q=Mountain+thornbill&fields=latitude,longitude&reasonTypeId=9)

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 12:59_


*date:* Tue Mar  4 20:49:49 2014
*author:* moyesyside
 ---

just realised this is downloads against cassandra as opposed to index....

**Comment by nickdos** [comment]
_From @mbohun on August 19, 2014 12:59_


*date:* Tue Mar  4 20:50:52 2014
*author:* natasha....@csiro.au
 ---

You are using the download from cassandra URL. This needs to take dwca fields as params.

I think that we need to do some work on mapping index and cassandra values to support better downloads.

**Comment by nickdos** [comment]
Cassandra downloads have been inactive for years - setting as low priority

**Comment by adam-collins** [comment]
index/fields includes the correct and working downloadNames to use for with Cassandra downloads; institutionName.p, collectionName.p
