### ISSUE TITLE
QID issues for creating alerts from specieslists

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#26]
_From @djtfmartin on August 19, 2014 12:59_

_migrated from:_ https://code.google.com/p/ala/issues/detail?id=605
_date:_ Wed Mar 12 17:48:06 2014
_author:_ moyesyside

---

QID issues for creating alerts from specieslists

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#63_

**Comment by nickdos** [comment]
Can't make sense of this one. Looks like a biocahe-service issue, so moving there,

**Comment by adam-collins** [comment]
I wonder if this is about the 200 or so species limit for the qids created in specieslists when using 'view occurrence records'? Or maybe that the qid is not bound to list changes in specieslists?

What about pushing maxBooleanClauses up and adding another query field like lsid: that will lookup specieslists?

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
