### ISSUE TITLE
Inconsistent responses from /index/fields for both biocache-service-1.x and biocache-service-2.x

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#263]
I am trying to implement a systematic analysis of the fields that are exposed by ``/index/fields``, but it is producing inconsistent results for both biocache-service-1.x and biocache-service-2.x

The differences on the last two calls to ``/index/fields`` which were done within minutes of each other for ``https://biocache-lb.ala.org.au/ws/index/fields`` (biocache-service-1.x) after pretty-printing for readability, are:

```diff
--- a/ala-index-fields-debug/ALA-Production-Fields-Pretty.json
+++ b/ala-index-fields-debug/ALA-Production-Fields-Pretty.json
@@ -13,13 +13,6 @@
   "multivalue" : false,
   "downloadName" : "CurrentSeedQuantity"
 }, {
-  "name" : "Global",
-  "dataType" : "string",
-  "indexed" : false,
-  "stored" : false,
-  "multivalue" : false,
-  "downloadName" : "Global"
-}, {
   "name" : "OriginalSeedQuantity",
   "dataType" : "string",
   "indexed" : false,
@@ -190,6 +183,13 @@
   "multivalue" : false,
   "downloadName" : "attr.qa"
 }, {
+  "name" : "austConservation.p",
+  "dataType" : "string",
+  "indexed" : false,
+  "stored" : false,
+  "multivalue" : false,
+  "downloadName" : "austConservation.p"
+}, {
   "name" : "australianHerbariumRegion",
   "dataType" : "string",
   "indexed" : false,
@@ -1406,7 +1406,7 @@
   "indexed" : true,
   "stored" : true,
   "multivalue" : false,
-  "downloadName" : "countryConservation.p"
+  "description" : "Country conservation"
 }, {
   "name" : "county",
   "dataType" : "string",
@@ -6785,6 +6785,13 @@
   "downloadDescription" : "State - parsed",
   "classs" : "Location"
 }, {
+  "name" : "stateConservation.p",
+  "dataType" : "string",
+  "indexed" : false,
+  "stored" : false,
+  "multivalue" : false,
+  "downloadName" : "stateConservation.p"
+}, {
   "name" : "stateProvince",
   "dataType" : "string",
   "indexed" : false,
@@ -6800,7 +6807,7 @@
   "indexed" : true,
   "stored" : true,
   "multivalue" : false,
-  "downloadName" : "stateConservation.p"
+  "description" : "State conservation"
 }, {
   "name" : "subfamily",
   "dataType" : "string",
```

The differences for ``https://biocache-clustered.ala.org.au/ws/index/fields`` (biocache-service-2.x) again after pretty-printing for readability, are:

```diff
--- a/ala-index-fields-debug/ALA-Clustered-Fields-Pretty.json
+++ b/ala-index-fields-debug/ALA-Clustered-Fields-Pretty.json
@@ -7553,6 +7553,15 @@
   "downloadName" : "taxonomic_status",
   "classs" : "Taxon"
 }, {
+  "name" : "type",
+  "dataType" : "string",
+  "indexed" : true,
+  "stored" : true,
+  "multivalue" : false,
+  "dwcTerm" : "type",
+  "downloadName" : "type",
+  "classs" : "Record"
+}, {
   "name" : "type_status",
   "dataType" : "string",
   "indexed" : true,
@@ -7739,6 +7748,14 @@
   "info" : "The person or entity that verified this record.",
   "downloadName" : "verifier"
 }, {
+  "name" : "videos",
+  "dataType" : "string",
+  "indexed" : true,
+  "stored" : true,
+  "multivalue" : false,
+  "info" : "Videos associated with a record",
+  "downloadName" : "videos"
+}, {
   "name" : "water_body",
   "dataType" : "string",
   "indexed" : true,
```

**Comment by ansell** [comment]
Clearing all caches and restarting biocache-b4-a/b the first time didn't work. However, restarting biocache-b4-a/b a second time has them now showing the same values, so there is definitely an intermittent issue in biocache-service.

**Comment by ansell** [comment]
@nickdos @alexhuang091 This issue is still occurring based on rerunning my debug script just now.

**Comment by adam-collins** [comment]
biocache-service is using the `LukeRequestHandler`. This provides a node specific response and may not include all schema fields. Depending on which node that the request is routed to the response can vary.

`SearchDAOImpl.getIndexFieldDetails` needs to an alternative approach.
- `/solr/biocache/schema/fields` can be used to retrieve all schema fields for the biocache collection.
- `replication?command=indexversion` can be used to retrieve index version of specific shards. Because this is not useful, an alternative may be to monitor the total number of indexed documents and monitor for changes and increment.

**Comment by ansell** [comment]
@adam-collins Switching to an authoritative fields list would be useful. 

That diagnosis fits with what I observed in my debugging, where the fields that disappeared seemed to be those that are not very common and hence wouldn't necessarily be present in all shards in the collection. Most look like they come from the small number of ASBP records with a large number of unique fields.
