### ISSUE TITLE
Citizen Science Images do not have license information attached to them

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#28]
_From @mbohun on August 19, 2014 13:3_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=624
*date:* Mon Mar 31 22:15:03 2014
*author:* natasha....@csiro.au
 ---

The CS records do not have the license information attached to them.  This is because they are reporting the value in a non DWC field. 

I have modified the DataLoader to map this field to the correct DWC one.  This change has been performed in biocache-store 1.1.  In order for the fix to be applied to the data:

1) biocache-service 1.1 needs to be deployed on macropus
2) all the citzen science records need to be reloaded onto the jms queue

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#67_

**Comment by nickdos** [comment]
This is probably fixed but I can't test it (not enough info provided)... Moving to biocache-service.

**Comment by djtfmartin** [comment]
closing. I believe this is fixed but if not should be raised against ecodata/images.
