### ISSUE TITLE
Faceting is inconsistent and the process of identifying candidate contextual layers unknown

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#30]
_From @Tasilee on August 19, 2014 13:4_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=634
*date:* Wed Apr  9 23:58:26 2014
*author:* leebel...@gmail.com
 ---

1. The ORDERING of geospatial facets appears random (=dog's breakfast):
Uncertainty (in metres)
Sensitive
State conservation
State conservation (unprocessed)
IMCRA (meso-scale)
Local Gov. Area
State/Territory
Country
Biogeographic region
IBRA
IMCRA
Dynamic land cover
Vegetation types - native
Vegetation types - present
Spatial validity

2. NAMING of facets is inconsistent, e.g., the IBRA layers in the SP are named (Add to Map | Layers)-

IBRA 6 Regions
IBRA 6 Sub Regions
IBRA 7 Regions
IBRA 7 Subregions

but in the facets, you have

IBRA

So which IBRA is it? You could find out by mapping all the IBRA layers and checking alignment of points, but this is obtuse.

3. If the IBRA noted above is actually IBRA 6 Regions or Sub Regions, why is it still there when IBRA 7 supersedes it? Therefore, what is the process for deprecating facets? What is the process of identifying and 'loading' a new facet from a new contextual layer?

4. Ideally, a user should be able to facet on non-trivial (e.g., not single polygons of small extent, e.g., GER polygons) CONTEXTUAL non-trivial  layers as this is a powerful filtering mechanism.

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#69_

**Comment by nickdos** [comment]
_From @Tasilee on October 20, 2014 3:25_

I have reviewed all the potential 'facets' (which are also candidates for tabulation) with a focus on those derived from contextual layers (ALA_Spatial_layers.xlsx) and suggest a list organized as in Facets.xlsx. Basically, any contextual layer that generates a legend is a facet candidate. Some layers that are comprised of unique polygons may also be candidates, particularly if they have national coverage and could be ecologically useful for filtering.

**Comment by nickdos** [comment]
_From @Tasilee on November 13, 2014 0:29_

..This issue also relates to the record download fields (which should match the facet fields), which are also current ad hoc

**Comment by nickdos** [comment]
_From @Tasilee on November 13, 2014 1:30_

Related but possibly worth one or more separate issues: 

I am assuming that field "description: "Presence/Absence", name: "occurrence_status_s" maps to download "assumed Present Occurrence Status" (which is a wild guess given the name difference)? This is a good example where names of fields need standardization and where concise definitions are needed.

If the above fields were a match, then there is a problem if someone inadvertently downloads ONLY absence records.

**Comment by nickdos** [comment]
_From @Tasilee on December 10, 2014 3:33_

Relevant files - 

https://www.dropbox.com/s/n5150p20kvks1xy/Facet_GEOSPATIALs.xlsx?dl=0
https://www.dropbox.com/s/hoe844b603jqxj9/ALA_Spatial_Layers_CONTEXTUAL%20CLASSIFICATION.xlsx?dl=0

**Comment by nickdos** [comment]
Facets are determined by the grouped_facets.json config file now. So just need to update this file to make the order of the "Location" group more logical.

The labels are determined by i18n entries - `facets.facetName`, etc. Fix labels there.

**Comment by adam-collins** [comment]
Location facets are updated in ala-install https://github.com/AtlasOfLivingAustralia/ala-install/commit/05a4332573acab4c424d8deb055a8d6813f76723
