### ISSUE TITLE
Regression: A large number of Darwin Core Terms are missing in downloads

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#308]
There are many Darwin Core Terms missing in downloads when users choose "Darwin Core Terms". All Darwin Core Terms must be supported if we are to claim compliance with this TDWG specification. There is a machine readable version of Darwin Core Terms at ``https://github.com/tdwg/dwc/blob/master/dist/simple_dwc_vertical.csv`` which can be used in bulk to ensure that we are supporting all of Darwin Core Terms.

Listing each of the terms which we currently have issues with has been deemed to not be helpful so those issues have been abandoned.

**Comment by nickdos** [comment]
This needs reviewing - a quick look just now suggests most are being indexed and provided in the DwC download but [this issue ](https://github.com/AtlasOfLivingAustralia/biocache-store/issues/391)suggests it is still not complete.

**Comment by adam-collins** [comment]
There should be an automatic mapping of field names to DwC terms for the `messages.properties`(`/facets/i18n`) `dwc.*` and `class.*` entries. Note that these are visible in `/index/fields` `dwcTerm` and `classs` (DwC class)

**Comment by adam-collins** [comment]
Use the most recent `org.gbif:dwc-api`

Pull request https://github.com/AtlasOfLivingAustralia/biocache-service/pull/864

**Comment by peggynewman** [comment]
checked downloads, all looks good
