### ISSUE TITLE
qid searches - include fq in displayString

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#312]
When a QID search is shown in the biocache UI, the interface only knows about the `query` (e.g. `?q=qid%3A1534223432772`) and the `queryTitle` (e.g. `<span class='lsid' id='urn:lsid:biodiversity.org.au:afd.taxon:c3176e73-885c-48bc-a9e6-b43c1c912a23'>GENUS: Pogona</span>`) which only reflects the `q` param and ignores any `fq` or other params. 

However the QID could also include a number of `fq` and other params that might affect the results. These are effectively lost to the UI and the user is left wondering why the map/result set is smaller than what the `queryTitle` suggests should be there.

FIX: amend the `queryTitle` with information about the `fq`s and any spatial filters.

E.g.

`<span class='lsid' id='urn:lsid:biodiversity.org.au:afd.taxon:c3176e73-885c-48bc-a9e6-b43c1c912a23'>GENUS: Pogona</span> with filters: state: New South Wales, record type: Image`

**Comment by adam-collins** [comment]
A more current example https://biocache.ala.org.au/ws/occurrences/search?q=qid:1701233918857

The result should contain `activeFacetMap` entries for the fq terms in the `qid` https://biocache.ala.org.au/ws/qid/1701233918857
