### ISSUE TITLE
taxon_concept_lsid values missing in 'index' download

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#313]
E.g. http://biocache.ala.org.au/ws/occurrences/index/download?qa=zeroCoordinates,badlyFormedBasisOfRecord,detectedOutlier,decimalLatLongCalculationFromEastingNorthingFailed,missingBasisOfRecord,decimalLatLongCalculationFromVerbatimFailed,coordinatesCentreOfCountry,geospatialIssue,coordinatesOutOfRange,speciesOutsideExpertRange,userVerified,processingError,decimalLatLongConverionFailed,coordinatesCentreOfStateProvince,habitatMismatch&q=genus:Macropus&fq=multimedia%3A"Image"&fields=decimalLongitude.p,decimalLatitude.p,coordinateUncertaintyInMeters.p,eventDate.p,year.p,month.p,species_guid,species.p,taxon_concept_lsid,taxon_name,rank&email=nickdos@gmail.com&reasonTypeId=4&sourceTypeId=2002

Although the field `taxon_concept_lsid` is present in the data file, very few rows have a value included. See attached zip file. Note the species_guid has lost of values, so missing data looks like a bug.

[data (22).zip](https://github.com/AtlasOfLivingAustralia/biocache-service/files/2295542/data.22.zip)

**Comment by djtfmartin** [comment]
Yes, confirmed. This is an indexing bug. Only 32k records with this value in the index.

https://biocache.ala.org.au/ws/occurrences/search?q=taxon_concept_lsid:*&pageSize=0

@adam-collins any thoughts on this ?

**Comment by djtfmartin** [comment]
fixed in this commit

https://github.com/AtlasOfLivingAustralia/biocache-store/commit/a0cef9ac0c4f1c66fab7e8be090003b7050072c2

**Comment by djtfmartin** [comment]
this is now fixed after a bug fix and re-index.
