### ISSUE TITLE
Add better support for WMS "REQUEST=GetLegendGraphic"

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#315]
E.g. AODN guys were requesting

http://biocache-lb.ala.org.au/ws/ogc/wms/reflect?fq=species_habitats:%22Marine%22&LEGEND_OPTIONS=forceLabels:on&REQUEST=GetLegendGraphic&LAYER=ALA%3Aoccurrences&FORMAT=image/png&VERSION=1.1.1

which just shows a coloured dot. I think it should also show the text description,  .e.g. as shown here http://docs.geoserver.org/stable/en/user/services/wms/get_legend_graphic/index.html

**Comment by nickdos** [comment]
Maybe we can pull in code for the legend WS?

http://biocache.ala.org.au/ws/mapping/legend

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
