### ISSUE TITLE
Facet values are not escaped.

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#316]
Refer to search below.

**Steps to reproduce**

1. Issue   [this search](https://biocache.ala.org.au/occurrences/search?q=*%3A*&wkt=MULTIPOLYGON%28%28%28146.53564453125+-43.00464712779443%2C146.53564453125+-43.96119063892024%2C148.11767578125+-43.96119063892024%2C148.11767578125+-43.00464712779443%2C146.53564453125+-43.00464712779443%29%29%29#tab_mapView
)
2. Select "Amygdalum lineum" (4) as per screenshot 
<img width="1025" alt="screen shot 2018-08-30 at 4 58 14 pm" src="https://user-images.githubusercontent.com/8326394/44848607-c4b5f400-ac9a-11e8-8bc9-60f2d2386cc8.png">

**Expected:**
Search results with 4 records

**Actual**
_No records found for *:*_ message is displayed

**Further Info**
The facets values returned by biocache-service are not encoded using Solr/Lucene org.apache.solr.client.solrj.util.ClientUtils.escapeQueryChars() [in getFormattedFqQuery()](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/85671b9b54cd2677bda9859c54358ddb2cda281b/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L4072)  which results in the facet/filter not finding any records.

However in applying the fix above will require at least to fix [formatSearchQuery](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/7ff68304a4abe712761c7b890a119860dd756820/src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java#L119) and its dependencies as the parsing routines don't expect quote characters (") to be present inside the already quoted facet value. 

The analysis is not exhaustive, other parts of biocache-service and/or downstream systems might require changes too.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
