### ISSUE TITLE
Downloads - custom format missing raw fields

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#318]
Reported by Bob M:

> Hi, Nick.
>
>I did a small ALA download tonight* and noticed that the raw ("as supplied") fields are no longer included in the custom download field sets. Are these no longer available, either to providers or users? Is there another way to get them?
>
>*https://doi.org/10.26197/5b8cf0e81ec8a
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr345
>
>Regards,
>Bob

**Comment by nickdos** [comment]
Quite a few raw fields are there so I've asked Bob for more details.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
