### ISSUE TITLE
Request for record using occurrenceID work for some services but not others

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#321]
E.g. requesting a record via its `occurrenceID` (and not the `rowKey`) works for the record path:

https://biocache-ws.ala.org.au/ws/occurrences/ee230ee8-5877-4d4a-ac71-07dbab80617d (occurrenceID)
https://biocache.ala.org.au/ws/occurrences/ee230ee8-5877-4d4a-ac71-07dbab80617d (rowKey)

but the related call for assertions fail:

https://biocache-ws.ala.org.au/ws/occurrences/ee230ee8-5877-4d4a-ac71-07dbab80617d/assertions (occurrenceID)

this works:

https://biocache.ala.org.au/ws/occurrences/ee230ee8-5877-4d4a-ac71-07dbab80617d/assertions (rowKey)

Whereas using the `rowKey` (ceffbe27-2bf5-4496-8e1c-292643dd1388) gives the same record for both calls.

This inconsistency results in UI pages throwing an error:

https://biocache.ala.org.au/occurrences/ee230ee8-5877-4d4a-ac71-07dbab80617d

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
