### ISSUE TITLE
Downloads: provide instructions on how to cite DOIs in publications

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#327]
As suggested by Nicole K: https://support.ehelp.edu.au/helpdesk/tickets/23322

Both the email notification and the README file need some updated text with clearer instructions on how to cite the DOI when publishing any material pertaining to the download. See the text on https://www.ala.org.au/how-to-cite-ala/ for ideas or ask @M-Nicholls or @nickdos for more details.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
