### ISSUE TITLE
Very long response time for WMSController.generateWmsTile when no arguments are provided

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#328]
The first query to ``WMSController.generateWmsTile`` with no arguments provided takes a long time, and generates a tile with a single dot in the top left hand corner. This query showed up as a very long outlier in the biocache-service log files, at about 40 seconds.

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/f68560bb024df8a4b366387505b5f8b1430c3dca/src/main/java/au/org/ala/biocache/web/WMSController.java#L1432

After the first call, ever other call to the same instance may/will be cached by nginx and/or the internal WMS cache, but this is replicable on a fresh server startup for me.

The test URL I used (which is currently cached), is ``https://biocache-ws-test.ala.org.au/ws/ogc/wms/reflect``

**Comment by djtfmartin** [comment]
ive changed this so that no args returns a 400 with an XML response
