### ISSUE TITLE
Possible fixes to the biocache offline download services

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#329]
The current behaviour for supporting offline downloads is to submit the entire set of ``Callable``'s to the shared ``ExecutorService`` at the same time. As each ``Callable`` is given the same priority, and execution is fairly done based on the ordering of ``Callable``'s arriving, those from smaller downloads wait until after the large downloads complete. 

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/85671b9b54cd2677bda9859c54358ddb2cda281b/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L1323

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/85671b9b54cd2677bda9859c54358ddb2cda281b/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L1380-L1383

This breaks the conceptual model where smaller downloads are theoretically being supported in parallel with large downloads, as the larger downloads in practice will need to complete before the ``Callable``s created for smaller downloads will be put through the ``biocache-query-offline`` executor

There are multiple ways to fix this, including:

* fixing the memory usage where every ``Callable`` for a large download is precreated and stored in memory until it is needed, 
* switching everything to use a pull based system that fairly orders queries for every download by polling the running downloads to get their next queries rather than pushing the ``Callable``s into the executor service in a large batch when the download is first executed, 
* switching to a single thread for large downloads and a single thread for small downloads and adding a ``PriorityBlockingQueue`` to ensure that the smaller downloads are promoted to the front of the queue and supercede large downloads
* keeping multiple threads in multiple categories, but adding a ``PriorityBlockingQueue`` and randomising the priority of ``Callable``s using some unfair distribution so that large downloads still eventually complete and are executed in parallel with small downloads
* create a separate ``biocache-query-offline`` ``ExecutorService`` for each offline download pool thread (the ALA has limited budget for the solr cloud instances, so supporting this would make large downloads much slower as they couldn't use spare capacity when small downloads are being executed concurrently)

**Comment by ansell** [comment]
Note the workaround above still runs into blocking issues when the consumer is slower than the producer threads, as it is for our current (ancient) GeoTools shapefile writer. In some cases excessive latency from the consumer thread can also affect the latency sensitive zookeeper connection and maintenance calls.

**Comment by ansell** [comment]
The workaround above is also limited in the ALA case by the requirement to limit the number of concurrent Solr Cloud connections to less than the 30 download threads. Those of the 30 producer threads that are able to connect to solr are blocking other threads from accessing solr based on the maximum connection count, (which destroys the solr cloud if we set it anywhere near 30).

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
