### ISSUE TITLE
WMS outline param has wrong default value

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#331]
Reported by a user - https://support.ehelp.edu.au/a/tickets/23658

The API docs do not mention the `outline` param (~~TODO fix!~~) but the `/ws/mapping/wms/image` API docs do include it and it states the default value is `false`. Testing the WMS service I can see the default value is currently true:

https://biocache-ws.ala.org.au/ws/mapping/wms/reflect?q=lsid%3Ahttp%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F2895888&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=ALA%3Aoccurrences&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&BGCOLOR=0x000000&ENV=color%3Adf4a21%3Bname%3Acircle%3Bsize%3A4%3Bopacity%3A0.8&GRIDDETAIL=32&STYLE=opacity%3A0.8&SRS=EPSG%3A3857&BBOX=17063190.698156465,-3287403.7124888604,17102326.456638474,-3248267.9540068493

returns the same image as

https://biocache-ws.ala.org.au/ws/mapping/wms/reflect?q=lsid%3Ahttp%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F2895888&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=ALA%3Aoccurrences&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&BGCOLOR=0x000000&OUTLINE=true&ENV=color%3Adf4a21%3Bname%3Acircle%3Bsize%3A4%3Bopacity%3A0.8&GRIDDETAIL=32&STYLE=opacity%3A0.8&SRS=EPSG%3A3857&BBOX=17063190.698156465,-3287403.7124888604,17102326.456638474,-3248267.9540068493

**Comment by nickdos** [comment]
Fixed API docs (https://api.ala.org.au).

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
