### ISSUE TITLE
Regression: occCount attribute not included in all autocomplete results

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#333]
I have a user from AODN who has requested that we look into why the ``occCount`` attribute is no longer included on all autocomplete results since the switch to biocache-service-2.

A sample URL that shows ``occCount`` being present on three results out of ten when I resolve it is:

``https://biocache.ala.org.au/ws/autocomplete/search?q=shark&pageSize=10&fq=species_habitats%3A%22Marine%22``

If the ``occCount`` is zero, it would be useful to show it in the result as ``0`` rather than having users investigating whether it was non-zero using a separate query.

Refs ticket 23737 in helpdesk

**Comment by djtfmartin** [comment]
I've changed the counts lookup to be synchronous. If this proves too much of  a performance problem it can be switched off in configuration.

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/service/SpeciesCountsService.java#L46

**Comment by ansell** [comment]
Waiting on verification from AODN that this is working for their queries

**Comment by ansell** [comment]
No contact from AODN since the fix, closing
