### ISSUE TITLE
Regression: fq parameter does not have an effect on autocomplete query

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#334]
The ``fq`` parameter in this autocomplete query does not seem to have an effect on the results:

```
https://biocache.ala.org.au/ws/autocomplete/search?q=blue+grass&pageSize=1000&fq=species_habitats%3A%22Marine%22
```

Refs ticket 23792 in helpdesk

**Comment by ansell** [comment]
Verified that the ``fq`` parameter does have an effect on biocache-service-1, so this is a regression

**Comment by djtfmartin** [comment]
This is now fixed

**Comment by ansell** [comment]
Waiting on verification from AODN that this is working for their queries

**Comment by ansell** [comment]
No contact from AODN since the fix, closing
