### ISSUE TITLE
Shapefile downloads may not be compatible with ArcGis/ArcMap

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#338]
User reporting lack of values in some fields after opening shapefile using ArcGIS products.

Refs ticket 24270 in helpdesk

**Comment by ansell** [comment]
Could not verify the issue with GeoTools. No errors loading or exporting with GeoTools. Have offered an imported and reexported version from the current GeoTools (much more recent than the one biocache-service is using) to the user. Moving this to backlog again as it doesn't look different to the other cases where ArcGIS users have been unable to load shapefiles but can't completely explain why due to the cryptic or non-existent error messages. These users should be contacting ESRI with their support contracts before contacting us, to get the ESRI support team who understand (and have access to) their proprietary software looking at each case first.

**Comment by djtfmartin** [comment]
Shapefile downloads have been deprecated.
