### ISSUE TITLE
Darwin Core export: four pseudo-duplicated fields

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#341]
_From @Mesibov on August 6, 2017 2:10_

basisOfRecord, class, dcterms:bibliographicCitation and specificEpithet each appear twice among the 187 fields in a Darwin Core TSV export. These are pseudo-duplicates, because in the two ca 500000-records sets I downloaded on 3 August 2017, the two "class", "dcterms:bibliographicCitation" and "specificEpithet" fields had very different content, i.e., wrong values in one of the pseudo-replicates.

_Copied from original issue: AtlasOfLivingAustralia/ala-downloads#17_

**Comment by nickdos** [comment]
Hi Bob, I think the duplicates were probably raw and processed versions of the field. So the field names in the first line of the TSV/CSV file needs to disambiguate these fields. The `headings.csv` provides more details (order is preserved so duplicate entries could be differentiated) on the field names, so this would've shed light on them but I think the "heading" row in the data file should be clearer.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
