### ISSUE TITLE
Make email address a mandatory parameter for /ws/occurrences/index/download

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#343]
It is easy to flood solr with queries using /ws/occurrences/index/download. It would be ideal if there was a mandatory email address for this service so legitimate users of the service can be contacted instead of getting themselves blocked without any way to contact them before hand.

Ideally in the long term, there would be apikeys required after a small number of requests to this service during a period of time, but the next best option would be to require users to submit email addresses with requests.

**Comment by ansell** [comment]
The tracking issue for apikeys is https://github.com/AtlasOfLivingAustralia/biocache-service/issues/326

**Comment by brucehyslop** [comment]
Adding a mandatory email address would effect any service that rely on the endpoint. Do we have a list of clients that rely on `/ws/occurrences/index/download`?

I think the second suggestion of rate limited access when no apiKey has been provided would be a better solution that wouldn't effect existing clients. 
Would 5 requests (keyed by IP address) within 5 minutes with 1 request per minute after that be sufficient?

**Comment by ansell** [comment]
If it can be implemented configurably, and we switch it on in biocache-ws-test for as long as necessary for clients to test and make the necessary changes we could smooth the process out.

In terms of identifying clients, we have limited descriptions about them in User-Agents (ALA4R), or by identifying our servers by IP address (Spatial Portal for example) , or identifying their institutions based on their IP address. We will need some point at which to switch it on in production though, as this is a chicken-egg issue because we would need their email address to conclusively identify them to communicate that they need an email address.

The two biggest users of online downloads from monitoring in the past are ALA4R and Spatial Portal, both of which we control the code for so we can make the changes proactively.

Having said that, adding custom nginx rate limits is possible if we want to go that way, at least initially.

**Comment by brucehyslop** [comment]
I propose that we could either deny access or rate limit requests if either:
- the request does not contain an apiKey param
- the request does not contain an email param
- the request IP address is not within a list of allowed network addresses

To disable the checking that the request contains an email the allowed network address could be set to 0.0.0.0/0. 

Once clients implement passing of email then remove the allowed networks or reduce the list to the network addresses of clients that have not or are unable to pass email in the request.

**Comment by brucehyslop** [comment]
added logic to the `AbstractSecureController.rateLimitRequest()` to allow rate limiting of requests. 
This can be configured with the following values:
 - `ratelimit.network.exclude`: list of network addresses to be excluded from rate limiting.
 - `ratelimit.network.include`: list of network address to be included in rate limiting (the included networks override any excluded network ranges).
 -  `ratelimit.window.seconds`: rate limiting window (default 360s, 5 minutes).
 - `ratelimit.count`: rate limit count (default 5), the number of requests that can be performed within the rate limit window. 

If the `ratelimit.window.seconds` or `ratelimit.count` are zero (0) than any request that does not match the network exclude / include rules will be instantly blocked.
Rate limiting is only applied to the `/occurrences/index/download` request if either the apiKey or email parameter is not defined.

**Comment by Rita-C** [comment]
@brucehyslop @ansell, 

- `https://biocache-test.ala.org.au/ws/occurrences/index/download?reasonTypeId=10&q=Wollemia+nobilis&email` allows access - should email value being validated?

- `https://biocache-test.ala.org.au/ws/occurrences/index/download?reasonTypeId=10&q=Wollemia+nobilis&EMAIL` returned 403 after 5 attempts without email address - case sensitive?

**Comment by brucehyslop** [comment]
some level of email validation would be a good idea. Basic validation to check the email matches a regex would be an improvement. 

It would be best to check that email against an ALA account, not sure if this is practical

**Comment by nickdos** [comment]
@ansell suggests that checking the email address against AUTH is preferable as we have had issues where emails bounce. When DOIs are requested, the email address is already checked against AUTH (most downloads) so moving the check to the beginning of the response chain would be an improvement. Code to check against AUTH is already present, so should be a case of calling existing service.

This can wait for a subsequent release, so create a new issue if not included in the next release.

**Comment by ansell** [comment]
@nickdos The auth verification issue was created this morning: #479

**Comment by nickdos** [comment]
Tested with missing `email` param and empty value - both returned 400 with message `Required parameter 'email' is not present`.
