### ISSUE TITLE
WMS requests with `SRS=EPSG:900913` are failing

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#348]
[Reported by Taryn](https://support.ehelp.edu.au/a/tickets/26051):

Regions pages are not showing occurrence dots on the map - it is displaying the broken image icon. The tile URLs look like:

https://biocache.ala.org.au/ws/mapping/wms/reflect?REQUEST=GetMap&SERVICE=WMS&VERSION=1.1.1&BGCOLOR=0xFFFFFF&TRANSPARENT=TRUE&SRS=EPSG:900913&WIDTH=256&HEIGHT=256&q=cl22%3A%22Australian+Capital+Territory%22&FORMAT=image/png&LAYERS=ALA%3Aoccurrences&STYLES=&BGCOLOR=0xFFFFFF&CQL_FILTER=&symsize=3&ENV=color:FF0000;name:circle;size:3;opacity:0.7&EXCEPTIONS=application-vnd.ogc.se_inimage&&&fq=rank:(species%20OR%20subspecies)&&fq=-occurrence_status_s:absent&&fq=geospatial_kosher:true&&fq=occurrence_year:*&pageSize=50&fq=occurrence_year:[1850-01-01T00:00:00Z%20TO%202018-12-31T23:59:59Z]&BBOX=16593561.596372342,-4383204.9499851465,16750104.630300382,-4226661.916057104&zoom=8

which gives an error:

```
{
  "message": "No code "EPSG:900913" from authority "European Petroleum Survey Group" found for object of type "CoordinateReferenceSystem".", 
  "errorType": "Server error"
}
```

Changing the `SRS` param to `EPSG:3857` results in a working tile, e.g.

https://biocache.ala.org.au/ws/mapping/wms/reflect?REQUEST=GetMap&SRS=EPSG%3A3857&SERVICE=WMS&VERSION=1.1.1&BGCOLOR=0xFFFFFF&TRANSPARENT=TRUE&WIDTH=256&HEIGHT=256&q=cl22%3A%22Australian+Capital+Territory%22&FORMAT=image/png&LAYERS=ALA%3Aoccurrences&STYLES=&BGCOLOR=0xFFFFFF&CQL_FILTER=&symsize=3&ENV=color:FF0000;name:circle;size:3;opacity:0.7&EXCEPTIONS=application-vnd.ogc.se_inimage&&&fq=rank:(species%20OR%20subspecies)&&fq=-occurrence_status_s:absent&&fq=geospatial_kosher:true&&fq=occurrence_year:*&pageSize=50&fq=occurrence_year:[1850-01-01T00:00:00Z%20TO%202018-12-31T23:59:59Z]&BBOX=16593561.596372342,-4383204.9499851465,16750104.630300382,-4226661.916057104&zoom=8

**Comment by nickdos** [comment]
@adam-collins do you have time to look at this or should I assign it to @djtfmartin?

**Comment by nickdos** [comment]
This is less critical now as I changed `regions` to use `EPSG:3857`.

**Comment by adam-collins** [comment]
Fix for this on docvalues branch.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
