### ISSUE TITLE
biocollect UUIDs searchable in the Biocache

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-service#349]
biocollect UUIDS are different to Biocache UUIDS - when viewing a record the biocollect UUID doesn't work to view the record but it does work to view the JSON:

biocache-service is trying to be smart and return JSON for the UUID for the provided identifier (UUID from Ecodata) but the webpage fails as it can't find any assertions for that UUID - it needs the native biocache-service generated UUID which is used to store the assertions against
can see from the error:
`Failed to get json from web service (https://biocache-ws.ala.org.au/ws/occurrences/bc33eefa-2635-4321-8657-1fb283ecf4cb/assertions)`
assertions on end of URL

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
