### ISSUE TITLE
Distance outside expert range should be expressed in KM

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#35]
_From @Tasilee on August 20, 2014 3:32_

_migrated from:_ https://code.google.com/p/ala/issues/detail?id=616
_date:_ Thu Mar 20 16:52:14 2014
_author:_ leebel...@gmail.com

---

At the moment, the record details don't state what the UNIT is when reporting "Distance outside expert range". It appears to be metres? I'd suggest km.

![capture 2](https://cloud.githubusercontent.com/assets/1772897/3976196/226ae014-281b-11e4-8117-7932e407eb24.jpg)

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#87_

**Comment by nickdos** [comment]
_From @djtfmartin on August 20, 2014 3:32_


*date:* Mon Aug 18 21:16:33 2014
*author:* moyesyside
 ---

*(No comment was entered for this change.)*

 ---
**UPDATES:**
*Labels:* -Component-UI Biocache

**Comment by adam-collins** [comment]
Will need to re-run distribution-outliers across all occurrences after deploy.

https://github.com/AtlasOfLivingAustralia/biocache-store/commit/47fff9d081f5ffa5770d2277aa4491b80e706b0f

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
