### ISSUE TITLE
search result ws shows eventDate as unix time

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-service#353]
In search result:
https://biocache.ala.org.au/ws/occurrences/search?q=species_habitats:Marine&facet=no&fq=data_resource_uid:dr5018&pageSize=20

eventDate (and eventYear) is a number  e.g.  1197417600000 as unix time from 1-Jan-1970 in seconds - why is this not ISO formatted date string? like the individual record view ws

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
