### ISSUE TITLE
biocache taxonomic filters - add lichens

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-service#356]
reported via helpdesk: https://support.ehelp.edu.au/a/tickets/28690

when creating a field guide. One comment is it is frustrating not being able to filter out the lichens (except ideally the basidiolichens).
__________________________________________
Your download is available on the URL:

https://fieldguide.ala.org.au/download/offline/24012019-fieldguide1548307646764.pdf

When using this field guide please use the following citation:

Atlas of Living Australia field guide generated from https://biocache.ala.org.au/occurrences/search?file=records-2019-01-24&reasonTypeId=11&dwcHeaders=true&fileType=csv&qa=none&sourceTypeId=0&email=fungimapconservation%40gmail.com&q=cl2120%3A%22West+Gippsland%22&fq=species_subgroup%3A%28%22Asco%5Cu0027s%22+OR+%22Basidio%5Cu0027s%22%29&fq=occurrence_year%3A%5B*+TO+2019-12-31T23%3A59%3A59Z%5D&fq=rank%3A%28species+OR+subspecies%29&fq=-occurrence_status_s%3Aabsent&fq=geospatial_kosher%3Atrue&fq=occurrence_year%3A*&&pageSize=0&&facet=true& accessed on Thu Jan 24 16:30:09 AEDT 2019.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
