### ISSUE TITLE
AVH map downloads showing all ALA records

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#357]
Support ticket: https://support.ehelp.edu.au/a/tickets/28687

https://avh.ala.org.au/occurrences/search?q=collector_text%3A%22Campbell%2C+T.G.%22#tab_mapView

click map tab and then "download map". Resulting map show many more records and is the same map as: https://biocache.ala.org.au/occurrences/search?q=collector_text:%22Campbell,%20T.G.%22&fq=#tab_mapView

Map request is: https://biocache-ws.ala.org.au/ws/webportal/wms/image?q=collector_text%3A%22Campbell%2C%20T.G.%22&qc=data_hub_uid%3Adh9&extents=125.9912109375,-38.856820134743614,168.837890625,-15.665354182093274&format=jpg&dpi=300&pradiusmm=0.5&popacity=0.7&pcolour=FB5548&widthmm=150&scale=on&outline=true&outlineColour=0x000000&baselayer=world&baseMap=&fileName=support%20check.jpg

and it appears the `qc=data_hub_uid%3Adh9` param is being ignored or is the wrong format for the download service.

**Comment by adam-collins** [comment]
Fix on docvalues branch.

**Comment by ansell** [comment]
May also be the cause of ticket 32853 in helpdesk where the user reported the following URL returning all occurrences in the extents:

```
https://biocache-ws.ala.org.au/ws/mapping/wms/image?baselayer=world&extents=166.2,-48,178.8,-33.5&outline=true&fileName=MyMap.jpg&pcolour=3531FF&pradiusmm=1&format=jpg&q=genus:Carpophyma&fq=species:Carpophyma+mutabilis&fq=data_resource_uid:dr2153&popacity=0.8&dpi=100&outlineColour=#000000&scale=off
```

**Comment by adam-collins** [comment]
This is now working in prod.
