### ISSUE TITLE
Typo at "Original versus Processed" Comparison Table

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#36]
_From @sadeghim on December 4, 2014 0:6_

On the "Original versus Processed" Comparison Table in occurrence view, Class is misspelled as  _Classs_ .

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#110_

**Comment by nickdos** [comment]
"classs" value is coming from biocache-service:

http://biocache.ala.org.au/ws/occurrence/compare?uuid=10ff70a3-7088-44c6-9cea-95ccd9299ba5

Might be a reserved word workaround (usually as clazz)? Moving to biocache-service.

**Comment by nickdos** [comment]
needs i18n treatment?

**Comment by adam-collins** [comment]
Other fields in Comparison need the same treatment. Most of these Cassandra fields are appear missing from i18n, or they appear with .p

**Comment by adam-collins** [comment]
Use of i18n in comparison table added to biocache-hub https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/861a0d02e73a7999d50814a50d9d0a7010e66655
