### ISSUE TITLE
Investigate whether download.max is consistently used

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#360]
There are a large number of online/index downloads that fill up the limited resources available on the dedicated download instance of biocache-service. There is a configuration value that nominally should help with restricting cases where very large downloads are being performed using the time-sensitive online downloads instead of the more appropriate offline downloads. 

However, it isn't clear whether the default max download parameter, `download.max` is being enforced in these cases, as it isn't currently overridden in the `ala-install` `biocache-config.properties` template or whether it always practically overridden and ignored by the boolean `limit` parameter that controls access to it on a number of methods:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L121-L122

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L1994

It also isn't clear what the limit is going to be from looking at the code in some cases, given that the default for "unzipped limit" is very small but is potentially overridden or ignored:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L188-L189

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
