### ISSUE TITLE
taxa search field parsing error

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-service#361]
When using q=taxa:a OR taxa:b it is incorrectly parsed as parsedTermA ORparsedTermB. i.e. there is a missing space after the OR term.

- [ ] add unit tests for `formatTaxa(String [] current)` method

**Comment by adam-collins** [comment]
Fixed on docvalues branch.

**Comment by nickdos** [comment]
Adde comment to code (see https://github.com/AtlasOfLivingAustralia/biocache-service/commit/af1215d4d894476a4e7c37fdf535c0843fa7ca8f). I think this needs unit tests added - adding to issue body.
