### ISSUE TITLE
occurrences/batchSearch is not correctly documented/does not accept DownloadRequestParams

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-service#362]
occurrences/batchSearch does not accept DownloadRequestParams, e.g. qc

The service documentation will be updated and it will be changed to support DownloadRequestParams.

Query parsing in biocache-service will be changed to detect and attempt to correct the 'too many boolean terms' error.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
