### ISSUE TITLE
VirtualWebappLoader removed in Tomcat-8

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#363]
The `VirtualWebappLoader` function relied on by the `META-INF/context.xml` definitions was removed in Tomcat-8

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/webapp/META-INF/context.xml#L8

http://tomcat.apache.org/migration-8.html#Web_application_resources

To support `biocache-service` under Tomcat-8, it would need to be rewritten to use the new scheme.

**Comment by brucehyslop** [comment]
Add of resources has been replaced with a single framework see [https://stackoverflow.com/a/23152546](https://stackoverflow.com/a/23152546) for resolution

**Comment by brucehyslop** [comment]
I've created a branch for the update to [origin/tomcat-8.5+9-update](https://github.com/AtlasOfLivingAustralia/biocache-service/tree/tomcat-8.5%2B9-update)

**Comment by ansell** [comment]
This is working on `aws-biocache-service-test-1`, so moving to CAB column on the project board.
