### ISSUE TITLE
Explore your area performance enhancements

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#365]
It could be useful to analyse the performance and cacheability of the Explore Your Area queries.

The current requests on a new `/explore/your-area` page appear to be:

* Users exact location to a fairly high precision is used as the centre point of a circle
* By default a 5km radius is used from the high precision centre point to perform queries
* By default every record "All species" is used as the search which is performed automatically
* *Two identical calls other than callback parameters* are made to GeoJSON service. Result, wrapped in JSONP form, is returned from `/ws/geojson/radius-points.jsonp?callback=.......` to the users browser. In my case, this was 580.98KB of text, which was compressed by NGINX to 25.07KB across the wire
* Grouped species counts, wrapped in JSONP form, are returned from `/ws/explore/groups.json?callback=.......` for all species in the set of groups that are shown to the user
* All of the counts for all species are requested automatically to populate the default view using a JSONP (incorrectly labelled with `Content-type: application/json;charset=UTF-8`) call to `/ws/explore/group/ALL_SPECIES.json?callback=....`

None of the calls above are cached as they either contain highly specific coordinates which will not match solr query caches if the user moves at all or unique `callback` parameters to support JSONP.

A breakdown of the biocache-ws.ala.org.au calls made are:

![screen shot 2019-02-14 at 11 56 39 am](https://user-images.githubusercontent.com/82365/52754707-a75dc200-304f-11e9-8644-d7c542fa90fb.png)

Some ideas for possible improvements are:

- [x] Remove all use of JSONP and replace with CORS+JSON
- [x] Force cache the relevant CORS+JSON paths in nginx
- [ ] Add `ETag`/`Last-Modified` to the biocache-service responses so browsers can know to cache them internally
- [x] Only request `radius-points.jsonp` once
- [ ] ~~Do not expand the All species group automatically~~
- [ ] Do not populate the very specific species counts table automatically, only after user selects an entry on the group heirarchy
- [ ] Default to only animals and/or plants
- [ ] Eliminate the unplaced APNI entries under Plantae from the "Plants" queries if they are an issue and removing them is practical
- [x] Desensitise the location sent to biocache-service to a fixed set of grid points (50/100 metre resolution?) which could improve cacheability of successive calls by the same user by reducing the entropy in the lat/long coordinates
- [x] Render WMS tiles on the server rather than requesting GeoJSON. Reduces the JSON parsing overhead on the client, which is potentially a issue for battery devices.

CC @nickdos

**Comment by nickdos** [comment]
@ansell I'm not sure what you mean by:
>  Do not expand the All species group automatically
Are you thinking the middle column should be empty initially (until user clicks on a species group)? Or something else?

**Comment by ansell** [comment]
@nickdos Yes, it sounds wrong to me as well now that I reread it. I put a strike-through on that one. 

The idea for only populating the group on the right panel after they click on one of the species groups is the next point after that. If we do that, we potentially avoid some calls to `ALL_SPECIES.json` I think, and replace those with calls to subgroups for whatever the user was actually interested in and clicked on in the left panel.

**Comment by nickdos** [comment]
FYI I'm working on a branch for this - https://github.com/AtlasOfLivingAustralia/biocache-hubs/tree/EYA-enhancements

**Comment by ansell** [comment]
The core performance issues for this are done, the others were suggestions but are not critical, so closing this issue as fixed for now.
