### ISSUE TITLE
OGC service params should be case insensitive

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#366]
Currently some OGC services (e.g. WMS tiles) require the OGC params to be provided in upper case. The problem is that recent versions of Leaflet send the various dynamic params in lower case by default and the tiles fail to load. There is an option in Leaflet to send params in upper case (`uppercase: true`) but this sends all params in upper case and then the ALA-defined params are ignored. E.g. `LAT` and `LON` are ignored, as they are required to sent in lowercase! 

The OGC spec says params should not be case sensitive:

http://cite.opengeospatial.org/OGCTestData/wms/1.1.1/spec/wms1.1.1.html#basic_elements.param_rules.order_and_case

**Comment by nickdos** [comment]
@ansell suggested:
> This option using a Filter looks like it could possibly be supportable by biocache-service without changing the way RequestParam works https://stackoverflow.com/questions/29531786/making-a-request-parameter-binding-case-insensitive/29533456

**Comment by adam-collins** [comment]
Fix for this is on docvalues branch.

**Comment by djtfmartin** [comment]
@adam-collins ive reverted the commits for case-insensitivity as they broke WMS

**Comment by KeyboardSounds** [comment]
@adam-collins @djtfmartin this issue is affecting us (see [here](https://github.com/TerriaJS/neii-viewer/issues/143)), and I'd like to take a crack at fixing it. If I put together a PR, would it be possible for you to review, (and if you're happy with it) merge and release?

**Comment by djtfmartin** [comment]
Thanks @KeyboardSounds ! Yes that would be great.

**Comment by Rita-C** [comment]
Tested on `https://biocache-test.ala.org.au/`

**Comment by nickdos** [comment]
Re-opening until deployed to prod (done column)

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
