### ISSUE TITLE
WMS: density grid tiles are not rendering correctly

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#367]
The WMS tiles output when requesting "record density grid" output in biocache UI, is showing a completely different pattern to the regular dots output.

https://biocache.ala.org.au/occurrences/search?taxa=acacia#tab_mapView

![dots](https://user-images.githubusercontent.com/532845/52831066-46092200-3127-11e9-9717-9a6988511993.png)

change the map option drop-down to "record density grid" and it shows:

![grid](https://user-images.githubusercontent.com/532845/52831047-325dbb80-3127-11e9-8c78-f4bc0ce112f8.png)

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/commit/1d5d59cd554b9ab1ca40f876fd4ec81e1b6de214
