### ISSUE TITLE
Outlier facets are buggy

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#369]
Reported by a user:

> I’ve been using your useful outlier detection facility.
>
> When I take a species with outliers (such as Mycena interrupta - https://biocache.ala.org.au/occurrences/search?q=lsid:b521e32c-4af4-4ece-9f0d-6779e0caaa32#tab_recordsView) and add “Outlier layer count” in the filter, I often get two options:
> 
> Not a detected outlier (20)
Not supplied (3102)
> 
> It seems that there are in fact 20 records with outliers, matching the category “Not a detected outlier”, but presumably the options should include “Outlier for x layers”, for as many different categories as necessary (I can see that some records are outliers for multiple layers, up to three).
> 
> Sometimes over the last few weeks for some species there have been options that include “Outlier for one layer“, but this occurring along with the category “Not a detected outlier”.
> 
> Should the numbers of layers for which records are outliers be included as categories under “Outlier layer count”?

I confirmed [this search](https://biocache.ala.org.au/occurrences/search?q=lsid%3Ab521e32c-4af4-4ece-9f0d-6779e0caaa32&fq=outlier_layer_count%3A%220%22) is showing results for  `Outlier layer count: "Not a detected outlier"` yet also shows facet results for:

```
Outlier for layer
  Precipitation - seasonality (Bio15) (13)
  Moisture Index (Bio32) (5)
  Radiation - seasonality (Bio23) (2)
```

So the numbers don't add up. I think the `fq=outlier_layer_count:"0"` is the give-away. It must be indexing that the layer count is 0 when in fact its not 0 but 1 (or more). So code that adds up the number of layers triggered is buggy.

**Comment by nickdos** [comment]
@adam-collins does this look like an indexing or biocache-service issue? I'm thinking the former.

**Comment by adam-collins** [comment]
outlier_layer_count is indexed incorrectly. 

https://github.com/AtlasOfLivingAustralia/biocache-store/commit/17ceb58356b915303ad52c093c832fdd6a175899

**Comment by djtfmartin** [comment]
i think this is fixed.
