### ISSUE TITLE
Export checklist gives only species with Species rank 

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-service#37]
_From @sadeghim on December 23, 2014 2:10_

Does the spatial portal export taxonomic lists in different levels through **Export Checklist**? 

Here is the related request asked by an Atlas user:

*I have found a major fault that has crept in since the last time I did a
search in Spatial Portal on organisms in a defined area. All the
infraspecific information (eg subspecies, variety) has been deleted from
the result of the search.*

*Taxonomists regularly move organisms from being a full species to a
subspecies or variety of another species and back again. Governments
gazette particular infraspecies of an organism as Threatened Species or
Noxious Weeds. Other infraspecies of the same species are not so
gazetted. This information is important.*

_Copied from original issue: AtlasOfLivingAustralia/spatial-portal#55_

**Comment by djtfmartin** [comment]
_From @Tasilee on December 23, 2014 2:24_

The checklist should contain names down to the lowest level in the biocache that have observations in the area.

**Comment by djtfmartin** [comment]
_From @sadeghim on December 23, 2014 2:33_

I downloaded the checklist for the whole world, it didn't contain any lower level name than species.

**Comment by djtfmartin** [comment]
_From @adam-collins on January 13, 2015 1:14_

Species lists are all rank specific. Need to revisit this in biocache.

**Comment by adam-collins** [comment]
/occurrences/facets/download now supports &lookup=true and &count=true when using &facets=names_and_lsid 

species rank example
http://biocache.ala.org.au/ws/occurrences/facets/download?facets=species_guid&lookup=true&count=true&q=macropus

any rank example, lsid needs to be parsed out if required
http://biocache.ala.org.au/ws/occurrences/facets/download?facets=names_and_lsid&lookup=true&count=true&q=macropus

SP needs an update now.

**Comment by Tasilee** [comment]
This looks good. Please advise post SP update.
