### ISSUE TITLE
HTTP POST to /ws/webportal/params are timing out intermittently

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#370]
Not clear from a quick code review of the handler for `/ws/webportal/params` why it could be timing out, but there are a large number of queries timing out. If a query doesn't succeed after 5 seconds (which is already longer than expected for creating a `qid`) then it seems to be timing out when nginx gives up after 180 seconds:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/ef9e5856d23dce1649f19d6f663f24e59ab8b233/src/main/java/au/org/ala/biocache/web/WMSController.java#L227-L275

The following is the kibana permanent URL to the period that is showing the long queries (queries less than 1 second are excluded in this view)

`https://kibana.ala.org.au/app/kibana#/discover/55b4e370-4aa8-11e9-8659-3985e25fefdd`

**Comment by adam-collins** [comment]
This remains a potential issue.

**Comment by adam-collins** [comment]
Also apply this `fix` to other POST enabled services for WKT.

**Comment by adam-collins** [comment]
Removed the simplification loop. Added simplification where missing. 

pull request https://github.com/AtlasOfLivingAustralia/biocache-service/pull/871

**Comment by adam-collins** [comment]
The goal of this issue is to reduce infrequent timeout responses by the internal proxy that are the result of proxy config limits and potentially slow code in biocache-service.

For end users the change means that WKT sent can be larger before a timeout occurs.
