### ISSUE TITLE
map download doesn't include the base map

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-service#371]
e.g. https://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Af9eb417b-2de3-48ac-ba4e-1d438f0cb323&fq=license%3A%22CC0%22+OR+license%3A%22CC-BY%22+OR+license%3A%22CC-BY+4.0+%28Int%29%22+OR+license%3A%22CC-BY+3.0+%28Au%29%22+OR+license%3A%22CC-BY-Int%22&fq=country%3AAustralia&fq=-data_resource_uid%3Adr635#tab_mapView

Download map - base layer either State and Territories or simple world outline - no base layer included in download, just the points

**Comment by nickdos** [comment]
ALA biocache is requesting a param `baselayer=aus1` which used to work but only dots are showing on JPG file. `baselayer=world` also shows no boundaries as does `ALA:aus1`.

**Comment by adam-collins** [comment]
Fixed. Cache not reset.
