### ISSUE TITLE
apikey cache is static and permanent for the lifetime of the JVM

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#374]
The cache of valid apikeys is static and permanent for the lifetime of the JVM. This prevents apikeys that have been removed from being disallowed for use by biocache-service until after biocache-service is restarted next time (and possibly forever if the on-disk cache is setup and it is caching this field??). 

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/9f08a35b6b3735af5c69eace2d882a4bc367112d/src/main/java/au/org/ala/biocache/web/AbstractSecureController.java#L52

**Comment by nickdos** [comment]
Can I move/copy this into biocache-service issues or is it sensitive and should be kept non-public?

**Comment by ansell** [comment]
This is public currently

**Comment by ansell** [comment]
The reasoning for having this issue public is that it isn't accessible for end-users without either `ROLE_ADMIN` to create a new apikey or having one of our active apikeys (which would be a separate issue anyway).

It is still an issue as it makes it a pain to revoke apikeys as each of the biocache-service instances need to be restarted in turn to clear their permanent cache.

**Comment by nickdos** [comment]
Could've sworn it was in infrastructure repo...

**Comment by ansell** [comment]
When someone gets to working on this issue, my partial commit on the branch for it should be able to be rebased onto the current code, and if there are issues I can help with rebasing.

https://github.com/AtlasOfLivingAustralia/biocache-service/compare/issue-374-api-key-cache-fix

**Comment by nickdos** [comment]
@ansell could you please QA this in test?

**Comment by ansell** [comment]
- [x] Verified the war filehash on biocache-ws-test that is in use for testing using sha1 hash of `a9d393e45b0e67d07adc35194b63995956556ab3` which traced that successfully to this `2.4-SNAPSHOT` version in nexus: https://nexus.ala.org.au/service/local/repositories/snapshots/content/au/org/ala/biocache-service/2.4-SNAPSHOT/biocache-service-2.4-20200702.050728-35.war
- [x] Create a new apikey on auth-test.ala.org.au for this purpose at 10:34
- [x] Confirmed the apikey worked initially with the biocache offline download status URL: `https://biocache-ws-test.ala.org.au/ws/occurrences/offline/download/stats?apiKey=[REDACTED]` at 10:34
- [x] Revoked the apikey on auth-test.ala.org.au at 10:35
- [x] Apikey still works at 10:36 (expected, due to the expiry time on the cache)
- [x] Confirmed apikey failed at 10:41 (7 minutes after first use, and 5 minutes after revocation)

@brucehyslop There is a small different in the documentation, it says "5 minutes", but then specifies "360 seconds", which is 6 minutes: https://github.com/AtlasOfLivingAustralia/biocache-service/commit/948618fce7a143b09a3106289f31ed137e76cb58#diff-90509f0cf4fe6fce6d03978c8dd0c5daR13-R14

**Comment by ansell** [comment]
Will still move this into Ready for CAB as the documentation issue is very minor.
