### ISSUE TITLE
Add app.version to meta tags

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/biocache-service#376]
`biocache-service` currently don't expose its `app.version` as other services do.

Would be nice to have this build info also available for each node. 

See:
https://github.com/AtlasOfLivingAustralia/documentation/wiki/Components-versioning
generated from:
https://github.com/AtlasOfLivingAustralia/documentation/wiki/LA-Nodes-and-Components

**Comment by nickdos** [comment]
Just started looking at this - https://www.vojtechruzicka.com/spring-boot-version/ looks helpful.

**Comment by vjrj** [comment]
Maybe we can use this:
https://stackoverflow.com/questions/3697449/retrieve-version-from-maven-pom-xml-in-code
https://stackoverflow.com/questions/2712970/get-maven-artifact-version-at-runtime

**Comment by brucehyslop** [comment]
I have written a new `BuildInfoController` and view that mimics [ala-admin-plugin/BuildInfoController.groovy](https://github.com/AtlasOfLivingAustralia/ala-admin-plugin/blob/master/grails-app/controllers/au/org/ala/admin/BuildInfoController.groovy).
Build and runtime properties are injected via maven `git-commit-id-plugin` plugin.

The build info can be access at `/ws/buildInfo` for html view or `/ws/buildInfo.json` for JSON output.
