### ISSUE TITLE
Upgrade GeoTools to the latest version

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#381]
The GeoTools version in use, `11.1` is unacceptably old and is likely to be much slower than a modern version. An example of a performance issue that we could expect the recent GeoTools releases to have looked into and possibly improved on is related to the urgent need to restrict large shapefile downloads, as described in #380

**Comment by nickdos** [comment]
@djtfmartin I think you might have done this already in your current branch or recent commit...

**Comment by ansell** [comment]
The master branch on layers-store, which also needs to be updated at the same time as biocache-service is still on 11.1. I opened the issue here but could move or also open an equivalent issue for layers-store. https://github.com/AtlasOfLivingAustralia/layers-store/blob/master/pom.xml#L272

If there is uncommitted code, then that would explain it, but I can't find it in the branches that have been pushed to github.

**Comment by djtfmartin** [comment]
This dependency is transitive from the layers-store dependency.
I've upgrade this on a branch, but there is a complete lack of JUnit tests which is stopping us from upgrading at this moment.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
