### ISSUE TITLE
SimpleCORSFilter allows all origins to access biocache-servivce

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#382]
`SimpleCORSFilter` is hardcoded to allow all origins to access `biocache-service`. This enables any authenticated users permissions to be used to request sensitive `biocache-service` resources.

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/web/SimpleCORSFilter.java#L29

At minimum this should be configurable, and ideally CORS should be turned off by default and only switched on by users who are aware of the security consequences of doing so.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
