### ISSUE TITLE
Add host to SOLR indexed fields

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/biocache-service#386]
Requested by Keith McGuire of the South Australian Museum.

For parasites, the host is a key piece of information.

To begin with, simply include the host DwC field in the SOLR index. Potentially include name-matching and a hostTaxonID in future.

**Comment by nickdos** [comment]
FYI, this is already in APPD.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
