### ISSUE TITLE
Improve text in download email

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#391]
Related to #246.

Current email example:

![image](https://user-images.githubusercontent.com/532845/62348724-ecfc4180-b540-11e9-8f7f-cc9ddc61fa00.png)

The email shows the DOI URL as the main "link" to get the download file (ZIP). The problem is that the DOI system in ARDC can be slow to mint the DOI and the user can get an error message instead. This is also a problem when the DOI resolver is "down" (out of our control). We then get support tickets from users (often 3-4 a day when DOIs are very slow).

Fix is to show the URL to the download on our DOI server, using its native URL and not the DOI version. We should also show the DOI a bit lower and include some text about encouraging the citation of the DOI in any publications that use this download.

E.g. for the screenshot above, the main link should be https://doi.ala.org.au/doi/359ae391-0535-4795-8c2a-90f0ad80914b.

The reason is, 99% of users want to quickly get to the ZIP file and they don't care about the DOI.

**Comment by ansell** [comment]
An alternative for this is to switch the static base from `https://doi.org/` to `https://doi.ala.org.au/doi/`, which will resolve as long as our doi infrastructure is working and still contains the DOI, rather than our internal GUID

**Comment by Rita-C** [comment]
Waiting for wording suggestion from BA/Comm.

**Comment by nickdos** [comment]
Hi @Rita-C - a simple approach is to change the second line of the email (link to DOI) to be the URL to the file on DOI server.

E.g. from

https://doi.org/10.26197/5d65d53d438d0

to

https://doi.ala.org.au/doi/c44c4910-23e5-4916-8b66-32bab793e0b5

and to add the DOI URL under the DOI reference (line 3).

E.g. full email:

> Your download can be accessed on the page:
> 
> https://doi.ala.org.au/doi/c44c4910-23e5-4916-8b66-32bab793e0b5
> 
> The DOI for this download is DOI10.26197/5d65d53d438d0 
> 
> https://doi.org/10.26197/5d65d53d438d0 
> 
> When using this dataset please use the following citation: 
> 
> Atlas of Living Australia occurrence download at [https://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A91c90b44-e9dd-4ce1-a4b5-37d60d59b859&fq=data_resource_uid%3A%22dr466%22](https://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A91c90b44-e9dd-4ce1-a4b5-37d60d59b859&fq=data_resource_uid%3A%22dr466%22) accessed on Wed Aug 28 11:13:23 AEST 2019. 
> 
> Also cite the contributing data providers which are listed in the included "citation.csv" file.
> 
> More information can be found at [citing the ALA](https://www.ala.org.au/about-the-atlas/terms-of-use/citing-the-atlas/).
> 
> All of your DOI assigned downloads are available [here](https://doi.ala.org.au/myDownloads).

**Comment by Rita-C** [comment]
Hi @nickdos , so we only adding line 3 - the DOI ref, no other wording changes, that's fine.

Can both links use DOI, i.e. not uuid in the first one?

**Comment by nickdos** [comment]
> Can both links use DOI, i.e. not uuid in the first one?

That is the point of the issue - the DOI link is not reliable & often takes 30 minutes to mint and "resolve". So when a user gets the email, they click that link and get a 404 error. We know the `doi.ala.org.au` link will always resolve, so that is why we want to show it first.

**Comment by Rita-C** [comment]
Okay.

**Comment by ansell** [comment]
@nickdos https://doi.ala.org.au/doi/10.26197/5d65d53d438d0 also works, and contains the DOI identifier inside of it, rather than the GUID version that is opaque and internal to the ALA.

**Comment by nickdos** [comment]
Good point @ansell  - @Rita-C you could test the form of the URL Peter mentioned above first(?), as its a bit nicer than the UUID version.

**Comment by Rita-C** [comment]
@ansell, @nickdos Updated code to use DOI in both downloading URLs, e.g.

   

>  Your download can be accessed on the page:
> 
>     https://doi.ala.org.au/doi/10.26197/5d65d53d438d0
> 
>     The DOI for this download is DOI10.26197/5d65d53d438d0
> 
>     https://doi.org/10.26197/5d65d53d438d0
> 
>     When using this dataset please use the following citation:
> 
>     Atlas of Living Australia occurrence download at https://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A91c90b44-e9dd-4ce1-a4b5-37d60d59b859&fq=data_resource_uid%3A%22dr466%22 accessed on Wed Aug 28 11:13:23 AEST 2019.
> 
>     Also cite the contributing data providers which are listed in the included "citation.csv" file.
> 
>     More information can be found at citing the ALA.
> 
>     All of your DOI assigned downloads are available here.

**Comment by nickdos** [comment]
Actually on second thought, the second and third lines could be merged into one, as:

> The DOI for this download is https://doi.org/10.26197/5d65d53d438d0

which will remove the styled DOI box.

I think this is better, as having two representations of the DOI is confusing to users, and the URL form is the preferred way to display DOIs, as of 2017 (see https://www.crossref.org/display-guidelines/).

**Comment by Rita-C** [comment]
@nickdos the second is rendered differently, I think it looks fine:
![Screen Shot 2019-09-02 at 10 43 11 am](https://user-images.githubusercontent.com/29115246/64084443-e98ded00-cd6e-11e9-89ae-7e0c36cd2ad0.png)

**Comment by nickdos** [comment]
The difference is only for test DOIs, prod DOIs will be the same.

The aim for the second line is to provide a string the user can copy and paste into a form when submitting a paper for publication. DOI organisation now prefers the full URL as the display format, so this is why I suggest removing the styled box version and just show the URL.

**Comment by Rita-C** [comment]
Okay, 
![Screen Shot 2019-09-02 at 11 12 27 am](https://user-images.githubusercontent.com/29115246/64084861-a33a8d00-cd72-11e9-88cc-21861b3164fd.png)

**Comment by ansell** [comment]
Is `All of your DOI assigned downloads are available here.` being removed as part of this issue. It currently gives a link to `https://doi.ala.org.au/myDownloads`.

**Comment by nickdos** [comment]
`All of your DOI assigned downloads are available here.` should be there still, on last line...

**Comment by ansell** [comment]
It is present in `ala-install`, which will need to be updating to push these changes into `biocache-ws-test`, Rita is working on a 12 months+ old copy of this obtained from another location. https://github.com/AtlasOfLivingAustralia/ala-install/blame/master/ansible/roles/biocache-service/templates/config/download-doi-email.html#L1047

**Comment by Rita-C** [comment]
Do we want to remove the styled DOI from the readme file (part of the zip) as well?

**Comment by ansell** [comment]
Updating the other template at https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/biocache-service/templates/config/download-doi-readme.html would be useful to keep them using the same style.

**Comment by nickdos** [comment]
> @nickdos Do we want to remove the styled DOI from the readme file (part of the zip) as well?

Yes, may as well, assuming its the same text as the email.

**Comment by Rita-C** [comment]
@ansell @nickdos , can one of you review the changes please? The biocache-service change is in a different branch, would be good to merge it back.

**Comment by ansell** [comment]
I don't understand why the previous property, which other Living Atlases may have been using since it was introduced 12 months ago, was changed to include `.ala.`

**Comment by Rita-C** [comment]
> I don't understand why the previous property, which other Living Atlases may have been using since it was introduced 12 months ago, was changed to include `.ala.`

If you refer to "download.doi.ala.resolver", that was introduced by me.

**Comment by ansell** [comment]
Ahh, you made a change to the master branch before the latest commit which added the new property https://github.com/AtlasOfLivingAustralia/ala-install/commit/4e42b2630fa9b9cb4d9179951c8506cd9d386be3#diff-e01ad0946746ba73827bb747db78e1c0

It would be ideal not to have `.ala` in the property name so that other Living Atlases can reuse it without thinking it is ALA-specific.

**Comment by Rita-C** [comment]
> Ahh, you made a change to the master branch before the latest commit which added the new property [AtlasOfLivingAustralia/ala-install@4e42b26#diff-e01ad0946746ba73827bb747db78e1c0](https://github.com/AtlasOfLivingAustralia/ala-install/commit/4e42b2630fa9b9cb4d9179951c8506cd9d386be3#diff-e01ad0946746ba73827bb747db78e1c0)
> 
> It would be ideal not to have `.ala` in the property name so that other Living Atlases can reuse it without thinking it is ALA-specific.

`ala` removed.

**Comment by Rita-C** [comment]
`ala` removed.

**Comment by ansell** [comment]
Closing and moving to Ready for CAB on project board
