### ISSUE TITLE
Fix header/footer text on prod /ws/ page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#394]
Following the new WP server change, the skin (header/footer) for https://biocache.ala.org.au/ws is broken (due to missing CSS and JS files).

![image](https://user-images.githubusercontent.com/532845/62918689-ca411700-bde3-11e9-9943-56d8dceacfa2.png)

Fix is to point to newer versions that use the 2019 skin. E.g. https://www.ala.org.au/commonui-bs3-2019/css/ala-styles.css.

**Comment by ansell** [comment]
https://biocache-ws-test.ala.org.au/ws/ is now skinned. Closing this issue and moving to the CAB column on the project board.
