### ISSUE TITLE
i18n label change

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#396]
Change the i18n properties file for the value `alau_user_id` that is substituted in facet output. E.g. See https://biocache-ws.ala.org.au/ws/occurrences/search?q=*%3A*&fq=data_resource_uid%3A%22dr1411%22&fq=alau_user_id%3A%22superstaryn1%22&pageSize=0

Change `Atlas user` to be `User ID`. E.g.

`displayName: "Atlas user:"superstaryn1"",`

should be

`displayName: "User ID:"superstaryn1"",`

Please check the code/properties files for any other instances of `alau_user_id` that get read as `Atlas user` (or similar).

**Comment by ansell** [comment]
Verified this is working on biocache-ws-test, closing and moving to Ready for CAB
