### ISSUE TITLE
Batch catalogNumber search not working

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-service#397]
https://support.ehelp.edu.au/a/tickets/38356

https://biocache.ala.org.au/#tab_catalogUpload 

throws 

HTTP Status 400 -

type Status report

message

description The request sent by the client was syntactically incorrect.
Apache Tomcat/7.0.68 (Ubuntu)

**Comment by nickdos** [comment]
This was working previously, so a change in `biocache-service` is a likely cause. 

Is it now expecting an `apiKey`, possibly?

**Comment by ansell** [comment]
`biocache-ws-test.ala.org.au` is running 2.3-SNAPSHOT (not sure which commit) and it works there

I tested by searching for `MELUD121229a` and it correctly found the record `https://biocache-test.ala.org.au/occurrences/search?q=qid:1566881973769`
