### ISSUE TITLE
Find alternative mechanism for data files used by docker for testing

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#402]
The binary files used by docker for testing have been removed. This issue is aimed at finding a sustainable git and docker friendly solution to the need for data files during integration tests.

**Comment by djtfmartin** [comment]
The files are not in use during the integration tests. They where left in the repository to make the generation of the docker images (which are used by the integration tests) more easy for further development (as and when test data needs to change). 
I don't have a problem with binary content in repositories - we have test JPEGs/PNGs and zips in various places, but im not prepared to argue that strongly for these files.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
