### ISSUE TITLE
Support client defined email templates supplied to download

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/biocache-service#405]
The CSDM project needs a customised email to be sent to the user after a modelling data set has been downloaded and a DOI created.
This email will contain instructions for how to use the data in the CSDM modelling tool, and link to that tool.

The template could be selected via the reason code supplied to the download request or via a direct client parameter.

**Comment by ansell** [comment]
The only issue I would have is if the template file itself was being named by the parameter. As long as there is a mapping in the configuration from a parameter/code to an actual file name this is okay from a security perspective.

**Comment by nickdos** [comment]
Please clean-up CSS if working on this issue - see #410.

**Comment by temi** [comment]
Code review: 
https://github.com/AtlasOfLivingAustralia/biocache-service/commit/a99028bf70d9d47711f6ce155d6a2290caed848e

Email template can be found here - https://github.com/AtlasOfLivingAustralia/ala-install/commit/fac927e5e78d650c83da52ef5e98b1a8f07152a5

**Comment by temi** [comment]
Another commit to review:
https://github.com/AtlasOfLivingAustralia/biocache-service/commit/c771227e357f4b579ea01596dcfb99bcde5a8409

**Comment by ansell** [comment]
Reviewing these changes one by one isn't easy. I have opened a Pull Request to review them all: 

https://github.com/AtlasOfLivingAustralia/biocache-service/pull/411

**Comment by temi** [comment]
https://upsource.ala.org.au/biocache-service/review/BS-CR-2

**Comment by brucehyslop** [comment]
New PR #503 created to replace #444

**Comment by brucehyslop** [comment]
:white_check_mark: confirmed that when the params `&emailTemplate=csdm&mintDoi=true` the email matches the cddm template. 

<img width="853" alt="Screen Shot 2020-09-17 at 3 15 45 pm" src="https://user-images.githubusercontent.com/12233783/93423161-ad391a80-f8f8-11ea-9a41-1d18d9ecc849.png">
