### ISSUE TITLE
occurrence_year not working with webportal/legend and cm ranges

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-service#408]
does not work https://biocache.ala.org.au/ws/webportal/legend?q=*:*&cm=occurrence_year,1823-01-01T00:00:00.000Z,1850-12-31T20:34:17.000Z&type=application/json 

works https://biocache.ala.org.au/ws/webportal/legend?q=*:*&cm=occurrence_date,1823-01-01T00:00:00.000Z,1850-12-31T20:34:17.000Z&type=application/json

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
