### ISSUE TITLE
AlaImageMetadataService ignores errors, obscuring the cause of issues

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#409]
The code in `AlaImageMetadataService` should check response codes and response content types before working on the responses. In particular, it should check for `HTTP 200` as the response code, and `application/json` as the response content type before working on the following two lines. `EntityUtils.toString` blindly copies the contents of the response, which in the case of errors may not be JSON but HTML, causing hard to diagnose Jackson issues that are not obviously caused by feeding it a non-JSON content.

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/service/AlaImageMetadataService.java#L73-L75

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
