### ISSUE TITLE
/var/log/tomcat7/biocache-service.log deleted/reset; NEEDS to be archived/preserved

### ISSUE THREAD

**Issue by mbohun** [AtlasOfLivingAustralia/biocache-service#41]
both **production** and test env **biocache-service log (and most likely other services)** ansible-playbook-s should make sure that `biocache-serice.log` (and all other important log files: tomcat, solr, etc.) are properly preserved/archived (i found out accidentally on the 2015-02-20 when the `/var/log/tomcat7/biocache-service.log` i was working with was deleted, resp. replaced/reset and all the existing log messages starting from early January 2015 were lost)

NOTE: it is very likely that this applies to all ALA production vm-s/services

**Comment by nickdos** [comment]
Ansible issue - moving

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/ala-install#71
