### ISSUE TITLE
Download emails - remove un-referenced CSS rules

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#410]
The download emails appear to be simple, un-styled text-based emails (from user perspective) but they are HTML styled and contain a very long list of CSS styles. See email source example:

[biocache-test-email-src.txt](https://github.com/AtlasOfLivingAustralia/biocache-service/files/3781180/biocache-test-email-src.txt)

Most of those CSS rules can be deleted. In particular the rule that adds 80-140 px space above the beginning block of text (which is just weird and confusing).

![image](https://user-images.githubusercontent.com/532845/67735809-67adfd80-fa59-11e9-8d95-f6e8422376ea.png)

Linking to similar issue, to be done at the same time: #405.

**Comment by temi** [comment]
@nickdos Refactored email template and it is now deployed on biocache-test. You can look at the changes here https://github.com/AtlasOfLivingAustralia/ala-install/commit/fac927e5e78d650c83da52ef5e98b1a8f07152a5 .

**Comment by nickdos** [comment]
@temi changes look good, thanks.

**Comment by nickdos** [comment]
@Temi just a minor suggestion for any of the templates that show a DOI, is to link the word "DOI" to the URL https://www.doi.org/.

E.g. The DOI for this download is

to be 

The <a href="https://www.doi.org/">DOI</a> for this download is

As I've had a support email where the person mentioned they had no idea what a DOI was.

**Comment by temi** [comment]
@nickdos as discussed, added link to wiki article (https://github.com/AtlasOfLivingAustralia/ala-install/commit/3ce2c12ff99ca6a60a09db86cffeec8205b0bf3a).

**Comment by nickdos** [comment]
done - in prod
