### ISSUE TITLE
Support User-Agent blacklist for logger submissions

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#412]
The nginx logs on the ALA logger system seem to show our monitoring software creating entries in the logger database, which is unnecessary and will skew numbers for those data resources, collections and institutions which are incidentally included in the static monitoring queries:

```
3.106.48.174 - - [01/Nov/2019:10:22:16 +1100] "POST /service/logger HTTP/1.1" 200 674 "-" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/98 Safari/537.4 (StatusCake)" "-"
```

- [ ] Support a `User-Agent` blacklist for logger submissions in `biocache-service`

Some possible implementation methods are:

* Reject the query in the existing Tomcat Filter `LoggerConfigFilter` where we are currently mapping it through:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/web/LoggerConfigFilter.java

* Reject the query in LogTypeValidator, but that may require new fields and would require LogTypeValidator to be made mandatory (it is currently optional and setup with a global non-specific disable flag `caches.log.enabled`):

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/validate/LogTypeValidator.java

* Reject the query in `ala-logger` (the client library)

https://github.com/AtlasOfLivingAustralia/ala-logger/blob/master/src/main/java/org/ala/client/appender/RestfulAppender.java

**Comment by brucehyslop** [comment]
The logging of events for `biocache-servive` has via the log4j appender has been deprecated in PR #470 and the `LoggerConfigFilter` removed. 

The logging is now handled by the [`LoggerService.logEvent(LogEventVO logEvent)`](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/service/LoggerService.java#L35). Filtering of blacklisted `User-Agent` should be done by [`LoggerRestService.logEvent(LogEventVO logEvent)`](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/cb880f014545ad0506975860b639ca9b202a6806/src/main/java/au/org/ala/biocache/service/LoggerRestService.java#L96).

**Comment by Rita-C** [comment]
Discussed with @ansell , It isn't an issue since #513 was implemented because it was the StatusCake requests to occurrence record view pages that was the worrying part. Moved to ready for CAB.
