### ISSUE TITLE
Mislabelled field in full dwc download

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-service#413]
Copied from  AtlasOfLivingAustralia/data-management#527

> In this full Darwin Core download of 649186 iNaturalist records:

> https://doi.org/10.26197/5da76dbb62b55

 > 1.
> there are 5 pseudo-duplicated fields, 1 apparently mislabeled field and blanked entries. The mislabelled field is (details from headings.csv): "maximumDepthInMeters","max_depth_d","maximumDepthInMeters","max_depth_d","Maximum depth in meters","max_depth_d","Maximum depth in meters","http://rs.tdwg.org/dwc/terms/maximumDepthInMeters"
> "maximumDepthInMeters","min_depth_d","maximumDepthInMeters","min_depth_d","Minimum depth in meters","min_depth_d","Minimum depth in meters","http://rs.tdwg.org/dwc/terms/maximumDepthInMeters

**Comment by ansell** [comment]
Support ticket 59763 refs this issue. Release of the fix is currently blocked by #422

**Comment by ansell** [comment]
Cherry-picked the change for this to a hotfix branch and deploying to biocache-ws-test

**Comment by ansell** [comment]
This is ready for testing on biocache-test. For me, it looks right, but for CAB we need an independent reviewer.

**Comment by ansell** [comment]
Testing for this involves performing a full Darwin Core download on biocache-test and verifying that the line for `maximumDepthInMeters` now correctly contains `Maximum depth in meters`

**Comment by sadeghim** [comment]
Tested and it works.
