### ISSUE TITLE
Issues with quality check fields for names and identifications

### ISSUE THREAD

**Issue by Mesibov** [AtlasOfLivingAustralia/biocache-service#414]
I downloaded the 61334-record ANIC Hymenoptera dataset on 2019-11-04 (https://doi.ala.org.au/doi/10.26197/5dbf279172f6f) and found a number of taxon name issues in the subset of 48751 records from Australia ("Australia", "Christmas Island", "Cocos Islands", "Norfolk Island"). These are described in a separate issue (q.v.) Here I'm querying 4 of the data quality check fields for the 61334-record set.

Invalid scientific name:
"false" for 61332 of the 61334 records. "true" for
Signiphora (Unplaced) coquilletti Ashmead, 1900 (up-matched to Signiphora)
Signiphora (Unplaced) sp. (up-matched to Signiphora)
But there are numerous other invalid scientific names as supplied, e.g.
Acropyga sp_no_8
Anoplius () amoenulus (Turner, 1910)
Arpactophilus p128 Naumann
Camponotus ceriseipes_complex
Camponotus claripes_group
What are the parsing rules for "Invalid scientific name"?

Missing identification qualifier:
"false" for all 61334 records, but all 61334 entries for identificationQualifier in the download are the string "Not provided"

Missing name of person who identified the specimen/observation:
"false" for all 61334 records, but identifiedBy is blank for 49467 records

Name not in national checklist:
"false" for all 61334 records, but there are many names not in the NSL, e.g.
Paramesius consimilis (Dodd, 1926), up-matched to Paramesius
Does "Name not in national checklist" mean "No part of supplied scientific name is in national checklist?"

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
