### ISSUE TITLE
Issues with taxon name fields

### ISSUE THREAD

**Issue by Mesibov** [AtlasOfLivingAustralia/biocache-service#415]
I downloaded the 61334-record ANIC Hymenoptera dataset on 2019-11-04 (https://doi.ala.org.au/doi/10.26197/5dbf279172f6f) and found a number of taxon name issues in the subset of 48751 records from Australia ("Australia", "Christmas Island", "Cocos Islands", "Norfolk Island"). These are described here. In a separate issue (q.v.) I query 4 of the data quality check fields related to names and identifications..

(1) The following supplied scientific names (with no. of records) were all up-matched to the indicated genus, apparently because the parser had trouble with the replacement character in the authority name as supplied. Each of the supplied names (with correct characters) is in AFD.

Anonychomyrma nitidiceps (Andr�, 1896) (17)
Dolichoderus australis Andr�, 1896 (44)
Leptomyrmex nigriventris (Gu�rin-M�neville, 1831) (32)
Myrmecorhynchus emeryi Andr�, 1896 (97)
Notoncus enormis Szab�, 1910 (5)
Notoncus spinisquamis (Andr�, 1896) (28)
Polyrhachis semipolita Andr�, 1896 (1)
Pristomyrmex quadridentatus (Andr�, 1905)	(73)
Prolasius nitidissimus (Andr�, 1896) (8)
Rhytidoponera victoriae (Andr�, 1896) (12)

(2) ALA appears to follow the rule that if there are multiple subspecies in the AFD for a particular species, then the species name supplied without a subspecies should be down-matched to the nominate subspecies. This replacement will be incorrect if the occurrence is for a subspecies (not specified by the data provider) other than the nominate one. In the ANIC Australian Hymenoptera dataset there are 10 such cases, e.g. Camponotus oetkeri Forel, 1910 was replaced with Camponotus oetkeri oetkeri Forel, 1910, and taxonRank given as "subspecies" (https://biocache.ala.org.au/occurrences/f79da9f3-7acc-47f5-93a9-bd5270d8427c)

Records	Supplied name				No. of subspp in AFD
15	Camponotus aeneopilosus Mayr, 1862		2
1	Camponotus oetkeri Forel, 1910		2
24	Opisthopsis diadematus Wheeler, 1918		2
208	Opisthopsis haddoni Emery, 1893		2
41	Opisthopsis pictus Emery, 1895		4
1	Pheidole anthracina Forel, 1902		3
1	Pheidole athertonensis Forel, 1915		3
1	Pheidole concentrica Forel, 1902		2
1	Pheidole deserticola Forel, 1910		2
3	Tapinoma minutum Mayr, 1862		4

(3) 43 records with the supplied scientific name "Ctenostegus Haupt, 1930" were up-matched to Pompilidae because of the taxonomic issue "Matched to homonym". Example: https://biocache.ala.org.au/occurrences/fa018f13-6e30-4670-8dec-382f6908b802. There is no suggestion of homonymy in the AFD (https://biodiversity.org.au/afd/taxa/Ctenostegus),  in the Catalogue of Life or in the GBIF taxonomic backbone. How was Ctenostegus Haupt, 1930 matched to a homonym?

(4) The following misspelled supplied scientific names were up-matched to the indicated genus, but could have been fuzzy-matched? All correct names are in AFD.

Iphiaulax profiscator (Fabricius, 1775) (1 record) / Correct: profisciscator
Lasioglossum (Chilalictus) repraesantans Smith, 1853 (2) / Correct: repraesentans
Monomorium capito Heterick, 2001 (1) / Correct: captio
Podomyrma gastralis Emery, 1897 (2) / Correct: grastralis

(5) The following malformed supplied scientific names (not flagged as "Invalid scientific name") were up-matched to the indicated genus, although both species names are in AFD:

Anoplius () amoenulus (Turner, 1910) (19 records)
Anoplius () elatus Smith, 1865 (31)

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
