### ISSUE TITLE
Flag an Issue on iNaturalist records

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#416]
@peggynewman commented on [Tue Sep 17 2019](https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/317)

As discussed, this may not be the right repo for this issue, but let's talk about it here anyway.

Raised via Support Desk ticket https://support.ehelp.edu.au/a/tickets/40495, but I saw it coming! 

When somebody wants to Flag an Issue for an iNaturalist record, there needs to be a way for that information to get back to the original iNaturalist record. 

Some options might be:

* Set the Data Resource contact on iNaturalist to be support@ala.org.au, and Freshdesk workflow can be that people on staff who have iNaturalist logins can go and update the record (myself, Taryn). Currently the contacts are Scott and Ken-ichi, but there is no email contact for them.

* Add something on the Data Resource or Record that tells users that they can go back to the original record in iNaturalist to make comments (the link is in the record)

* Have workflow that makes Flag an Issue behave differently for iNaturalist records, and sends the ALA human's message across to the iNaturalist record. See iNaturalist's API for details on what's possible. 

Other suggestions welcome, remembering that the records will be updated regularly so an ID is likely to change and our Flag an Issue function will have to not look silly as those changes occur (that's a technical term and it has to pass this in UAT).

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
