### ISSUE TITLE
String format of doubles %f generate wrong lat & lon

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/biocache-service#417]
We have detected some [wrong bbox calculation depending on locale here](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/19443624ffc01ca3443834140f836050bb9b0591/src/main/java/au/org/ala/biocache/web/WMSController.java#L1447) when selecting some species and some facet like family in spatial-hub. 

In some cases latitude & longitude are calculated with commas instead of periods in non English portals (like in Brasil and Spain) so solr queries complains.

```
ERROR (qtp1708570683-5564) [   x:biocache] o.a.s.h.RequestHandlerBase org.apache.solr.common.SolrException: Invalid Number: -35,661621 for field longitude
```

Here [some sample of url generated by spatial-hub](https://registros-ws.gbif.es/webportal/wms/reflect?OUTLINE=false&&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=ALA%3Aoccurrences&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&Q=qid%3A1573157566166&ENV=colormode%253Afamily%253Bname%253Acircle%253Bsize%253A5%253Bopacity%253A1%253Bsel%253Afamily%253A%2522Ginkgoaceae%2522&CONTINUOUSWORLD=true&SRS=EPSG%3A3857&UPPERCASE=false&BBOX=-2504688.5428486555,6261721.35712164,-1252344.2714243277,7514065.628545966).

In other parts of the code, does not suffer this issue, because doesn't use `%f`:
https://github.com/AtlasOfLivingAustralia/biocache-service/blob/19443624ffc01ca3443834140f836050bb9b0591/src/main/java/au/org/ala/biocache/web/WMSController.java#L982
Related: https://stackoverflow.com/questions/5236056/force-point-as-decimal-separator-in-java

Slack discussion with screenshots, etc:
https://atlaslivingaustralia.slack.com/archives/CCTFGEU1G/p1572631812108300

**Comment by djtfmartin** [comment]
This is fixed in 2.2.1. Thank you for the pull request @vjrj

**Comment by nickdos** [comment]
@djtfmartin have you QA'ed this issue? I'm not sure how to test it is OK in production so would appreciate if you could do some testing and then close this issue and move it to Done. Thanks.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
