### ISSUE TITLE
Query being matched to taxon when not asked to

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#418]
The following request is doing the wrong thing,  IMO...

https://biocache-ws.ala.org.au/ws/occurrences/search?q=alert&start=0&pageSize=1

```json
{
  "pageSize": 1,
  "startIndex": 0,
  "totalRecords": 0,
  "sort": "score",
  "dir": "asc",
  "status": "OK",
  "occurrences": [],
  "facetResults": [],
  "query": "?q=alert",
  "urlParameters": "?q=alert",
  "queryTitle": "<span class='lsid' id='NZOR-6-52809'>SPECIES: Decathelepus species NIWA Alert Stn 18</span>",
  "activeFacetMap": {}
}
```

Note the  `queryTitle` element.

In contrast I'd expect the results above for this request:

https://biocache-ws.ala.org.au/ws/occurrences/search?q=taxa:alert&start=0&pageSize=1

Note the `taxa` field specified.

If a raw `q` with no field is specified, then the default SOLR field of `text:` should be applied. 

Currently, the following search produces an unexpected and confusing result:

https://biocache.ala.org.au/occurrences/search?q=alert

> No records found for <span class='lsid' id='NZOR-6-52809'>SPECIES: Decathelepus species NIWA Alert Stn 18</span>

They didn't search for `<span class='lsid' id='NZOR-6-52809'>SPECIES: Decathelepus species NIWA Alert Stn 18</span>`, they searched for `alert`!

**Comment by alexhuang091** [comment]
Is it still an issue?

**Comment by nickdos** [comment]
Seems to be fixed with PIpelines changes - closing.
