### ISSUE TITLE
q=taxa:Aus bus not returning expected results

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#421]
Related to #418 but sslightly different.

https://biocache-ws.ala.org.au/ws/occurrences/search?q=taxa:"Xanthoparmelia+victoriana" (28215 results)
vs
https://biocache.ala.org.au/occurrences/search?taxa=Xanthoparmelia+victoriana (7 results)

It appears that the way biocache-service is implementing the `taxa` field search is different to the way `ala-hub` (`biocahce-hubs`) does it. The latter first queries `bie` web services and gets an LSID which it uses to search biocache with. The former is attempting to find a taxon but then failing back to a full-text search (service showing:  `queryTitle: "text:Xanthoparmelia victoriana",`).

Investigate why BIE is matching the name `Xanthoparmelia victorian` but biocache-service is not.

Related: I also noticed that https://biocache-ws.ala.org.au/ws/density/map?q=taxon_name:%22Xanthoparmelia+Victoriana%22 shows no records but https://biocache-ws.ala.org.au/ws/occurrences/search?q=taxon_name:%22Xanthoparmelia%20victoriana%22 returns the expected 7 records. This looks like a bug too.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
