### ISSUE TITLE
Make ScatterplotController.PAGE_SIZE configurable

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#423]
`ScatterplotController.PAGE_SIZE` is a static final variable hard configured to `100000000` which cannot currently be configured as necessary. This is a vulnerability as it allows all calls through `ScatterplotController` to be sent to Solr with that very large page size attached to them, which can easily DoS Solr with very small numbers of queries that would never be blocked by rate limiters (2 queries a minute managed it for the ALA today).

**Comment by ansell** [comment]
Even a single call to scatterplot can take out solr currently. Disabled scatterplot for ALA biocache-ws and biocache-ws-test using a fixed HTTP 503 response until the underlying scalability issues with scatterplots can be worked on.

**Comment by ansell** [comment]
Pushing to to "To Do" based on prioritisation discussion with @nickdos . Can move to "Emergency Fix" if that doesn't get it done in a reasonable amount of time. Lee wants Scatterplot functionality back as a priority.

**Comment by ansell** [comment]
This is the kibana visualisation of the query distribution from testing this with 50,000 and the SQLi request that was the key to disabling the service when this issue first came up. It shows one of the solr queries still at 85 seconds, with a total time of 89 seconds for the query to return:

![Screen Shot 2020-02-13 at 2 51 54 pm](https://user-images.githubusercontent.com/82365/74399969-ad5bce00-4e70-11ea-9ced-8b32326cdc91.png)

For those with Kibana access, the following is the source data for that:

https://kibana.ala.org.au/goto/e1b76896adecbf573b60d637cecb9bdb

Will cherry-pick this to a hotfix branch along with the i18n fixes and release a new biocache-service-2.2.x version with this change, as we aren't releasing biocache-service-2.4.x at this point.

**Comment by ansell** [comment]
Cherry-picked to 2.2.3-SNAPSHOT and deploying to biocache-ws-test

**Comment by sadeghim** [comment]
Tested, works fine.
