### ISSUE TITLE
WKT simplification algorithm with 20,000 limit simplifies a 22,600 polygon non-optimally

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#426]
The current ALA solr instances cannot process a 22,600 point WKT polygon in a reasonable time without interfering with service when `qid.wkt.maxpoints=50000` was configured. An attempt to solve this issue was made by configuring `qid.wkt.maxPoints=20000`, with the intent that the biocache-service WKT simplification algorithm would simplify the 22,600 points to a complexity that we could work on. This failed, as it ended up simplifying all the way down to about 8 points, which is unuseful as it doesn't describe the intentions of the user usefully.

The WKT simplification algorithm needs to be attempting more possibilities with larger numbers of points when simplifying complex polygons rather than reducing to 8 points.

The current implementation is at:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/util/SpatialUtils.java#L241-L272

The shapefile used for testing is at:

[vicalps_north.zip](https://github.com/AtlasOfLivingAustralia/biocache-service/files/4100535/vicalps_north.zip)

**Comment by ansell** [comment]
This has been deployed to biocache-ws-test and the script for someone else to QA it is at:

[qid-testing.zip](https://github.com/AtlasOfLivingAustralia/biocache-service/files/4105864/qid-testing.zip)

After unzipping, run `./test.sh` from the unzipped directory to run the test.

Expected output is similar to (note a time based parameter to avoid the QID cache, which may also have its own separate bugs):

```
qid-testing$ ./test.sh 
+ set -e
++ date +%s000
+ randomtestid=1579818497000
++ curl --data-urlencode wkt@simplify-wkt-input.wkt --data q=genus:Macropus1579818497000 https://biocache-ws-test.ala.org.au/ws/webportal/params
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  858k    0    13  100  858k     10   678k  0:00:01  0:00:01 --:--:--  678k
+ resultqid=1579818499134
+ rm -f result-qid-test.txt
+ curl https://biocache-ws-test.ala.org.au/ws/qid/1579818499134 -o result-qid-test.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95305    0 95305    0     0   709k      0 --:--:-- --:--:-- --:--:--  710k
++ tr -cd ,
++ wc -c
++ sed -e 's/^ *//g;s/ *$//g'
+ comma_count=2663
+ '[' 2663 -lt 1000 ']'
+ '[' 2663 -gt 20000 ']'
```

If `comma_count` is not around 2663 let me know and attach the output and the `result-qid-test.txt` file. Otherwise, the WKT simplification is working.

**Comment by djtfmartin** [comment]
Just ran that here

```
mar759@PEMBROKE-BM:  [~/Downloads/qid-testing] $ ./test.sh 
+ set -e
++ date +%s000
+ randomtestid=1579818870000
++ curl --data-urlencode wkt@simplify-wkt-input.wkt --data q=genus:Macropus1579818870000 https://biocache-ws-test.ala.org.au/ws/webportal/params
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  858k    0    13  100  858k      0  15940  0:00:55  0:00:55 --:--:--     0
+ resultqid=1579818925178
+ rm -f result-qid-test.txt
+ curl https://biocache-ws-test.ala.org.au/ws/qid/1579818925178 -o result-qid-test.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95305    0 95305    0     0  44629      0 --:--:--  0:00:02 --:--:-- 44639
++ tr -cd ,
++ wc -c
++ sed -e 's/^ *//g;s/ *$//g'
+ comma_count=2663
+ '[' 2663 -lt 1000 ']'
+ '[' 2663 -gt 20000 ']'
```

Same output.
