### ISSUE TITLE
Recent ALA Sighting records have missing `recordedBy` field

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#43]
More recent ALA sightings in biocache display with an `Observer` field of the ALA user ID (numeric) and lack a `recordedBy` field in the JSON output. E.g.

http://biocache.ala.org.au/occurrences/b963e1dd-5cf7-4a14-8335-38a709fbe746

In older records, this field shows the user's name and is indicated by text in the `recordedBy` field in the JSON output. E.g.

http://biocache.ala.org.au/occurrences/46a77fd8-1d27-49e4-a7db-2056ddf9e679

So this suggests there has been some change to AUTH or security somewhere that has resulted in this difference. 

References to auth.ala.org.au were recently updated in config file to use HTTPS, which fixed some related problems (like showing ALA user's name) but this issue is still outstanding.

**Comment by djtfmartin** [comment]
This a bug with ecodata/pigeonhole which is now using "userDisplayName" instead of recordedBy.

**Comment by djtfmartin** [comment]
This issue was moved to AtlasOfLivingAustralia/ecodata#87
