### ISSUE TITLE
incorrect activeFacetMap returned

### ISSUE THREAD

**Issue by hxuanyu** [AtlasOfLivingAustralia/biocache-service#434]
From ALA-hub you can construct your query in 2 ways:
`occurrences/search?q=*&fq=-month:"12"&fq=-month:"11"`
or 
`occurrences/search?q=*&fq=-(month:"12" OR month:"11")`

The first request gets below result which is incorrect as it shows only November is applied but actually both Dec and Nov are applied. I did some debug and the root cause seems to be, the fq is parsed into name and value at backend and stored into a map. In this case, both fq have the same name so the later over overwrites the first one.

```
    "activeFacetMap": {
        "-month": {
            "name": "-month",
            "displayName": "-Month:\"November\"",
            "value": "\"11\""
        }
    }
```
 
This is the result for the second request which is also incorrect. The name and value are from String.Split(":"). Name here is "-(month" which misses ')' and value being "\"12\" OR month:\"11\")" actually it should be "\"12\" OR \"11\""

```
  "activeFacetMap": {
        "-(month": {
            "name": "-(month",
            "displayName": "-(month:\"12\" OR Month:\"November\")",
            "value": "\"12\" OR month:\"11\")"
        }
    }
```

**Comment by alexhuang091** [comment]
No longer a problem with https://github.com/AtlasOfLivingAustralia/biocache-service/pull/441 merged.
