### ISSUE TITLE
Date management to allow ranges

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-service#44]
Date ranges are common in survey data e.g. a trap put out for week
incomplete dates (common in historical records) can be considered a date range e.g. 03-2015 can be interpreted as 01-03-2015/31-03-2015

Searching on date should include return records if any part of the date range is include in the target date/date range

e.g. 
a search on 15-03-2015 would return the record with a date 03-2015 or  01-03-2015/31-03-2015

a search on records between 01-01-2015 and 30-06-2015 would also return the record with a date 03-2015 or  01-03-2015/31-03-2015

**Comment by nickdos** [comment]
Dependent on https://github.com/AtlasOfLivingAustralia/biocache-store/issues/31

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-store/commit/820e81a651dd4c87ae181b8c08f14e42087ad110

**Comment by adam-collins** [comment]
Searching for occurrences between 01-01-2015 and 30-06-2015
http://biocache.ala.org.au/ws/occurrences/search?facet=off&pageSize=0&q=(occurrence_date:[*%20TO%202015-06-30T00:00:00Z]%20AND%20occurrence_date_end_dt:[2015-01-01T00:00:00Z%20TO%20*])%20OR%20(-occurrence_date_end_dt:*%20AND%20occurrence_date:[2015-01-01T00:00:00Z%20TO%202015-06-30T00:00:00Z])

Also need to check if all valid date ranges are parsed as ranges e.g. 03-2015 is parsed as 01-03-2015 to 31-03-2015.
