### ISSUE TITLE
errors occur when filter value has quotation mark

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#440]
Go to ala page (https://biocache.ala.org.au/search#tab_simpleSearch) do an occurrence search
Left side panel tells you there's one  ` "Cyclophora" lechriostropha (1)`
<img width="1527" alt="Screen Shot 2020-04-03 at 4 31 57 pm" src="https://user-images.githubusercontent.com/61677987/78328460-e8ee5b00-75ca-11ea-9ee4-c41558c877d2.png">

Click it you'll see `No records found for *:*`

<img width="817" alt="Screen Shot 2020-04-03 at 4 52 12 pm" src="https://user-images.githubusercontent.com/61677987/78328702-82b60800-75cb-11ea-88df-effd7fc3dd31.png">

Actually internally there's an error in the search.
<img width="1294" alt="Screen Shot 2020-04-03 at 4 49 39 pm" src="https://user-images.githubusercontent.com/61677987/78328557-2e128d00-75cb-11ea-8149-ffba0ffba9db.png">

The problem is in src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java line 846 - 860.
<img width="993" alt="Screen Shot 2020-04-03 at 4 51 02 pm" src="https://user-images.githubusercontent.com/61677987/78328622-55695a00-75cb-11ea-8371-0e7d01a98cee.png">

The expect formatted value is `'taxon_name:"\"Cyclophora\" lechriostropha"'`
but actually formatted value is `'taxon_name:"\"Cyclophora" lechriostropha"'`

This issue happens on other filter values as long as " appears in the middle.

**Comment by alexhuang091** [comment]
adam-collins is the author of this code fragment so he should be the proper person to fix it. I actually have no idea why we do all these at all.

**Comment by alexhuang091** [comment]
It's also wrong when I included 2 facets in a fq
<img width="1372" alt="Screen Shot 2020-05-18 at 1 42 58 pm" src="https://user-images.githubusercontent.com/61677987/82172480-9fa16300-990d-11ea-9c3c-ee99266a0072.png">

It returns 433 records but actually should be 2.

**Comment by nickdos** [comment]
@alexhuang091 FYI, I've re-opened this, until it is deployed to prod.
