### ISSUE TITLE
web-service: can't get multiple fields info in one query. 

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#448]
[https://biocache-ws.ala.org.au/ws/index/fields](https://biocache-ws.ala.org.au/ws/index/fields) is supposed to be used to get field info.

From the code it looks it can handle a ',' separated list of fields
<img width="898" alt="Screen Shot 2020-04-28 at 12 49 21 pm" src="https://user-images.githubusercontent.com/61677987/80441705-cbed4380-894e-11ea-82d7-71ebb07b6561.png">

<img width="822" alt="Screen Shot 2020-04-28 at 12 51 05 pm" src="https://user-images.githubusercontent.com/61677987/80441786-f7702e00-894e-11ea-94d8-e727365a2fe1.png">

But when call the WS with a ',' separated fields, only info of the first field is returned. (In below example, only 'occurrence_date_i' related info is returned)

<img width="653" alt="Screen Shot 2020-04-28 at 12 44 03 pm" src="https://user-images.githubusercontent.com/61677987/80441424-3ce02b80-894e-11ea-8c34-461b28d8cc5b.png">

**Comment by nickdos** [comment]
Not deployed - re-opening.

**Comment by nickdos** [comment]
Testing URL https://biocache-ws-test.ala.org.au/ws/index/fields?fl=occurrence_decade_i,month,year

**Comment by nickdos** [comment]
QA passed ✅
