### ISSUE TITLE
failed to search &fq=common_name:""Broad+water-milfoil""

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#453]
do a * search for occurrence records, left panel shows there are `"Broad water-milfoil" (428)` available.
<img width="363" alt="Screen Shot 2020-05-18 at 5 08 26 pm" src="https://user-images.githubusercontent.com/61677987/82184272-b99d6e80-992a-11ea-9de5-70751e70da84.png">

Click on it then you'll see no records found.

<img width="1047" alt="Screen Shot 2020-05-18 at 5 08 33 pm" src="https://user-images.githubusercontent.com/61677987/82184210-983c8280-992a-11ea-97f1-8bfd627a1a6b.png">

**Comment by alexhuang091** [comment]
when `&fq=common_name:""Broad+water-milfoil"" `

backend is able to extract `"Broad+water-milfoil"`, which is then sent to format query string.
Because it starts with " and end with ", the beginning and ending " don't get escaped, so the function returns "Broad+water-milfoil" which is sent to solr.

But actually what the solr needs is` \"Broad+water-milfoil\"`

<img width="974" alt="Screen Shot 2020-05-18 at 5 27 27 pm" src="https://user-images.githubusercontent.com/61677987/82185680-f5d1ce80-992c-11ea-9140-55965cd824b9.png">

**Comment by nickdos** [comment]
Seems to work as expected https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=*:*&fq=common_name:%22%22Broad+water-milfoil%22%22. - 428 results
