### ISSUE TITLE
incorrect search result &fq=(taxon_name:""Cyclophora" lechriostropha" OR taxon_name:""Cyclophora" rhodobapta")

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#454]
do a * occurrence search on ala, select 2 filters

<img width="590" alt="Screen Shot 2020-05-19 at 9 13 02 am" src="https://user-images.githubusercontent.com/61677987/82268647-e4330a00-99b2-11ea-8789-d5e2fbb7ceac.png">

the requested URL being https://biocache.ala.org.au/occurrences/search?q=*:*&fq=(taxon_name:""Cyclophora" lechriostropha" OR taxon_name:""Cyclophora" rhodobapta")

You'll see 433 records returned but the expected record number is 2.
<img width="948" alt="Screen Shot 2020-05-19 at 9 27 50 am" src="https://user-images.githubusercontent.com/61677987/82268757-1e041080-99b3-11ea-94fc-e0703f1c5121.png">

The root cause is, the fq contains an 'OR' so it's never processed by backend so the fq string `(taxon_name:""Cyclophora" lechriostropha" OR taxon_name:""Cyclophora" rhodobapta") ` is sent to solr directly.

<img width="1577" alt="Screen Shot 2020-05-19 at 9 13 50 am" src="https://user-images.githubusercontent.com/61677987/82268865-60c5e880-99b3-11ea-97b9-3a4b41d2fea1.png">

Actually what solr expects is this `(taxon_name:\"\\\"Cyclophora\\\" lechriostropha\" OR taxon_name:\"\\\"Cyclophora\\\" rhodobapta\"), with this sent to solr, the returned record number is 2.
`

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
