### ISSUE TITLE
update DOI minting to use DATACITE provider

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/biocache-service#455]

**Comment by brucehyslop** [comment]
need more information regarding this requirement.

**Comment by brucehyslop** [comment]
Will make the DOI provider configurable and default to `ALA`. 

The doi-service needs to be changed to route the `ALA` provider to it's configured default provider. This will prevent needing to make any changes to the biocache-service (or any other doi-service clients) if ALA's the default DOI provider is changed.

**Comment by Rita-C** [comment]
@brucehyslop , can this be tested or just be part of the integration test?

**Comment by Rita-C** [comment]
Verified downloaded file with minted DOI at doi-test.ala.org.au
