### ISSUE TITLE
Add doi.txt fil to download ZIP

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#456]
Requested by @matilda2812 - ALA4R needs to grab the DOI and currently the only way is to get it from the README file (brittle and not intended for API consumption).

- [x] create a new text file in the download dir (that gets put in zip file) called `doi.txt` that contains the DOI reference (e.g. `https://doi.org/10.26197/5ed8554ac1d5c`)

**Comment by brucehyslop** [comment]
I've added a new `doi.txt` to the download zip file containing the DOI reference. 

This file is only added if `mintDoi=true` as per [ALA4R issue 60](https://github.com/AtlasOfLivingAustralia/ALA4R/issues/60)
