### ISSUE TITLE
Facet search API pagination not working

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#47]
API described here: http://api.ala.org.au/#ws98

Example URL in API docs:

http://biocache.ala.org.au/ws/occurrence/facets?flimit=10&q=data_resource_uid:dr359&facets=taxon_name

Facet results should be able to be paginated via the `foffset` param. E.g. http://biocache.ala.org.au/ws/occurrence/facets?flimit=10&q=data_resource_uid:dr359&facets=taxon_name&foffset=10

but this gives the same result set as the first URL. I also tried using the param `startIndex` mentioned in the API docs but this gave the same result set also.

**Comment by nickdos** [comment]
`flimit` is also being ignored

**Comment by nickdos** [comment]
Looks like this never worked, as code does not specify `flimit` or `foffset`. 

See [SearchDAOImpl#getFacetCounts](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L2508).

Needs extra lines:
```
query.setFacetLimit(searchParams.getFlimit());
query.add("facet.offset", Integer.toString(searchParams.getFoffset()));
```
and possibly a few more for any other params specified in the API docs that are not implemented in code.

**Comment by djtfmartin** [comment]
I think this is a bug with the doco. I seem to remember Natasha saying this service would be more limited (limitations of SOLR) than the others for options. I'll have a look.

**Comment by adam-collins** [comment]
occurrence/facets is using grouping. Current docs seem to work, map flimit to rows and foffset to start, q=data_resource_uid:dr359&group=true&group.ngroups=true&group.limit=0&group.field=taxon_name&wt=json&rows=10&start=10. Sorting by count appears to be unavailable. Can sort by the field itself `&sort=taxon_name asc` but not sure it is possible to sort by count.

I think facets are used everywhere else, q=data_resource_uid:dr359&facet=true&facet.field=taxon_name&wt=json&rows=0&facet.mincount=1&facet.limit=10&facet.offset=10. Facets do not appear to be returning a total number of facets like grouping does.

I am inclined to change occurrence/facets to use faceting and add the missing count from a grouping query. It is probably going to be a bit slower but facet sorting will match usage elsewhere.

**Comment by adam-collins** [comment]
foffset and flimit are no longer ignored.
