### ISSUE TITLE
incorrect search result

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#490]
When using  `fq=year:[* TO 1970] duplicate_status:D geospatial_kosher:false outlier_layer_count:[3 TO *]` to do an occurrence search, the number of records returned is incorrect (4,605,164 vs 7,263,827 which is the correct number). It is a legal fq generated by Lucene BooleanQuery().build().toString().

Adding log into code you can see the fq eventually passed into solr is 
`fq = year:[* TO 1970] duplicate_status:D\ geospatial_kosher\:false\ outlier_layer_count\:\[3\ TO\ \*\]`.

The problem lies in the `QueryFormatUtils::formatString(String text, boolean isQuery)`. This function matches every xxx: appears in the fq and tries to extract the key/value.

When fq = `fq=year:[* TO 1970] duplicate_status:D geospatial_kosher:false outlier_layer_count:[3 TO *]`. 

- It can extract `year:[* TO 1970]` correctly 
-  then it finds `duplicate_status:` successfully. Then in line896, extractedValue = `"D geospatial_kosher:false outlier_layer_count:[3 TO *]"`, so far everthing is good.
- Next step we start to analyse extractedValue, it comes to line947

```
if (extractedValue.contains(" ") && end == 0) {
    extractedValue = extractedValue.substring(0, extractedValue.indexOf(' ') > 1 ? extractedValue.indexOf(' ') : extractedValue.length());
}
```

_extractedValue.indexOf(' ') > 1_ is problemtic here. In this case the value (D) is 1 char long so the indexOf(' ') == 1. _extractedValue.indexOf(' ') > 1_ is forcing the the value at least have 2 chars. So the whole string is extracted as the value of 
_'duplicate_status'_

**Comment by nickdos** [comment]
PR merged, so can someone please test this on test site and ensure it does what it says it should do.

**Comment by Rita-C** [comment]
Change is not on Test.

**Comment by ansell** [comment]
I am pushing it to test this afternoon. It was temporarily replaced on test with the hotfix release on Friday.

**Comment by Rita-C** [comment]
Test passed.
