### ISSUE TITLE
Add case insensitive filter to more endpoints

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#493]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/458

Had a change that was applied to `/ogc/*` paths but there are some legacy paths that also need this change, e.g. `/ws/mapping/wms/reflect`. There may be others as well so a check of paths in this controller is needed.

https://biocache-ws-test.ala.org.au/ws/ogc/wms/reflect?q=genus:Pogona&service=WMS&request=GetMap&layers=&styles=&format=image%2Fjpeg&transparent=false&version=1.1.1&LAYERS=ALA%3Aoccurrences&FORMAT=image%2Fpng&TRANSPARENT=true&ATTRIBUTION=Atlas%20of%20Living%20Australia&BGCOLOR=0x000000&OUTLINE=true&ENV=color%3A5574a6%3Bname%3Acircle%3Bsize%3A4%3Bopacity%3A1&width=256&height=256&srs=EPSG%3A3857&bbox=12523442.714243278,-5009377.085697311,15028131.257091936,-2504688.542848655

works but

https://biocache-ws-test.ala.org.au/ws/mapping/wms/reflect?q=genus:Pogona&service=WMS&request=GetMap&layers=&styles=&format=image%2Fjpeg&transparent=false&version=1.1.1&LAYERS=ALA%3Aoccurrences&FORMAT=image%2Fpng&TRANSPARENT=true&ATTRIBUTION=Atlas%20of%20Living%20Australia&BGCOLOR=0x000000&OUTLINE=true&ENV=color%3A5574a6%3Bname%3Acircle%3Bsize%3A4%3Bopacity%3A1&width=256&height=256&srs=EPSG%3A3857&bbox=12523442.714243278,-5009377.085697311,15028131.257091936,-2504688.542848655

fails

**Comment by brucehyslop** [comment]
We could enable the `CaseInsensitiveRequestFilter` to all paths. 

If there are multiple parameters (used for different purposes) with different cases this would cause an issue, otherwise I can't think of any downside.

**Comment by nickdos** [comment]
We could but because the this code base is so old, we need better automated tests to be confident nothing expects a certain "case". I also tested the filter with params in all uppercase and it threw an error, so not sure how it handling upper case params. So would prefer to be conservative.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
