### ISSUE TITLE
Fix hardcoded 1,000,000 page size for WMS uncertainty queries

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#495]
There is a hardcoded `1,000,000` page size that is active for WMS uncertainty queries. This has the ability to quickly crash Solr and must be configurable to fix this issue.

`https://github.com/AtlasOfLivingAustralia/biocache-service/blob/2c013e15d88350671ced5cabfe6781695d816fb9/src/main/java/au/org/ala/biocache/web/WMSController.java#L80`

`https://github.com/AtlasOfLivingAustralia/biocache-service/blob/2c013e15d88350671ced5cabfe6781695d816fb9/src/main/java/au/org/ala/biocache/web/WMSController.java#L1936`

**Comment by nickdos** [comment]
@ansell do you have any example queries we can use to test this fix (from the previous logs, etc.)?

**Comment by ansell** [comment]
This is an example that generates the uncertainty circles: 

`/ws/webportal/wms/reflect?OUTLINE=false&&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=ALA%3Aoccurrences&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&Q=qid%3A1605599572888&ENV=color%253ADC3912%253Bname%253Acircle%253Bsize%253A5%253Bopacity%253A1%253Buncertainty%253A1&CONTINUOUSWORLD=true&SRS=EPSG%3A3857&UPPERCASE=false&BBOX=16652265.234095357,-4246229.795298112,16671833.113336362,-4226661.916057105`
