### ISSUE TITLE
Remove deprecated MapController

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#496]
The `MapController` has been marked as `@deprecated` since at least 2014. It contains a Solr page size of `Integer.MAX_VALUE` which could crash Solr if it were ever used:

https://github.com/AtlasOfLivingAustralia/biocache-service/blame/2c013e15d88350671ced5cabfe6781695d816fb9/src/main/java/au/org/ala/biocache/web/MapController.java#L129

MapController should be removed, given its deprecation history, and anything using it should be switched to the `WMSController` functions.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
