### ISSUE TITLE
Use latest biocache-store version

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#497]
We should be using the latest biocache-store version to avoid bugs from reappearing for annotated records (including the User Assertion failure bug that was fixed in biocache-store but was not also fixed here: https://github.com/AtlasOfLivingAustralia/biocache-store/issues/317 )

**Comment by ansell** [comment]
Bumped in https://github.com/AtlasOfLivingAustralia/biocache-service/commit/4b40bb69db3c1054bde255e7770dba9582b49ab5

**Comment by Rita-C** [comment]
pom change is fine.
