### ISSUE TITLE
Create a link to /buildInfo on public HTML pages

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#498]
See https://github.com/AtlasOfLivingAustralia/biocache-service/issues/376

- [ ] To make it easier for people to find this info, it would be good to have a link to the `/ws/buildInfo` page on both the "home" page (`/ws) and old api page(`/ws/oldapi`)

**Comment by Rita-C** [comment]
Tested on` https://biocache-ws-test.ala.org.au/ws/oldapi` (a link to page below) and
`https://biocache-ws-test.ala.org.au/ws/buildInfo` (displays build info and Runtime Application Status)
