### ISSUE TITLE
(Test site) Offline downloads not sending emails

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#499]
I've tried a few downloads via UI and not got any emails (@ansell says he has got some which suggests emails are working). Example download:

https://biocache-ws-test.ala.org.au/ws/occurrences/offline/download?hubName=Atlas+of+Living+Australia&file=ala1-records-2020-08-04&mintDoi=true&reasonTypeId=10&searchUrl=https%3A%2F%2Fbiocache-test.ala.org.au%2Foccurrences%2Fsearch%3Fq%3Dacacia%26fq%3Dmultimedia%253A%2522Image%2522%26lat%3D-35.2649%26lon%3D149.2845%26radius%3D5.0&fileType=csv&qa=none&sourceTypeId=0&email=nick.dosremedios%40csiro.au&doiDisplayUrl=https%3A%2F%2Fbiocache-test.ala.org.au%2Fdownload%2Fdoi%3Fdoi%3D&q=acacia&fq=multimedia%3A%22Image%22&lat=-35.2649&lon=149.2845&radius=5.0

File downloads fine: https://doi-test.ala.org.au/doi/10.80416/TEST_DOI_5f28af4fe1f24

I see this error in logs:

> 2020-08-04 00:43:57,445 [biocachedownload-pool-200000-RECORDS_INDEX-0] ERROR au.org.ala.biocache.service.DownloadService  (DownloadService.java:998) - A null record was returned from the collectory citation service: [{name=BowerBird, citation=Records provided by BowerBird, accessed through ALA website., rights=Creative Commons - license at record level (Creative Commons - license at record level) The rights of material uploaded by users to the BowerBird website are owned by those users. Each user will nominate the type of license that can apply to their content - BowerBird encourages the Creative Commons License but users have the right to deny use of their content. Please respect the license wishes of the user's content.
> 
> For all other material, including the content, design and source code of BowerBird other than user-contributed material, is under the Open Source and Creative Commons licenses. You may use this material., link=For more information: https://collections-test.ala.org.au/public/show/dr893, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr893, DOI=}, {name=iNaturalist Australia, citation=iNaturalist.org: iNaturalist Research-grade Observations. doi:10.15468/ab3s5x
> Accessed via http://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7 on 2017-03-16, rights=CC-BY-NC-Int, link=For more information: https://collections-test.ala.org.au/public/show/dr1411, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr1411, DOI=}, {name=Citizen Science - ALA Website, citation=Records provided by Citizen Science - ALA Website, accessed through ALA website., rights=, link=For more information: https://collections-test.ala.org.au/public/show/dp31, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dp31, DOI=}, null, {name=ALA species sightings and OzAtlas, citation=Survey name: Atlas of Living Australia (2020) Survey name dataset
> Individual sighting: Atlas of Living Australia (2020) Individual sighting dataset
> Test survey: Atlas of Living Australia (2020) Test survey dataset
> , rights=CC-BY, link=For more information: https://collections-test.ala.org.au/public/show/dr364, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr364, DOI=10.15468/jayxmn}, {name=NatureMapr, citation=Records provided by NatureMapr, accessed through ALA website., rights=, link=For more information: https://collections-test.ala.org.au/public/show/dp3301, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dp3301, DOI=}, {name=Canberra Nature Map, citation=Canberra Nature Map http://canberranaturemap.org Content from this website should be attributed as:
> 
> Canberra Nature Map (<current year>, accessed <date of access>), rights=CC-BY, link=For more information: https://collections-test.ala.org.au/public/show/dr1947, dataGeneralizations=, informationWithheld=The data supplied by Canberra Nature Map to the ALA is a subset of data containing non-sensitive sightings suitable for public access via the ALA. If the ALA provides a sensitive data service that provides suitable restrictions, CNM may choose to provide further data that will be processed by this service before being made available for public access., downloadLimit=, uid=dr1947, DOI=10.15468/uv6p4z}, null], collected stats were: {dr893=5, dr1411=6, dp31=1, infoHeaders,Record ID,Data Resource ID,Data Resource Name,Institution ID,Institution,Collection ID,Collection,Licence,Catalogue Number,Taxon Concept GUID,Scientific Name - original,Vernacular name - original,Scientific Name,Taxon Rank,Vernacular name,Kingdom,Phylum,Class,Order,Family,Genus,Species,Subspecies,Institution Code,Collection Code,Locality,Latitude - original,Longitude - original,Geodetic datum - original,Latitude,Longitude,Coordinate Precision,Coordinate Uncertainty in Metres,Country - parsed,State - parsed,Local Government Areas 2011,IMCRA 4 Regions,IBRA 7 Regions,Minimum elevation in meters,Maximum elevation in meters,Minimum depth in meters,Maximum depth in meters,Individual count,Collector,Event Date - parsed,Year,Month,Day,Verbatim event date,Basis Of Record,Basis Of Record - original,Occurrence status,Sex,Preparations,Outlier for layer,Taxonomic Quality,Location Quality=-2, dr364=1, dp3301=18, dr1947=18, infoFields,id,data_resource_uid,data_resource,institution_uid,institution_name,collection_uid,collection_name,license,catalogue_number,taxon_concept_lsid,raw_taxon_name,raw_common_name,taxon_name,rank,common_name,kingdom,phylum,class,order,family,genus,species,subspecies,institution_code,collection_code,raw_locality,raw_latitude,raw_longitude,raw_datum,latitude,longitude,coordinate_precision,coordinate_uncertainty,country,state,cl959,cl21,cl1048,min_elevation_d,max_elevation_d,min_depth_d,max_depth_d,individual_count,collector,occurrence_date,year,month,day,verbatim_event_date,basis_of_record,raw_basis_of_record,occurrence_status,raw_sex,preparations,outlier_layer,taxonomic_kosher,geospatial_kosher=-1}

**Comment by ansell** [comment]
The collections "null record" error has been around for quite a while. It may need to be fixed, but it doesn't directly affect whether emails are sent.

**Comment by nickdos** [comment]
Found emails in my trash 😬
