### ISSUE TITLE
Error in log for DownloadService:998 null record from collectory

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#500]
`au.org.ala.biocache.service.DownloadService  (DownloadService.java:998) - A null record was returned from the collectory citation service`

I see this error in logs:

> 2020-08-04 00:43:57,445 [biocachedownload-pool-200000-RECORDS_INDEX-0] ERROR au.org.ala.biocache.service.DownloadService  (DownloadService.java:998) - A null record was returned from the collectory citation service: [{name=BowerBird, citation=Records provided by BowerBird, accessed through ALA website., rights=Creative Commons - license at record level (Creative Commons - license at record level) The rights of material uploaded by users to the BowerBird website are owned by those users. Each user will nominate the type of license that can apply to their content - BowerBird encourages the Creative Commons License but users have the right to deny use of their content. Please respect the license wishes of the user's content.
> 
> For all other material, including the content, design and source code of BowerBird other than user-contributed material, is under the Open Source and Creative Commons licenses. You may use this material., link=For more information: https://collections-test.ala.org.au/public/show/dr893, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr893, DOI=}, {name=iNaturalist Australia, citation=iNaturalist.org: iNaturalist Research-grade Observations. doi:10.15468/ab3s5x
> Accessed via http://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7 on 2017-03-16, rights=CC-BY-NC-Int, link=For more information: https://collections-test.ala.org.au/public/show/dr1411, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr1411, DOI=}, {name=Citizen Science - ALA Website, citation=Records provided by Citizen Science - ALA Website, accessed through ALA website., rights=, link=For more information: https://collections-test.ala.org.au/public/show/dp31, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dp31, DOI=}, null, {name=ALA species sightings and OzAtlas, citation=Survey name: Atlas of Living Australia (2020) Survey name dataset
> Individual sighting: Atlas of Living Australia (2020) Individual sighting dataset
> Test survey: Atlas of Living Australia (2020) Test survey dataset
> , rights=CC-BY, link=For more information: https://collections-test.ala.org.au/public/show/dr364, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr364, DOI=10.15468/jayxmn}, {name=NatureMapr, citation=Records provided by NatureMapr, accessed through ALA website., rights=, link=For more information: https://collections-test.ala.org.au/public/show/dp3301, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dp3301, DOI=}, {name=Canberra Nature Map, citation=Canberra Nature Map http://canberranaturemap.org Content from this website should be attributed as:
> 
> Canberra Nature Map (<current year>, accessed <date of access>), rights=CC-BY, link=For more information: https://collections-test.ala.org.au/public/show/dr1947, dataGeneralizations=, informationWithheld=The data supplied by Canberra Nature Map to the ALA is a subset of data containing non-sensitive sightings suitable for public access via the ALA. If the ALA provides a sensitive data service that provides suitable restrictions, CNM may choose to provide further data that will be processed by this service before being made available for public access., downloadLimit=, uid=dr1947, DOI=10.15468/uv6p4z}, null], collected stats were: {dr893=5, dr1411=6, dp31=1, infoHeaders,Record ID,Data Resource ID,Data Resource Name,Institution ID,Institution,Collection ID,Collection,Licence,Catalogue Number,Taxon Concept GUID,Scientific Name - original,Vernacular name - original,Scientific Name,Taxon Rank,Vernacular name,Kingdom,Phylum,Class,Order,Family,Genus,Species,Subspecies,Institution Code,Collection Code,Locality,Latitude - original,Longitude - original,Geodetic datum - original,Latitude,Longitude,Coordinate Precision,Coordinate Uncertainty in Metres,Country - parsed,State - parsed,Local Government Areas 2011,IMCRA 4 Regions,IBRA 7 Regions,Minimum elevation in meters,Maximum elevation in meters,Minimum depth in meters,Maximum depth in meters,Individual count,Collector,Event Date - parsed,Year,Month,Day,Verbatim event date,Basis Of Record,Basis Of Record - original,Occurrence status,Sex,Preparations,Outlier for layer,Taxonomic Quality,Location Quality=-2, dr364=1, dp3301=18, dr1947=18, infoFields,id,data_resource_uid,data_resource,institution_uid,institution_name,collection_uid,collection_name,license,catalogue_number,taxon_concept_lsid,raw_taxon_name,raw_common_name,taxon_name,rank,common_name,kingdom,phylum,class,order,family,genus,species,subspecies,institution_code,collection_code,raw_locality,raw_latitude,raw_longitude,raw_datum,latitude,longitude,coordinate_precision,coordinate_uncertainty,country,state,cl959,cl21,cl1048,min_elevation_d,max_elevation_d,min_depth_d,max_depth_d,individual_count,collector,occurrence_date,year,month,day,verbatim_event_date,basis_of_record,raw_basis_of_record,occurrence_status,raw_sex,preparations,outlier_layer,taxonomic_kosher,geospatial_kosher=-1}

**Comment by alexhuang091** [comment]
**code has changed after the pipeline project (from develop), but they have same issue**

the error is printed by

```
List<LinkedHashMap<String, Object>> entities = restTemplate.postForObject(citationServiceUrl,
                            uidStats.keySet(), List.class);
    for (Map<String, Object> record : entities) {
        if (record != null) {
            // xxx
        } else {
            if (logger.isDebugEnabled()) {
                logger.error("A null record was returned from the collectory citation service: " + entities + ", collected stats were: " + uidStats);
            } else {
                 logger.error("A null record was returned from the collectory citation service.");
            }
        }
```

a map object is posted to `https://collections-test.ala.org.au/ws/citations`

![1](https://user-images.githubusercontent.com/61677987/128120381-6caeeeca-f5a7-46f4-ac82-6d47ec2de1d4.jpg)

**The 1st, 6th items in the map yield null**

In pipeline they are added via
```
uidStats.put("infoFields," + StringUtils.join(downloadHeaders.joinOriginalIncluded(), ","), new AtomicInteger(-1));
uidStats.put("infoHeaders," + StringUtils.join(downloadHeaders.joinedHeader(), ","), new AtomicInteger(-2));
```

In previous `develop` branch they are added via
![2](https://user-images.githubusercontent.com/61677987/128120632-0bf1ae8b-b3cd-49a9-88d4-169fbb318c2a.jpg)

These 2 are used to generate headings in header.csv.
They shouldn't be posted to get the citation I think.

**Comment by alexhuang091** [comment]
From the original log provided by Nick we can see `uidStatus` has `infoHeaders,Record ID,Data Resource ID,Data Resource Name,Institution ID,Institution,Collection ID,Collection,Licence` and `infoFields,id,data_resource_uid,data_resource,institution_uid,institution_name,collection_uid,collection_name,license,catalogue_number,taxon_concept_lsid` and the `entities` had 2 `null` at corresponding position.

**Comment by brucehyslop** [comment]
The issue is the `uidStats` has been used to store the download `infoFields` and `infoHeaders` that is used to generate the `headers.csv`. This data is filtered out of the `uidStats` using hardcoded map values (-1 & -2) 
https://github.com/AtlasOfLivingAustralia/biocache-service/blob/a36efd87899982207b645bf71c3a5f5e941bf711/src/main/java/au/org/ala/biocache/service/DownloadService.java#L980-L989

It appears the intent is to store stats about UID's (hence the variable name) to generate the `citation.csv`. 

See incrementing of UID data when processing the download. 
https://github.com/AtlasOfLivingAustralia/biocache-service/blob/a36efd87899982207b645bf71c3a5f5e941bf711/src/main/java/au/org/ala/biocache/stream/ProcessDownload.java#L149-L153

---
The solution could be:

1. filter out `uidStats` keys with negative values before retrieving citations.
2. refactor the code to replace `ConcurrentMap uidStats`with a DTO that encapsulates `uidStats`, `infoFields` and `infoHeaders`.

**Comment by brucehyslop** [comment]
I've tested the issue on `nci3-biocache-service` not all download are returning the error `A null record was returned from the collectory`, however some downloads still returning the error when a citation uid does not exist in the collectory. 

In the case below the `dr15870` returns null. 
```
2021-11-04 15:13:10,109 [biocachedownload-pool-500000-RECORDS_INDEX-1] ERROR au.org.ala.biocache.service.DownloadService  (DownloadService.java:927) - A null record was returned from the collectory citation service: [
    {name=Australia's Virtual Herbarium, citation=Records provided by Australia's Virtual Herbarium, accessed through ALA website., rights={}, link=For more information: https://collections-test.ala.org.au/public/show/dp36, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dp36, DOI=}, 
    {name=NSW AVH data, citation=Records provided by NSW AVH data, accessed through ALA website., rights=Creative Commons Attribution (International) (CC-BY 4.0 (Int)) This work is licensed under a Creative Commons Attribution (CC-BY) 4.0 License., link=For more information: https://collections-test.ala.org.au/public/show/dr15861, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr15861, DOI=10.15468/jf3yae}, 
    {name=The University of Melbourne Herbarium, citation=Records provided by The University of Melbourne Herbarium, accessed through ALA website., rights={}, link=For more information: https://collections-test.ala.org.au/public/show/co64, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=co64, DOI=}, 
    {name=James Cook University Herbarium, citation=Records provided by James Cook University Herbarium, accessed through ALA website., rights={}, link=For more information: https://collections-test.ala.org.au/public/show/co31, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=co31, DOI=},
    {name=National Herbarium of New South Wales, citation=Records provided by National Herbarium of New South Wales, accessed through ALA website., rights={}, link=For more information: https://collections-test.ala.org.au/public/show/co54, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=co54, DOI=}, 
    {name=N.C.W. Beadle Herbarium, citation=Records provided by N.C.W. Beadle Herbarium, accessed through ALA website., rights={}, link=For more information: https://collections-test.ala.org.au/public/show/co65, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=co65, DOI=}, 
    {name=Encyclopedia of Life Images - Flickr Group, citation=Citation is at the individual image, rights=Creative Commons - license at record level (Creative Commons - license at record level), link=For more information: https://collections-test.ala.org.au/public/show/dr360, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr360, DOI=}, 
    {name=ABRS Flora of Australia Online, citation=Flora of Australia Online (http://www.environment.gov.au/biodiversity/abrs/online-resources/flora/main/). © Commonwealth of Australia 2016, rights=CC-BY-Int, link=For more information: https://collections-test.ala.org.au/public/show/dr382, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr382, DOI=doi:10.15468/fbr7fh}, 
    {name=JCT AVH data, citation=Records provided by JCT AVH data, accessed through ALA website., rights=This work is licensed under a Creative Commons Attribution (CC-BY) 4.0 License., link=For more information: https://collections-test.ala.org.au/public/show/dr15868, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr15868, DOI=10.15468/mzbw85}, 
    {name=James Cook University, citation=Records provided by James Cook University, accessed through ALA website., rights={}, link=For more information: https://collections-test.ala.org.au/public/show/in40, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=in40, DOI=}, 
    {name=The Royal Botanic Gardens & Domain Trust, citation=Records provided by The Royal Botanic Gardens & Domain Trust, accessed through ALA website., rights={}, link=For more information: https://collections-test.ala.org.au/public/show/in50, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=in50, DOI=}, 
    {name=University of New England, citation=Records provided by University of New England, accessed through ALA website., rights={}, link=For more information: https://collections-test.ala.org.au/public/show/in65, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=in65, DOI=}, 
    {name=The University of Melbourne, citation=Records provided by The University of Melbourne, accessed through ALA website., rights={}, link=For more information: https://collections-test.ala.org.au/public/show/in26, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=in26, DOI=}, 
    null, 
    {name=NE AVH data, citation=Records provided by NE AVH data, accessed through ALA website., rights=This work is licensed under a Creative Commons Attribution (CC-BY) 4.0 License., link=For more information: https://collections-test.ala.org.au/public/show/dr15870, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr15870, DOI=10.15468/7t5ghf}, 
    {name=Flickr, citation=Records provided by Flickr, accessed through ALA website., rights={}, link=For more information: https://collections-test.ala.org.au/public/show/dp29, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dp29, DOI=}, 
    {name=Australian Plant Image Index, citation=How to cite the APII is given at: http://www.anbg.gov.au/citation.html For further information, contact the APII Photograph Curator., rights=Creative Commons Attribution (Australia) (CC-BY 3.0 (Au)), link=For more information: https://collections-test.ala.org.au/public/show/dr413, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr413, DOI=}, 
    {name=MELU AVH data, citation=Records provided by MELU AVH data, accessed through ALA website., rights=Creative Commons Attribution (International) (CC-BY 4.0 (Int)) This work is licensed under a Creative Commons Attribution (CC-BY) 4.0 License., link=For more information: https://collections-test.ala.org.au/public/show/dr13282, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr13282, DOI=https://doi.org/10.15468/2yyu7i}, 
    {name=CSIRO, South East Fishery Habitat Ecosystem Study, Southeast Australia, 1993-1997, citation=CSIRO - SE Fishery habitat & ecosystem study 1993-1996, rights=This work is licensed under a Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0 License., link=For more information: https://collections-test.ala.org.au/public/show/dr17694, dataGeneralizations=, informationWithheld=, downloadLimit=, uid=dr17694, DOI=}
], collected stats were: {
    dp36=10, 
    dr15861=5, 
    co64=2, 
    co31=1, 
    co54=5, 
    co65=2, 
    dr360=7, 
    dr382=1, 
    dr15868=1, 
    in40=1, 
    in50=5, 
    in65=2, 
    in26=2, 
    dp5190=1, 
    dr15870=2, 
    dp29=7, 
    dr413=40, 
    dr13282=2, 
    dr17694=1
}
```

**Comment by adam-collins** [comment]
appears fixed
