### ISSUE TITLE
occurrence search failed on fq=month:03" month:"04"

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#502]
In issue https://github.com/AtlasOfLivingAustralia/biocache-service/issues/440 I fixed a bug where when `&fq=taxon_name%3A""Cyclophora"+lechriostropha"` no records is returned.

It failed because the legacy code searches un-escaped " (indicating the end of query term) from left to right. If query term itself has an un-escaped ", search stops there in the middle of query term. Thus the query sent to solr is incorrect.

The change I've made is: search from right, so the first un-escaped must be the ending " for the whole query term. This solves the issue.

But later I found my fix doesn't work on this fq: `fq=month:"03" month:"04"`. It's a valid fq, queries for those with month March or April. Legacy code can handle it correctly, but my change not. If search from right, it stops at 04", the whole `03" month:"04` will be treated as a query term and thus sent to solr.

- One possible solution is always escaping " when query term contains it. So un-escaped " marks the start/end of query term.

- One solution is we can parse every key:value correctly and process them individually. 

This is the full conversation with Nick [biocache-service issue 440.pdf](https://github.com/AtlasOfLivingAustralia/biocache-service/files/5032138/biocache-service.issue.440.pdf)

**Comment by adam-collins** [comment]
My suggestion is that any q or fq sent to biocache-service is ready for use in SOLR without additional processing. It is necessary to be aware that there are existing exceptions for fields not in SOLR such as qid, taxa, matched_name, lsid, species_list, etc. 

Therefore all encoding and escaping must be done before a request is sent to biocache-service.

This makes it clear that the fq inserted by biocache-service facet responses is not appropriately escaped. Fixing this should also work as a solution to 440. 
- note that the `facetResults.fieldResult .fq` is not correctly escaped https://biocache.ala.org.au/ws/occurrences/search?q=taxon_name%3A%22%22Cyclophora%22+lechriostropha%22&facet=true&facets=taxon_name&pageSize=0
- relevant code that does not escape the value https://github.com/AtlasOfLivingAustralia/biocache-service/blob/cb880f014545ad0506975860b639ca9b202a6806/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L4236

**Comment by alexhuang091** [comment]
Just a suggestion, maybe here we can add a judge. If it's a complex query (contains more than 1 key:value pairs) so we don't format it. But we still need to translate it (format display string). The translation may also have issues with current implementation. 

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/02c3bfeccd6ca26f081cef329a6d229685cc22a6/src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java#L848-L853

**Comment by alexhuang091** [comment]
Hi, I checked out this branch 544fd3895fdb5cf48d732d13cf41104027606c57 onto my local machine and it doesn't work.

When I sent ?q=*&fq=month:"03" I got 6117092 records back. The fq sent to solr is `fq = month:"04"` 
When I sent ?q=*&fq=month:"04" I got 5928101 records back. The fq sent to solr is `fq = month:"03"`
When I sent ?q=*&fq=month:"03" month:"04" I got 0 records back. The fq sent to slor is `fq = month:"03\"\ month\:\"04"`

When I sent ?q=*&fq=month:04 month:03 I got the correct number which is 12045193. The fq sent to solr is` fq = month:03 month:04`

**Comment by brucehyslop** [comment]
Added code to terminate processing of quoted term values when the next term is encountered. 

Also escaped the `facetResults.fieldResult .fq` results. 

When the facet result is escaped then the escaping is displayed in the `biocache-hub` 
<img width="419" alt="Screen Shot 2020-09-11 at 4 35 46 pm" src="https://user-images.githubusercontent.com/12233783/92875902-dbc47a80-f44c-11ea-89b3-c29e1805a4d0.png">

see: PR #525

**Comment by nickdos** [comment]
I'm ok with the display of `\"` in ala-hub output.

**Comment by nickdos** [comment]
Testing functionality.

- #440 is working as expected 
- I note that the biocache - UI selecting month facets produces `&fq=(month%3A"04" OR month%3A"05")`
- testing `&fq=month%3A"04" month%3A"05"` returns the same number as result as `&fq=(month%3A"04" OR month%3A"05")`

So I'm happy this is fixed ✅
