### ISSUE TITLE
How can a subgroup have more records than a group?

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#51]
_From @aruizca on June 16, 2015 3:22_

Can any of you @nickdos or @djtfmartin help me to find out why the following is happening: 
In the bug report that I fixed today the user gave us the following url: http://regions.ala.org.au/Major%20drainage%20divisions/DARLING%2520RIVER#group=Crustaceans&subgroup=&from=1850&to=2015&tab=speciesTab with a total of 861 records. How come if you select the next subgroup "Fairy shrimp, Clam shrimp" we get 964 records -> http://regions.ala.org.au/Major%20drainage%20divisions/DARLING%2520RIVER#group=Crustaceans&subgroup=Fairy+shrimp,+Clam+shrimp&from=1850&to=2015&tab=speciesTab

* In the first instance the following URL generated and executed: http://biocache.ala.org.au/ws/occurrences/search?q=cl1059%3A%22DARLING+RIVER%22&facets=names_and_lsid&fsort=taxon_name&pageSize=0&flimit=50&foffset=0&fq=rank%3A%28species+OR+subspecies%29+AND+species_group%3A%22Crustaceans%22

* When subgroup is selected the following URL is generated: http://biocache.ala.org.au/ws/occurrences/search?q=cl1059%3A%22DARLING+RIVER%22&facets=names_and_lsid&fsort=taxon_name&pageSize=0&flimit=50&foffset=0&fq=rank%3A%28species+OR+subspecies%29+AND+species_subgroup%3A%22Fairy+shrimp%2C+Clam+shrimp%22

_Copied from original issue: AtlasOfLivingAustralia/regions#46_

**Comment by nickdos** [comment]
_From @djtfmartin on June 16, 2015 7:46_

Im guessing this is a bug with the subgroups config.

**Comment by nickdos** [comment]
This is a duplicate issue of https://github.com/AtlasOfLivingAustralia/biocache-service/issues/46

This has been happening for a while so is not related to the new `subgroups.json` that was deployed yesterday.

**Comment by nickdos** [comment]
Not sure this is a strict duplicate but definitely related... Re-opening issue so this is tested for, specifically.

**Comment by nickdos** [comment]
More info:

There is a problem here - we are missing a bunch of records that should have "lifeform: reptiles" but don't get that attribute added when indexed, it seems. 

This can bees seen with this search:

http://biocache.ala.org.au/occurrences/search?taxa=Common+Brown+Snake

which returns 5672 records but the "taxon -> Lifeform: Reptiles" facet only shows 3919 records. Leaving 1753 records not being included as reptiles in the "species_group" facet.

**Comment by charvolant** [comment]
With the http://biocache.ala.org.au/occurrences/search?taxa=Common+Brown+Snake query, all non Lifeform: Reptile records have no matched vernacular name, even though they may have supplied vernacular names. Same as https://github.com/AtlasOfLivingAustralia/biocache-service/issues/46

Data resources for records with the correct lifeform attribution: dr340, dr343, dr346, dr348, dr361, dr365, dr368, dr415, dr419, dr457, dr661, dr695, dr732, dr746, dr1057, dr1097

Data resources for records without the lifeform attribution: dr340, dr341, dr342, dr344, dr360, dr364, dr635, dr893, dr1411, dr1902, dr2008

The only overlap is dr340 - Australian Museum provider for OZCAM, which has 994 correct records and 9 incorrect records

**Comment by charvolant** [comment]
http://biocache.ala.org.au/occurrences/cfa5746a-e02c-482f-94e5-81cd76bd8f89 is one of the non-reptiles. The download doesn't contain a matched vernacular name but the actual web page does. The original-processed table shows the correct supplied vernacular name but no matched name. This has a date loaded/procesed of 2015-06-30, today.

Similar example http://biocache.ala.org.au/occurrences/8750d0f7-a3bf-4b73-9804-f5616844c2e6 with a loaded/processed date of 2015-06-02

http://biocache.ala.org.au/occurrences/c67a9c1d-bbc8-4e0e-8ad9-a1b08cbc4531 is a recognised reptile. In this case, the vernacular name matches. Date loaded/processed is 2014-05-14/2014-09-27

Similar example http://biocache.ala.org.au/occurrences/c4f097d2-92e3-486c-a4db-c26eb28fd0db date loaded/processed 2014-05-23/2014-12-02

For the dud records in dr340 we have 

http://biocache.ala.org.au/occurrences/58e6e99b-0bec-4cb0-a825-0ea867081209
http://biocache.ala.org.au/occurrences/665edf80-2109-4711-98cb-b7cba6378815
http://biocache.ala.org.au/occurrences/cd7c8372-0d06-4981-b113-3cdd15d1bc07
http://biocache.ala.org.au/occurrences/f9abe610-d27b-4912-88a3-7848453dabe9
http://biocache.ala.org.au/occurrences/b6f2abd6-3525-4f06-a24f-393424c60e81
http://biocache.ala.org.au/occurrences/c9e775ce-9e5a-4a6f-a424-ba12eba5df84
http://biocache.ala.org.au/occurrences/5dc4d424-7275-49f5-8f66-914450bbbc6e
http://biocache.ala.org.au/occurrences/15b1c253-2519-4670-969b-02c458e1dc9c
http://biocache.ala.org.au/occurrences/269a3a4e-e41d-4873-bd39-a4a5e0581a5e

All loaded/processed on 2015-06-28

A sample of correct records for dr340 shows dates in 2014. (How is that possible for a single dataset; isn't it processed in toto?)

**Comment by charvolant** [comment]
A sampling of incorrect records show the earliest processing date to be 2015-05-29.

**Comment by charvolant** [comment]
See https://github.com/AtlasOfLivingAustralia/biocache-store/commit/cb8475914f38f92f13de5cd84b63af832061fdfe

ClassificationProcessor.scala:179

Transfer of common name removed

**Comment by charvolant** [comment]
See https://github.com/AtlasOfLivingAustralia/biocache-store/commit/1189026e00372bfb50a047a5e7222c0b3bb78a64 ClassificationProcessor.scala:189

Species group retrieval removed.

Subgroups are indexed by processing left and right values in SolrIndexDAO.scala So species_subgroup still gets indexed. From the look of it, the species_group value comes from the originally processed map that gets supplied to the index DAO.

Querying to see whether the code has simply been moved elsewhere.

**Comment by djtfmartin** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-store#61
