### ISSUE TITLE
Deduplicate fq params before sending them to Solr

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#512]
It would be useful, for debugging if not functionality, to deduplicate the fq params before sending them into Solr:

[Massive-solr-query-20200820.txt](https://github.com/AtlasOfLivingAustralia/biocache-service/files/5101277/Massive-solr-query-20200820.txt)

**Comment by ansell** [comment]
This is happening again currently: 
[Uploading 20201201-biocache-repeated-terms-query.txt…]()

**Comment by adam-collins** [comment]
pull request https://github.com/AtlasOfLivingAustralia/biocache-service/pull/863

**Comment by peggynewman** [comment]
Regression testing should have this covered well enough, also code reviews.
