### ISSUE TITLE
Hotfix: Configurably disable occurrence record log event submission

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#513]
Our logger system is not handling the load well since we fixed occurrence record log event submission. It would be very useful to be able to configurably turn off this (while leaving offline download log event submission active):

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/4bbf3a99ca182b2da28714809340e17b9a419230/src/main/java/au/org/ala/biocache/web/OccurrenceController.java#L1566

**Comment by djtfmartin** [comment]
Seems to be done. Please reopen if not.
