### ISSUE TITLE
Download CSV file - fix duplicate column heading values

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#518]
Reported by @timhicks-ala:

> Columns CZ and DA in a full DwC download are titled the exact same thing (scientificName), I believe CZ is the original unprocessed data and DA is the processed scientific name (in an ALA legacy download, where scientificName fields are paired, the first one is scientificName - original). I think this would be a quick ticket to either rename column CZ to append " - original" or to remove it?

- [ ] the 2 instances of `scientificName` header should be renamed to `scientificName - original` and `scientificName - processed`, respectively (assuming those labels are correct)

**Comment by Tasilee** [comment]
With the "Full Darwin Core" download format, we need to be careful to map what we believe are the best matches to the Darwin Core terms. In this case, the only term available is dwc:scientificName, defined as "The full scientific name, with authorship and date information if known. When forming part of an Identification, this should be the name in lowest level taxonomic rank that can be determined..." There is no verbatim equivalent. 

**It is debatable therefore how we should deal with cases that extend beyond Darwin Core (sensu stricto).** 

When I do opt for the "Full Darwin Core" download, my reasoning is that this is the standard that I need to use to best evaluate records.  What I probably also (incorrectly) assume, is that no information should be lost. It seems I can't have both unless terms like "ala:scientificNameOriginal" (rendered in dwc phrasing :) are included. 

My conclusion is therefore to be explicit: Use the best match to an EXACT Darwin Core terms as in "scientificName" and make it obvious where corresponding Darwin Core terms are not available?

**Comment by nickdos** [comment]
@Tasilee, I agree and have been trying to push something similar - an `ala:` namespace for terms that are not strictly DwC. With the GBIF pipelines work, we effectively get some terms like this because GBIF already adds a `gbif:` namespace onto a handful of extra terms.

The issue above is due to us processing the provided scientific name. Verbatim terms are quite different, as they relate to the data custodian collecting a value and then changing it themselves (e.g. lat/lng collected as DMS and then converted to decimal degrees), which is different to aggregators changing a value (raw vs processed). DwC has no terms to distinguish raw vs processed. So the record can come to the ALA with a `scientificName` value and then we compare that with our taxonomy and often map it to a different name (e.g. the accepted has changed over time), because ~many~ most datasets never update their taxonomy. 

I think it's fine to provide both versions of `scientificName` because:
Most users don't (really) understand taxonomy and expect the downloads to show the same values they see when they search - most searches are via an accepted scientific name from the ALA taxonomy (often coming via our species pages which get the most hits on our site). E.g. user searches for "red kangaroo" which resolves to  _Osphranter rufus_ (species page) and then they do a download and see most of the records say _Macropus rufus_ - they would then say "Hey ALA your downloads are broken as I'm getting records for species I didn't ask for" (not realising that the accepted name was changed in 2018).

I'd like to see the column headings contain a URI that links to the definition of the term, so a user can click on the `ala:scientificName` URI and get a web page that explains the difference to the `dwc:scientificName` version. At the moment, this is hard to communicate as just a "string" field heading. There is the `headings.csv` file in the download but a lot of users don't seem to ever look at it. This would also resolve the confusion you raised about "Use the best match to an EXACT Darwin Core" as we can show that dwc:scientificName` and `ala:scientificName` are related (ala is an "is a" version of the dwc one).

**Comment by Tasilee** [comment]
Thanks @nickdos. I figured the pipelines project would help with this issue. Download column headings with URI to explanations/definitions would be an improvement over headings.csv. Darwin Core will remain the framework we have to hang off, so we a) Have to map whatever we have received or processed to the best match explicit dwc:term, b) use an alternative explicit namespace where there are no matches.

**Comment by brucehyslop** [comment]
There has been changes to the field names with pipelines project work.

When performing a full DwC download the column headers are for `scientificName` are

| Column name            | Requested field    | DwC Name               | Field name         |
|------------------------|--------------------|------------------------|--------------------|
| ... |
| scientificName         | scientificName     | scientificName         | scientificName     |
| ... |
| verbatimScientificName | raw_scientificName | verbatimScientificName | raw_scientificName |
| ... |

**Comment by nickdos** [comment]
Fixed in pipelines
