### ISSUE TITLE
Implement name autocomplete service

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#53]
Currently in the biocache-hubs, autocomplete is tied to the ALA BIE service.

With more external users running biocache, there is a need to provide the autocomplete service for just the data coming from biocache-service. biocache-service is already doing names lookups via the lucene index, so it should be possible to produce an aucomplete lookup service, similar to that provided by the BIE.

APPD would benefit from this.

**Comment by djtfmartin** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-hubs#128

**Comment by nickdos** [comment]
Not sure why this has been moved unless it has been implemented in biocahe-service already... Has it?

**Comment by adam-collins** [comment]
An autocomplete with the same results format as bie is available when service.bie.enabled=false.

By default it will only results that have occurrences. Those occurrences can be restricted with fq:
http://ala-cohen.it.csiro.au/biocache-service/autocomplete/search?q=acacia&fq=data_hub_uid:dh2

**Comment by adam-collins** [comment]
done

**Comment by nickdos** [comment]
I'm not seeing the same results format for this service vs BIE version.

https://biocache-clustered.ala.org.au/ws/autocomplete/search.json?q=ac

![image](https://user-images.githubusercontent.com/532845/40651398-edb20d96-6378-11e8-962e-6df8b103c713.png)

https://bie.ala.org.au/ws/search/auto.json?q=ac

![image](https://user-images.githubusercontent.com/532845/40651561-598e43a4-6379-11e8-9c6a-2a2d20d2e293.png)

**Comment by nickdos** [comment]
It is desirable but not a show stopper. It would just make the JS code in ala-hub/biocache-hubs simpler if you could just switch the URL and all the JS code to parse the JSON was the same. Otherwise we could simply swap a different JS file to parse the BIE and another to parse the biocache-service JSON.

**Comment by djtfmartin** [comment]
closing. If we need to align the services, i suggest we create a new issue.
