### ISSUE TITLE
CSDM downloads are not passing correct param to doi-service

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#533]
Related to #516. 

The CSDM download passes in a param `&displayTemplate=csdm` which is correctly triggering a CSDM-specific email template. However this value should be passed onto the request to DOI service, so the DOI service can also use a CSDM-specific template on the DOI page. 

According to debugging, the following is being sent: `\x22displayTemplate\x22:\x22biocache\x22`, whereas the [displayTemplate](https://github.com/AtlasOfLivingAustralia/biocache-service/search?q=displayTemplate&unscoped_q=displayTemplate) value should be `csdm` or similar. P.A. thinks the encoding is incorrect, as it should be URL encoded (`%22`) and not unicode encoded in the POST body(?).

FYI @m-hope & @temi.

**Comment by brucehyslop** [comment]
The parameter to pass to `biocache-service` is `&doiDisplayTemplate=csdm`

**Comment by nickdos** [comment]
> The parameter to pass to `biocache-service` is `&doiDisplayTemplate=csdm`

This issue is for param **from** biocache-service to doi-service.

**Comment by ansell** [comment]
There is no encoding issue. I was just explaining the strange way that NGINX was serialising to its log file.

**Comment by temi** [comment]
It looks like CSDM hub is creating DOI with the correct display template. Not sure what has changed.
https://doi-test.ala.org.au/doi/10.80416/TEST_DOI_5f643240a0c1d

**Comment by nickdos** [comment]
@adam-collins made [a fix in CSDM-hub](https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/7a5a44c3ea8fb9098ab48982bf3e976060003a3b) - apparently the param name changed (was `displayTemplate` and now is `doiDisplayTemplate`).
