### ISSUE TITLE
wrong status code

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#542]
While I ran Gatling test on biocache-service, this request

`https://biocache-ws-dq-test.ala.org.au/ws/webportal/params/details/1601282603173`

returns 
```
{
    "message": "No stored query available for qid:1601282603173",
    "errorType": "Server error"
}
```

with status code `500`. Should it be `404` or something indicating resource not available?

**Comment by nickdos** [comment]
@brucehyslop to test this fix on test env...

**Comment by brucehyslop** [comment]
:white_check_mark: passed on test env 

Successful QID lookup: 
```
Request URL: https://biocache-test.ala.org.au/ws/webportal/params/details/1601282603173
Request Method: GET
Status Code: 200 
```

Unknown QID lookup:
```
Request URL: https://biocache-test.ala.org.au/ws/webportal/params/details/9999999999999
Request Method: GET
Status Code: 404 
```

Unknown QIOD lookup on prod (v2.5.1)
```
Request URL: https://biocache.ala.org.au/ws/webportal/params/details/9999999999999
Request Method: GET
Status Code: 500
```
