### ISSUE TITLE
Allow * wildcard searches at the end of queries

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#556]
WIldcard searches (e.g. `q=record_number:questagame-*`) do not currently work via biocache-service but they do work using the SOLR admin interface. The reason they fail in biocahce-service, is due to the query part being esacped via the [SOLRJ escape function](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Escaping%20Special%20Characters), which escapes the `+ - && || ! ( ) { } [ ] ^ " ~ * ? : \` chars. 

This enhancement is suggesting that we make a special case for a trailing `*` char only. This could be achieved by wrapping the SOLRJ `ClientUtils.escapeQueryChars(value)` method ([called here](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/66e26d96c8d84f21aacc908fb8ef29eaa3deebc2/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L562)) in a utility method which then un-escapes any trailing `*` after the string has been escaped.

As discussed today - @peggynewman @patkyn @sadeghim

**Comment by brucehyslop** [comment]
https://biocache-ws.ala.org.au/ws/occurrences/search?q=raw_scientificName:Thismia* return 0 results

**Comment by adam-collins** [comment]
Appears done
