### ISSUE TITLE
Limit downloads to a maximum of X million records

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#563]
Most of the large downloads we notice appear to be accidental - user not really understanding what they are requesting. They can put a significant load on SOLR and result in SOLR outages.

There is a maximum record number for online downloads (from memory) and offline downloads, so we need to reduce the offline download limit to (say) 1,000,000.

Also check how this is handled in the resulting download file. Perhaps there should be an additional file called "Maximum record count exceeded.txt" with explanation and link to KB article that provides a full explanation.

CC @peggynewman @djtfmartin

**Comment by peggynewman** [comment]
I think 1m is unreasonably small - it would cause me problems with providing exports to stakeholders. I would support 25m, which is bigger than the largest data resource. 
Is another perspective on this problem to reduce the empty fields delivered? The downloads I get - when ticking that I want all the fields - gives me 250+ fields and the file size is massive.

**Comment by djtfmartin** [comment]
thanks @peggynewman  - this one was discussed and agreed at the O&A meeting. Maybe we can raise it again there.

It is not really related to document size currently (AFAIK with SOLR 6 the whole doc is loaded regardless of the request field) although we think downloads will be less of a strain on the system with docvalues introduced (as the whole document isn't loaded).

Few other points:
* With pipelines, producing the large exports could be done against the Spark cluster using SparkQL without impacting the SOLR cluster.
* If we start using SOLR streaming API, we think this will let us support much larger downloads without impacting the cluster too much. This is doc values dependent, so its something we can do post v1 release of pipelines.

**Comment by peggynewman** [comment]
Thanks @djtfmartin, exciting stuff. Perhaps we should concentrate our efforts on ensuring that we are using one or both of these options consistently for downloads in pipelines. Agree to raise it again at the O&A meeting.

**Comment by nickdos** [comment]
Is there a limit set in biocache-service, since pipelines?

**Comment by brucehyslop** [comment]
The default download limit is 100,000,000 records.
The current `test` and `prod` config is set to 50,000,000. 

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/89807ae158967218077f6db44aed6f7c2732c1a8/src/main/java/au/org/ala/biocache/service/DownloadService.java#L276-L280

https://github.com/AtlasOfLivingAustralia/ansible-inventories/blob/eed84ac2da246c925b3739e247b6b5c0d12f3700/biocache/biocache-service-2021#L124

**Comment by adam-collins** [comment]
Downloads are improved. 

Related https://github.com/AtlasOfLivingAustralia/downloads-plugin/issues/85
