### ISSUE TITLE
data-quality filter can be expanded multiple times

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#571]
`queryFormatUtils.formatSearchQuery(requestParams, false)` is called multiple times in WMSControlller when generating map data. This causes a quality filter to be expanded multiple times because with current implementation everytime `formatSearchQuery` is called, the dq filter get expanded once.

In my case `ALA General` profile is used and filters are expanded 3 times, resulting 30 fqs in the final solr query.

**Comment by adam-collins** [comment]
appears done
