### ISSUE TITLE
UserIP is getting 2 IP addresses

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#575]
@nickdos commented on [Thu Mar 25 2021](https://github.com/AtlasOfLivingAustralia/logger-service/issues/32)

Update: it appears the `user IP` value is generated by the client code (via `ala-logger`'s `LogEventVO` object), so not a `logger-service` bug, per se. 

- [ ] 1. Similar to the [fix I did here](25897370673aa25915f233991b257bedc3acb2ab), the `user IP address` needs to be de-duplicated.
![image](https://user-images.githubusercontent.com/532845/112407372-15662e80-8d6a-11eb-8249-5ead141408f6.png)

- [ ] 2. Download events (typeId = 1002) are showing a user IP address of `127.0.0.1`.

![image](https://user-images.githubusercontent.com/532845/112408178-70e4ec00-8d6b-11eb-88b5-524826d71744.png)

---

@nickdos commented on [Thu Mar 25 2021](https://github.com/AtlasOfLivingAustralia/logger-service/issues/32#issuecomment-806335463)

Moving to biocache-service.
Suspect these lines need looking at:

1. https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/web/OccurrenceController.java#L1607

2. https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/service/DownloadService.java#L845

**Comment by javier-molina** [comment]
Alex confirmed this has been tested.
