### ISSUE TITLE
Querying a species  in  complex areas brings in every occurrence record 

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/biocache-service#579]
When we register a query with a species and complex areas,   BS returns an incorrect query, like: 
https://biocache.ala.org.au/ws/webportal/params/details/1616715731279
q is set to [* : * ], and wkt is gone. 
[mg.txt](https://github.com/AtlasOfLivingAustralia/biocache-service/files/6225061/mg.txt)

**How to reproduce:**
Add area -> import SHP file -> choose the SHP file provided below
[aspis.1.zip](https://github.com/AtlasOfLivingAustralia/biocache-service/files/6837334/aspis.1.zip)

Add species -> Choose 'Eucalyptus'. 

**Result**:
The map displays all species across the world.

**Reason:**

@alexhuang091  points out: 
Nginx has post body Max < 2M limits
 
Oversized params / wkt is  rejected by Nginx before it reaches Biocache.  Those params were dropped by Nginx,  Biocache automatically fills q = *:* , which returns all records.

**Comment by qifeng-bai** [comment]
After updated Tomcat settings, adding a species in a complicated area on Spatial-test works
![Screen Shot 2021-07-19 at 11 20 23 am](https://user-images.githubusercontent.com/31238531/126089622-97e48438-7698-424f-a016-2c4c2ad5c926.png)

**Comment by nickdos** [comment]
Fixed

**Comment by nickdos** [comment]
May need to be revisited if new thresholds are exceeded in prod at some time in the future.
