### ISSUE TITLE
Improve downloads multimedia implementation

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#58]
Download API provides an option to specify `extra=multimedia,image_url` to be able to get image info in download file. There are two problems with this:
- the `image_url` field is just an `image_uuid` string and thus relies on the client to encode a URL themselves, which is not documented anywhere that I could find. Ben Raymond has brought this to our attention.
- it doesn't work for non-image multimedia types, such as sounds or video files - fields are empty in the download CSV. Ben also highlighted this issue.

Suggestion is to change the field from `image_url` to `multimedia_url` (and the associated `image_url_all`). To also provide the full URL not just the image UUID. This is important for external users of the ALA API and means the service would be a proper REST service (must have URIs).

**Comment by M-Nicholls** [comment]
We'll need to check the license conditions on the multimedia - e.g. the soundfiles from the ANWC are not meant to be available for download.

**Comment by nickdos** [comment]
Related to #52

**Comment by nickdos** [comment]
Also see AtlasOfLivingAustralia/data-management#531

**Comment by nickdos** [comment]
@peggynewman You mentioned @matilda2812 has added support for getting images from records via ALA4R, so I thought it might be a good time to look into the issue, as it is closely related.

**Comment by nickdos** [comment]
Added `images` to downloads config so they are included in all downloads. See:

- https://github.com/AtlasOfLivingAustralia/ansible-inventories/commit/e5b1fdf1fe31a4a8ddd6361ae13a1f9cbbaacaf7
- https://github.com/AtlasOfLivingAustralia/ansible-inventories/commit/79eb2b249dbbf3d21a0893cf8f9591243e252643
- https://github.com/AtlasOfLivingAustralia/biocache-service/commit/bafe5ac88eb37b9dce42c77a33437c37aa5c4d1c

First 2 are deployed but last one waiting on next biocache-service deployment.

**Comment by nickdos** [comment]
This is done in Pipelines, so closing.
