### ISSUE TITLE
Record JSON showing wrong value for `associatedOccurrences `

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#585]
https://biocache-test.ala.org.au/ws/occurrence/baf66e9a-c4db-442b-b987-c3f019bf3c45 shows:

```json
associatedOccurrences: "<a href="https://biocache.ala.org.au/occurrences/search?q=institution_code:%22ANWC%22%20AND%20collection_code:%22Birds%22%20AND%20catalogue_number:%22B50987%22"> ANWC:Birds:B50987</a>",
```

whereas this one- https://biocache-ws-test.ala.org.au/ws/occurrences/c98292ae-ce1a-4a95-9a38-28c4d6eb020b shows:

```json
associatedOccurrences: "17d3fa16-9ba3-4657-a7a6-78fb539ad591",
```

Investigate why the URL is being included in some records but not others.

**Comment by alexhuang091** [comment]
Hi Nick, I'll work on it this afternoon. Currently still doing alerts/biocache-hubs

**Comment by alexhuang091** [comment]
Had a quick look at this, 

```
"dataResourceName":"Australian National Wildlife Collection provider for OZCAM",
"raw_associatedOccurrences":"<a href=\"https://biocache.ala.org.au/occurrences/search?q=institution_code:%22ANWC%22%20AND%20collection_code:%22Birds%22%20AND%20catalogue_number:%22B50987%22\"> ANWC:Birds:B50987</a>",
"sensitive_decimalLongitude":"128.7581",
```

it's like this in Solr. Need to figure out how it get inserted into Solr.

**Comment by nickdos** [comment]
Values provided by owners. Not an issue.
