### ISSUE TITLE
qid only works in q, not fq

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-service#61]
works http://biocache.ala.org.au/occurrences/search?q=qid:1439583650801
does not work http://biocache.ala.org.au/occurrences/search?fq=qid:1439583650801

**Comment by nickdos** [comment]
Not sure this makes sense... A `qid` is a cached **full query** that includes both `q` and `fq` params. Using `qid` in a `fq` params breaks this idea - how can you include a full query inside a "restricted" query?

**Comment by adam-collins** [comment]
Agree that qid is a full query. Additional fq support was added early on. Additional wkt support was added recently. While there is no immediate need I was wondering if this was a useful next step.

When passing a qid between applications there may be a use for this enhancement. The qid generated for a species list for example. Instead of creating a new qid for each link through to biocache or SP it could be kept and reused.

**Comment by adam-collins** [comment]
Closing until there is a need for this.
