### ISSUE TITLE
Flag an issue - not accepting comments

### ISSUE THREAD

**Issue by johntann99** [AtlasOfLivingAustralia/biocache-service#62]
When a user attempts to Flag-an-issue, SUBMIT action does not function.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-hubs#140

**Comment by temi** [comment]
@johntann99 did you try submitting in biocache.ala.org.au?

**Comment by johntann99** [comment]
Yes.  And I hit the long slow wheel of nothing happening. 

John
