### ISSUE TITLE
Missing header field "Date" in email sent for downloads

### ISSUE THREAD

**Issue by shahmanash** [AtlasOfLivingAustralia/biocache-service#621]
The email sent from biocache-service when the download is ready seem to bounce due to missing header field "Date"

```
The message WAS NOT relayed to:
  <sbdi4r-test@biodiversitydata.se>:
   554 5.6.0 Bounce, id=22234-02 - BAD HEADER

This nondelivery report was generated by the program amavisd-new at host
mail.biodiversitydata.se. Our internal reference code for your message is
22234-02/Ebcojaf3qCEK

INVALID HEADER

  Missing required header field: "Date"
```

Should there be an additional line of code here https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/service/EmailService.java#L72-L78
to set the header field "Date" ?
`message.setSentDate(new Date());`

**Comment by shahmanash** [comment]
Not sure if anyone find this useful, but posting it for the record

To allow the delivery of the mail with missing header field, I added the following to the file **/etc/amavis/conf.d/50-user**
```
%final_destiny_maps_by_ccat = (
  CC_VIRUS,       D_DISCARD,
  CC_BANNED,      D_DISCARD,
  CC_UNCHECKED,   D_PASS,
  CC_SPAM,        D_PASS,
  CC_BADH.',7',   D_PASS,
  CC_BADH,        D_PASS,
  CC_MTA.',1',    D_TEMPFAIL,  # MTA response was 4xx
  CC_MTA.',2',    D_REJECT,    # MTA response was 5xx
  CC_MTA,         D_TEMPFAIL,
  CC_OVERSIZED,   D_BOUNCE,
  CC_CATCHALL,    D_PASS,
);
```
The line **CC_BADH.',7',   D_PASS,** seem to do the trick.

The mail is delivered to the recipient although the header indicates the the header field Date is missing.

**X-Amavis-Alert: BAD HEADER SECTION, Missing required header field: "Date"**

**Comment by djtfmartin** [comment]
That is useful. Thank you @shahmanash

**Comment by vjrj** [comment]
@shahmanash, tuning your amavis will work for that initial server, but the destiny server probably will reject also the email or mark it as spam if it has some missing header or some suspicious header. So I think that the correct fix is probably your initial comment or similar.

This can explain that sometimes user complain about missing download emails (but I can see that they are delivered correctly).
