### ISSUE TITLE
Occurrence page showing deleted record information, while search result has updated info.

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#63]
_From @sadeghim on January 23, 2015 0:11_

In the search result :
http://biocache.ala.org.au/occurrences/search?taxa=CANB123391
the last record shows Catalog Number:     **CANB:CANB 123391.1**   
while in the occurrence view page it is **CANB:CANB 123391** : http://biocache.ala.org.au/occurrences/cc641a8d-cf56-4a59-a096-1a309b0ac49d

In Cassandra, I could find two records for these catalog numbers and one of the (shown on the occurrence view page) has a deleted field as TRUE. 

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#117_

**Comment by nickdos** [comment]
_From @sadeghim on January 23, 2015 0:18_

Maybe it's related to issue AtlasOfLivingAustralia/biocache-store#33

**Comment by nickdos** [comment]
_From @nielsklazenga on January 23, 2015 1:4_

Hi Nick, just some background information. In November 2011 CANB (and CNS) stopped delivering, while they were working on a new collections database. In October 2013 (or thereabouts) delivery started up again, but by then their catalogue numbers had changed. Natasha matched them up as well as possible, but some must have been missed. Catalogue numbers with the structure CANB 123391 are pre-2011, while catalogue numbers with the structure CANB 123391.1 are post-2013. We did a complete reload of the CANB and CNS data sets, so there should really be no catalogue numbers without suffixes left.

**Comment by nickdos** [comment]
Dave, could you look at this? It seems there are 2 records in Cssandra for this specimen and biocache is serving up the old record. So I'm not sure why we:
* need to keep both (old and new)
* we are indexing and serving the old record

This looks like a biocache-service bug as the hubs should simply be displaying the record that is indexed by SOLR and shouldn't have to know about `deleted=TRUE` fields, etc.

**Comment by sadeghim** [comment]
I am going to remove all of those pre-2011 records that have a matching record post 2013.

**Comment by sadeghim** [comment]
The issue was fixed after deleting corrupt records.
