### ISSUE TITLE
Support map download with google base layer in Biocache

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#64]
_From @djtfmartin on August 19, 2014 11:40_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=256
*date:* Mon Sep  2 18:34:15 2013
*author:* moyesyside
 ---

Requested by several users.
This is available in spatial portal so we should look to moving this into a common service that can be accessed by all components

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#42_

**Comment by nickdos** [comment]
_From @djtfmartin on August 19, 2014 11:40_


*date:* Thu Jul 17 00:00:47 2014
*author:* moyesyside
 ---

*(No comment was entered for this change.)*

 ---
**UPDATES:**
*Labels:* Hubs

**Comment by adam-collins** [comment]
Added ```baseMap``` param to ```/webportal/wms/image``` and ```/mapping/wms/image```. Usage with  ```roadmap```, ```terrain```, ```satellite``` or ```hybrid``` will return with the corresponding Google base layer.
