### ISSUE TITLE
Search all records times out regularly

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-service#66]
<img width="1050" alt="screenshot 2015-08-25 16 41 17" src="https://cloud.githubusercontent.com/assets/444897/9471431/24503e96-4b48-11e5-9faf-4d3b335b1b67.png">

The "all records" search regularly timeout. This is linked to from the dashboard (see the record count) so its a bad look.

The reason for the timeout is the large number of facets requested **_51!!!**_ by default. So this could be solved by:

1) Reducing the number of default facets on the client (biocache-hubs)
2) Cache the "all records" query result (biocache-service)
3) Putting something infront of biocache-service to cache this expensive query (memcache ?)

Assigning to @nickdos as he may want to allocate this to a sprint.

**Comment by adam-collins** [comment]
For 1) wondering if hubs can use facet=off, q=*:*&facet=off is very quick. Hubs can ajax, or &facets= for visible facets only.

**Comment by djtfmartin** [comment]
yes, that makes sense

i also think its worth reducing the number of default facets. 51 seems a bit ridiculous.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/commit/76b6598dfdd5facbf5eadb607edd7cc4416f9dcd

**Comment by adam-collins** [comment]
Added a configurable:
- facets.max to trim &facets lists.
- facet.default to set &facet=off.

There are issues with defaulting facet=off. Some services that need facets are not turning it on, instead relying on the previous default facet=on.

**Comment by charvolant** [comment]
Certain facets have higher priorities than others. In particular, the Record Images tab on the biocache search pages expects a multimedia facet to determine whether it's worth looking for images. If the number of facets is to be limited, lowest priority facets need to be eliminated first. The number of location facets is now so large that if everything is selected, Occurrence, Record, Assertions and Attribution facets all go missing.

This could (should) be done by the requesting application but the biocache-service also supplies a default facet list which also needs to be prioritised.
