### ISSUE TITLE
Download "Datasets" breakdown counts are wrong

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#678]
This download DOI (test site) - https://doi-test.ala.org.au/doi/10.80416/ala.5d0db327-4e2a-4da5-ae51-87d54aae356e

was for a search for [institution: Australian Museum](https://biocache-test.ala.org.au/occurrences/search?q=institution_uid%3Ain4&disableAllQualityFilters=true&fq=-userAssertions%3A50001%20AND%20-userAssertions%3A50005&fq=-coordinateUncertaintyInMeters%3A%5B10001%20TO%20*%5D&fq=-duplicateStatus%3A%22ASSOCIATED%22&fq=-spatiallyValid%3A%22false%22&fq=-year%3A%5B*%20TO%201700%5D&fq=-occurrenceStatus%3AABSENT&fq=-establishmentMeans%3A%22MANAGED%22%20AND%20-decimalLatitude%3A0%20AND%20-decimalLongitude%3A0%20AND%20-assertions%3A%22PRESUMED_SWAPPED_COORDINATE%22%20AND%20-assertions%3A%22COORDINATES_CENTRE_OF_STATEPROVINCE%22%20AND%20-assertions%3A%22COORDINATES_CENTRE_OF_COUNTRY%22&fq=-assertions%3ATAXON_MATCH_NONE%20AND%20-assertions%3AINVALID_SCIENTIFIC_NAME%20AND%20-assertions%3ATAXON_HOMONYM%20AND%20-assertions%3AUNKNOWN_KINGDOM%20AND%20-assertions%3ATAXON_SCOPE_MISMATCH&fq=-basisOfRecord%3A%22FOSSIL_SPECIMEN%22%20AND%20-%28basisOfRecord%3A%22MATERIAL_SAMPLE%22%20AND%20contentTypes%3A%22EnvironmentalDNA%22%29&fq=-outlierLayerCount%3A%5B3%20TO%20*%5D) resulting in 1,289,086 records. 

However the breakdown counts in the "Datasets" table shows only 1001 records for "Australian Museum" (`in4`). This stat should be the same number as the total records (1,289,086).

The facet value appears correct...

![image](https://user-images.githubusercontent.com/532845/128667441-8c9dff39-5641-4efb-b0eb-2177bec79ddf.png)

So not sure why download DOI has such low count value for the same "facet"...

Running [~same~ equivalent search on prod](https://doi.ala.org.au/doi/10.26197/ala.88d9f71b-fb7b-4d5b-a4dd-ca25608e1bfb), shows the expected counts for `in4` (DQ filters was inactive, so not identical).

**Comment by javier-molina** [comment]
Issue moved to [AtlasOfLivingAustralia/la-pipelines #502](https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/502) via [**ZenHub**](https://www.zenhub.com/)
