### ISSUE TITLE
Exporting points generates an empty csv

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/biocache-service#680]
From here, I did as follows:
1) Export (top left corner menu) --> Points
2) Select area --> World, Select species --> "[all species] - within user defined polygon", Select layers --> "Aridity index - annual mean", "Vegetation types - native", "Topographic slope %", "Elevation", "WorldClim 2.1: Temperature - annual mean", "WorldClim 2.1: Temperature - seasonality", "WorldClim 2.1: Temperature - warmest quarter mean", "WorldClim 2.1: Temperature - coldest quarter mean", "WorldClim 2.1: Precipitation - annual", "WorldClim 2.1: Precipitation - seasonality"
3) Next > *to the data download page*
4) Occurrence records selected, change name of file, Download format = Full Darwin core, Output file format = csv, industry application = scientific research
5) Next > *to the download queue screen*
I have tried downloading the zip file from the link that comes up on the download screen when the download is ready, from the link sent to my email, and from the link in my profile download history, all with the same result. I've tried it on both my desktop and my laptop as well.
Here is a screenshot as well - as you can see, I tried doing this three separate times and each time it is saved in my profile as a download with 384 records, but the csv is just empty except for the header row.
I have also tried just downloading the points from the biocache and that worked fine, so the issue seems to be specifically with using the spatial portal.
I hope this is useful information to help you work out the problem.

**Comment by qifeng-bai** [comment]
The method of sample(String[] analysisLayers, double[][] points, Object o) in AlaLayerService has not been implemented
![Screen Shot 2021-08-12 at 9 15 07 am](https://user-images.githubusercontent.com/31238531/129118814-988a226d-a7d7-4457-8123-e269a4fa07dd.png)

**Comment by nickdos** [comment]
@qifeng-bai - this issue is still in progress on the board. Does it need more work or is it ready for CR and QA?

**Comment by qifeng-bai** [comment]
@nickdos @adam-collins would like to have a further discussion

**Comment by adam-collins** [comment]
appears done
