### ISSUE TITLE
All provided DwC terms should be displayed on the record page 

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/biocache-service#684]
For this record, the data provider gave us organismName and organismID, but these fields aren't available on the record view: https://biocache.ala.org.au/occurrences/bbcb4515-2350-4261-bdf4-146937830b2e

All DwC terms provided should be displayed on the record page, and the raw and processed fields displayed in the original vs processed view.

Need to be added to both ../ws/occurrences/uuid and the hubs display

**Comment by adam-collins** [comment]
This appears to be working e.g. https://biocache.ala.org.au/occurrence/f58ad174-fd5e-4f1a-a5d2-5ec757d795d2
