### ISSUE TITLE
Querying over the layer: "country:Australia" generates a flipped Australia map

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/biocache-service#687]
Url:  https://biocache.ala.org.au/occurrences/search?q=qid:1629435390762#tab_mapView

![Screen Shot 2021-08-20 at 2 57 43 pm](https://user-images.githubusercontent.com/31238531/130182762-ee25b2ec-a751-4977-b2b6-ef7ce6357e65.png)

**Comment by nickdos** [comment]
This is the same issue https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/510
