### ISSUE TITLE
record.sounds contain images

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#689]
This record `https://biocache.ala.org.au/ws/occurrences/4a87d38b-06e4-4294-83fe-6d2f9ba9b97f`
has same list of ids in images and sounds

```
"images": [
        "https://images.ala.org.au/image/proxyImage?imageId=480f5f5e-e96c-4ae3-8230-c53a37bc542e",
        "https://images.ala.org.au/image/proxyImage?imageId=e6675c23-d2f4-449e-b5f3-77b6a2c1a2a0",
        "https://images.ala.org.au/image/proxyImage?imageId=5af5532f-df55-4747-88e4-7e520d054c23",
        "https://images.ala.org.au/image/proxyImage?imageId=68f40107-5e2e-4c20-b825-9c2ed8d3992a"
],
"sounds": [
        "480f5f5e-e96c-4ae3-8230-c53a37bc542e",
        "e6675c23-d2f4-449e-b5f3-77b6a2c1a2a0",
        "5af5532f-df55-4747-88e4-7e520d054c23",
        "68f40107-5e2e-4c20-b825-9c2ed8d3992a"
],
```

Checking Solr you can see the `soundIDs` and `imageIDs` are identical.
<img width="646" alt="截屏2021-08-24 下午4 55 18" src="https://user-images.githubusercontent.com/61677987/130570893-fb526318-0627-4f7e-a167-3933afa09f6f.png">

This causes:
1. image being displayed as sound track (in sound player) and thus fails to be displayed
2. same list are being displayed for twice.

Do a search in Solr `http://localhost:8983/solr/biocache/select?fl=soundIDs, imageIDs&fq=multimedia:Sound&q.op=OR&q=*:*&rows=1000` Seems as long as a record has both soundIDs and imageIDs, they will be same.
<img width="421" alt="截屏2021-08-24 下午4 59 30" src="https://user-images.githubusercontent.com/61677987/130571502-a67850ee-0c43-48a1-a8f9-40447214e9ed.png">

**Comment by adam-collins** [comment]
Pipelines pull request https://github.com/gbif/pipelines/pull/999

**Comment by adam-collins** [comment]
Fix is in 2.18.0-SNAPSHOT

**Comment by adam-collins** [comment]
Possibly confirmed by these records not duplicating the sound IDs in the images field. https://biocache-test.ala.org.au/occurrences/search?q=sounds:*&fq=-dataResourceUid:dr22185

**Comment by peggynewman** [comment]
Those records LGTM
