### ISSUE TITLE
Searching by catalog number

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#69]
_From @santiagomtzdelariva on September 17, 2015 11:41_

I put these two catalog numbers, one per line, and the result is this:

OPP570042-8 - 7ba37098-3751-4e49-8cec-127a001d15e5 (ID)
OPP567978-5 - 0151a9c2-02f6-434e-ba86-3f9154bc4a0d

http://biocache.ala.org.au/ws/occurrences/batchSearch

{
"message": "Request method 'POST' not supported", "errorType": "Server error"
}

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#152_

**Comment by adam-collins** [comment]
action Search is working, e.g. ```curl -X POST -d "queries=OPP570042-8%0AOPP567978-5&field=catalogue_number&redirectBase=http://biocache.ala.org.au/ws/occurrences/search" -v http://biocache.ala.org.au/ws/occurrences/batchSearch?action=Search``` returns a valid redirect url.

action Download does not form a usable URL. Given that action Search requires a redirectBase and other downloads require additional information, it may be more useful to allow redirectBase to contain URL params. For downloads this would include reasons, user info, and whatever else is required.
