### ISSUE TITLE
failed to get notification email for download result

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#699]
Lot users had this issue on prod server which runs `biocache-service 3.0.22`.

This issue can be reproduced on test server

**Comment by brucehyslop** [comment]
Mail is attempted to be delivered to the MTA (postfix) on the biocache download server however is not forwarded on.

I've tried to inspect the difference betweem the SMTP traffic when switching `com.sun.mail:javax.mail:jar:1.5.0` to `com.sun.mail:javax.mail:jar:1.6.2` as per PR #700 however can not see any difference. However the download completion email is now being delivered from `nci3-biocache-service`.

I'm happy with the fix :white_check_mark:

**Comment by djtfmartin** [comment]
fixed
