### ISSUE TITLE
User assertions are disappearing from SOLR index

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-service#704]
@nickdos commented on [Wed Sep 15 2021](https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/520)

@elywallis reported this a few weeks back. When a user adds an annotation (assertion) on a record that triggers that record to be removed by the DQ filters (e.g. location issue), the SOLR index is updated immediately and the record disappears from the default "ALA General" DQ profile results set, as expected.

The problem is when a user re-runs the same query as above, a few days later, the same record re-appears in the result set. The record still has the annotation on it but it appears the SOLR index has lost the assertion status. This seems to happen after a full re-index has run over night.

@djtfmartin thought it was due to a missing Jenkins task not being run as part of the full indexing job. @peggynewman thinks this is not the case (not sure if that means job is now included but issue is still happening or that the cause is somewhere else).

---

@nickdos commented on [Fri Sep 17 2021](https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/520#issuecomment-921462110)

Testing this again now.

https://biocache.ala.org.au/occurrences/search?q=collector_text%3Aremedios orignally returned `23 of 31` records.

Then I added an annotation to [this record](https://biocache.ala.org.au/occurrences/e0966e63-a42c-42cd-81c4-a3c225408203), reducing count to be `22 of 31` records.

Retest next week so see how many records are being displayed.

---

@nickdos commented on [Fri Sep 24 2021](https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/520#issuecomment-926276563)

https://biocache.ala.org.au/occurrences/search?q=collector_text%3Aremedios

Now shows 29 of 31 records.

![image](https://user-images.githubusercontent.com/532845/134604376-e4c59ebe-3830-4ecd-8613-e0e5d3689d5b.png)

So issue is still unresolved.

**Comment by djtfmartin** [comment]
Issue moved to [AtlasOfLivingAustralia/data-management #760](https://github.com/AtlasOfLivingAustralia/data-management/issues/760) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nickdos** [comment]
Sanity checking this is fully resolved. Check next week that the query:

https://biocache.ala.org.au/occurrences/search?q=collector_text%3Aremedios

shows `21 of 31 records` and that the record:

https://biocache.ala.org.au/occurrences/1600fd32-ca6b-4097-8ef7-0cfac370be66

is NOT shown on the map.

**Comment by nickdos** [comment]
5 days later, the counts are unchanged (good).
