### ISSUE TITLE
Improve performance of download service

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-service#707]
@djtfmartin commented on [Mon Jun 14 2021](https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/424)

Areas of interest:
* Threading and queuing of downloads
* Increasing resource allocation for biocache downloads service (currently only 2 CPU machine)
* Investigate performance of CSV library in use - currently `au.com.bytecode.opencsv.CSVWriter` see [code](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/writer/CSVRecordWriter.java#L83)

Originally from Dave
> The CPU usage on the downloads server is high when running a download.
> This is the case in production as well, but there is a slight increase. Note - this isn't affecting the stability of SOLR cluster and so doesn't impact other services.
> 
> Things to investigate:
> * Field mapping optimizations
> * Use of CSV extracts in streams (as opposed to Tuples) - may reduce GC.
> 

---

@djtfmartin commented on [Wed Jun 16 2021](https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/424#issuecomment-862307173)

Discussed with @adam-collins 

Areas of interest:
* Threading of downloads
* Increasing resource allocation for biocache downloads service (currently only 2 CPU machine)
* Investigate performance of CSV library in use - currently `au.com.bytecode.opencsv.CSVWriter` see [code](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/writer/CSVRecordWriter.java#L83)

---

@adam-collins commented on [Tue Jul 27 2021](https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/424#issuecomment-887287711)

Include simplification of download queue and threads.

**Comment by adam-collins** [comment]
done
