### ISSUE TITLE
decade/occurrenceYear facet returning inconsistent results

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-service#708]
@adam-collins commented on [Fri May 07 2021](https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/337)

Faceting on `decade` returns the expected results, one per decade. The result indicates that the correct field to use is now `occurrenceYear` https://aws-biocache-quoll.ala.org.au/ws/occurrences/search?q=*:*&pageSize=0&facet=true&facets=decade&flimit=-1

However faceting on `occurrenceYear` returns incorrect results. A ten year span for each year.  https://aws-biocache-quoll.ala.org.au/ws/occurrences/search?q=*:*&pageSize=0&facet=true&facets=occurrenceYear&flimit=-1

---

@adam-collins commented on [Fri May 07 2021](https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/337#issuecomment-834146651)

production is also wrong

**Comment by adam-collins** [comment]
Treating decade (int field) and occurrenceYear (date field) as-is. Pull request https://github.com/AtlasOfLivingAustralia/biocache-service/pull/864

**Comment by peggynewman** [comment]
LGTM
