### ISSUE TITLE
Fullt-text `text` field should be documented in `index/fields`

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#709]
https://biocache.ala.org.au/ws/index/fields does not include SOLR fields that are `copyTo` fields, such as `text`. Also, there is no way for a user to know what fields are added to `text`.

- [ ] add all SOLR schema defined fields to `/index/fields` that are not already included (`copyTo` fields probably)
- [ ] provide a list of fields that are added to each `copyTo` field in the `info` attribute or alternatively add a URL (to either `info` or `infoUrl`) to a page that lists the fields (not sure where this might be served from - GH wiki page or another JSON or plain text page served from biocache-service)

**Comment by brucehyslop** [comment]
Merging the SOLR schema defined fields would also have the additional advantage of listing all fields that have no values defined for any records within the shard. Currently only fields that exist in the interrogated shard are listed.

I suggest adding a new `sourceFields` property to `IndexFieldDTO` which is a list of the source fields copied. 

The solr schema returns this data:
```
http://nci3-solr-1.ala:8983/solr/biocache/admin/luke?show=schema
...
"text": {
  "type": "textgen",
  "flags": "IT--UM------------",
  "positionIncrementGap": 100,
  "copyDests": [ ],
  "copySources": [
    "country",
    "eventID",
    "speciesSubgroup",
    "raw_typeStatus",
    "scientificName",
    "raw_countryConservation",
    "raw_stateConservation",
    "collectionName",
    "catalogNumber",
    "basisOfRecord",
    "vernacularName",
    "raw_scientificName",
    "institutionCode",
    "raw_vernacularName",
    "id",
    "class",
    "countryConservation",
    "order",
    "dataResourceName",
    "raw_basisOfRecord",
    "typeStatus",
    "stateProvince",
    "collectionCode",
    "occurrenceID",
    "kingdom",
    "recordedBy",
    "phylum",
    "dataResourceUid",
    "genus",
    "species",
    "dataProviderName",
    "locationID",
    "institutionName",
    "originalNameUsage",
    "speciesGroup",
    "stateConservation",
    "family"
]
}
```

**Comment by brucehyslop** [comment]
@nickdos, the `text` field is not in the index field list because it is part of the default `index.fields.tohide` config. 

`_version_,text_recordedBy,defaultValuesUsed,generalisationToApplyInMetres,occurrenceDetails,text,quad` these fields are filtered out be default. We could remove it from the default or override with a config change.

**Comment by nickdos** [comment]
Wasn't aware of that. I think all fields should be there, so users know they can be used. We should only exclude fields that are never exposed to users (internally used only), is my feeling.

**Comment by brucehyslop** [comment]
All fields have been removed from the default `index.fields.tohide` and will be returned by `index/fields`.
A new optional property `sourceFields` containing an array of field names that are copied to a SOLR field has been added to the index field object.

see: https://biocache-ws-test.ala.org.au/ws/index/fields?dataType=textgen all `textgen` fields are copied from other fields.

**Comment by nickdos** [comment]
Thanks @brucehyslop that looks really good.

**Comment by adam-collins** [comment]
appears done
