### ISSUE TITLE
user assertion field incorrectly mapped.

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#724]
https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=*&sort=first_loaded_date&dir=desc&pageSize=20&facets=basis_of_record&fq=id:95cb6dcc-abb3-4690-a8b5-209b600066a9

returns
`"hasUserAssertions": "50005",`
but it actually should be a bool value.

This is the data in solr:
```
"contentTypes":["point occurrence data",
"gbif import"],
"userAssertions":"50005",
"hasUserAssertions":true,
"userVerified":false,
"lastAssertionDate":"2021-11-08T21:51:34Z",
"assertionUserId":["56528"]}]
```

**Comment by adam-collins** [comment]
appears working
