### ISSUE TITLE
`marineOnly` method refers to `species_habitat` which has been removed from index

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-service#728]
See
https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/web/WMSController.java#L1205

**Comment by adam-collins** [comment]
Needs another update. Only 2 values are valid for `biome`, `MARINE` and `TERRESTRIAL`. Update https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/web/WMSController.java#L1205

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/864

**Comment by peggynewman** [comment]
Tested biome value in  biocache-test. passed
