### ISSUE TITLE
biocache-service has issue in parsing fq

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/biocache-service#729]
run this query `https://biocache.ala.org.au/occurrence/search?qualityProfile=ALA&disableAllQualityFilters=true&fq=basisOfRecord:"MATERIAL_SAMPLE" AND contentTypes:"EnvironmentalDNA" ` returns **1,029,740 records**.

`https://biocache.ala.org.au/occurrence/search?qualityProfile=ALA&disableAllQualityFilters=true&fq=+basisOfRecord:"MATERIAL_SAMPLE" +contentTypes:"EnvironmentalDNA"` returns **1,493,360 records**.

<br>
<br>

**But when feeding 2 fqs directly into solr admin console, they return same number of records.**

for `basisOfRecord:"MATERIAL_SAMPLE" AND contentTypes:"EnvironmentalDNA"`
![111](https://user-images.githubusercontent.com/61677987/143327392-a9d4a51b-0afc-4059-8b9b-e9b270d54cde.jpg)

for `+basisOfRecord:"MATERIAL_SAMPLE" +contentTypes:"EnvironmentalDNA"`
![112](https://user-images.githubusercontent.com/61677987/143327421-ae89f26e-c2bc-4cbd-8d51-208cb731907c.jpg)

This may be related to https://github.com/AtlasOfLivingAustralia/DataQuality/issues/262. After this is fixed we can check if #DQ262 is still an issue.

**Comment by alexhuang091** [comment]
debug shows the `+` which means `requires` are removed so what got passed into solr is `basisOfRecord:"MATERIAL_SAMPLE" contentTypes:"EnvironmentalDNA"`

<img width="995" alt="截屏2021-11-25 下午12 41 24" src="https://user-images.githubusercontent.com/61677987/143354006-15a3fe6b-21d1-4247-a930-11d741c6b18d.png">

**Comment by alexhuang091** [comment]
Seems we need to url encode `+basisOfRecord:"MATERIAL_SAMPLE" +contentTypes:"EnvironmentalDNA"` first then append to `fq=`

**Comment by adam-collins** [comment]
Only a subset of SOLR query syntax is supported. I recommend users use `AND`. 

Not adding support for `+fieldName` as this may generate more work if switching to Elasticsearch.
