### ISSUE TITLE
WMS map legend error

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#73]
API docs do not specify which fields are mandatory and the following URL fails with strange error message:

http://biocache.ala.org.au/ws/mapping/legend?q=macropus

```
{
"message": "undefined field: """, "errorType": "Query syntax invalid"
}
```

Either this is a bug or else both the API docs and the error message returned by the service need to be updated so as to allow the user to work out why the search is failing.

**Comment by adam-collins** [comment]
Updated api and added an example http://biocache.ala.org.au/ws/mapping/legend?q=macropus&cm=species&type=application/json
