### ISSUE TITLE
`taxonConceptID` searches no longer work when no field is specified

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#732]
As reported by Yong from BCCVL. This URL used to work but now returns 0 results:

https://biocache-ws.ala.org.au/ws/occurrences/search?q=urn:lsid:biodiversity.org.au:afd.taxon:c303a58c-ffb9-4bf6-a71b-5e22299c5ee2

adding `lsid:` or `taxonConceptID:` to the param value fixes it:

https://biocache-ws.ala.org.au/ws/occurrences/search?q=lsid:urn:lsid:biodiversity.org.au:afd.taxon:c303a58c-ffb9-4bf6-a71b-5e22299c5ee2
https://biocache-ws.ala.org.au/ws/occurrences/search?q=taxonConceptID:urn:lsid:biodiversity.org.au:afd.taxon:c303a58c-ffb9-4bf6-a71b-5e22299c5ee2

I suspect a change to the default `text:` field has broken backwards compatibility, possibly due to added stemming or other SOLR filters used in the `text` field's schema definition.

**Comment by qifeng-bai** [comment]
My two cents:

Not sure if it is the reason,  I found : q=lsid:xxxxx will be translated to : q=taxonConceptID:xxxxxxxx in this method:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/util/solr/FieldMappingUtil.java#L79

**Comment by nickdos** [comment]
It might be related, in that the `taxonConceptID` field is not being added to the `text` field (via `copyTo`) in the SOLR schema file.

**Comment by qifeng-bai** [comment]
Wonder if adding taxonConceptID into "<defaultSearchField>" would help?

**Comment by qifeng-bai** [comment]
Schema update process: 
Edit: https://github.com/gbif/pipelines/blob/dev/livingatlas/solr/conf/managed-schema

Update and run: 
(1, backup the old schema with timestamp, load the new one)
https://github.com/gbif/pipelines/blob/dev/livingatlas/solr/scripts/update-solr-cluster-config.sh

It will upload the new schema to the solr server (in zookeeper folder)

....................

**Comment by adam-collins** [comment]
There is a need to wrap searches of the default text field in double quotes. e.g. https://biocache-ws.ala.org.au/ws/occurrences/search?q=NZOR-6-73174 vs https://biocache-ws.ala.org.au/ws/occurrences/search?q=%22NZOR-6-73174%22

However this is currently failing https://biocache.ala.org.au/ws/occurrences/search?q=%22https:%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F2896715%22. Need to escape `https` in the same way as `http`. https://github.com/AtlasOfLivingAustralia/biocache-service/pull/864

I have seen examples where the wrapping is expected by a user that expects wrapping of the entire search. e.g. https://biocache-ws.ala.org.au/ws/occurrences/search?q=New%20South%20Wales

In the biocache-service I do not recommend we wrap, in double quotes, individual words or the entire search term. Instead I suggest that if there is confusion on how the search works we address it in the UI. If wrapping is required do it in the UI.

**Comment by peggynewman** [comment]
Ok to test with a current LSID:

Error In prod:
https://biocache.ala.org.au/ws/occurrences/search?q="https://biodiversity.org.au/afd/taxa/808f7f5b-f6cd-4677-848a-49315e7babe3"

Fixed In test: https://biocache-ws-test.ala.org.au/ws/occurrences/search?q="https://biodiversity.org.au/afd/taxa/808f7f5b-f6cd-4677-848a-49315e7babe3"
