### ISSUE TITLE
Batch taxon name search error

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/biocache-service#734]
Application error occurred when testing https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/245:

Steps to produce:
1. On the search page, the "batch taxon search" tab. (https://biocache-test.ala.org.au/search#tab_taxaUpload)
2. Search for Phyllanthus hirtellus F.Muell. ex Müll.Arg. in both raw and non-raw form. Raw form should return about 70 records, non-raw the lot
    - Supplied name -> 73 records
    - matched name ->
```
Application error
Failed to get json from web service (https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=qid%3A1642727109168&qualityProfile=ALA&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name%2Cfamily%2Cspecies_group%2Ccommon_name%2Cmonth%2Coccurrence_decade_i%2Cstate%2Cbasis_of_record%2Cmultimedia%2Coccurrence_status%2CcontentTypes%2Cassertion_user_id%2Cinstitution_uid%2Cdata_resource_uid&flimit=10). class org.grails.web.converters.exceptions.ConverterException Error parsing JSON, org.grails.web.converters.exceptions.ConverterException: Error parsing JSON; nested exception is org.grails.web.converters.exceptions.ConverterException: Error parsing JSON
```

**Comment by nickdos** [comment]
https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=taxa:%22Phyllanthus%20hirtellus%20F.Muell.%20ex%20M%C3%BCll.Arg.%22 replicates the issue without going via the UI.

**Comment by peggynewman** [comment]
https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=taxa:%22Phyllanthus%20hirtellus%20F.Muell.%20ex%20M%C3%BCll.Arg.%22 returns records now
