### ISSUE TITLE
Create text-based field for dataset name searching

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#738]
Allow users to search for a substring against the `dataset_name` field.  Related to AtlasOfLivingAustralia/biocache-hubs/issues/341.

Currently `dataset_name` is a string field in the SOLR schema and can only be "found" when an exact match query is used. Therefore to allow Google-style searching, a new SOLR field needs to be created (`text` type) and then the `dataset_name` (and possibly `data_resource` as well) need to be copied into this field. Once this field is searchable, the advanced search page needs an additional field for Survey/dataset name to be added, to allow users to be able to search it.

Call the new (`text` based) field: `datasets` (maybe) and copy `dataset_name` and data_resource` values into it.

**Comment by qifeng-bai** [comment]
dataset_name is deprecated.  We are using camel case now.  

We have 'datasetName'  and 'dataResourceName' in https://github.com/gbif/pipelines/blob/dev/livingatlas/solr/conf/managed-schema

Please confirm we should use dataResourceName, instead of 'data_resource'. @nickdos

**Comment by nickdos** [comment]
> Please confirm we should use dataResourceName, instead of 'data_resource'. @nickdos

Yes, that is correct 👍

Original issue pre-dated the change to camelCase.
