### ISSUE TITLE
Support for fields that have changed to multivalue fields in pipelines

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-service#739]
See here:  https://github.com/gbif/pipelines/issues/665

These changes (not yet released) will necessitate changes in the SOLR schema to:
* identifiedBy
* samplingProtocol
* datasetID
* datasetName
* otherCatalogNumbers
* typeStatus

The following fields are already multivalue
* recordedBy

The code in OccurrenceController will need to be modified to accommodate these schema changes.

**Comment by djtfmartin** [comment]
Note - the addition of multi value fields has caused some issues in the databox environment - possibly as a result of a multi valued `typeStatus` field

See

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/develop/src/main/java/au/org/ala/biocache/dto/OccurrenceIndex.java

Error message

```

{
  "message": "Could not instantiate object of class au.org.ala.biocache.dto.OccurrenceIndex",
  "errorType": "Server error",
  "statusCode": 500
}
```

**Comment by qifeng-bai** [comment]
Fixed recordedBy

**Comment by adam-collins** [comment]
Looks ok
