### ISSUE TITLE
Image metadata not shown for multiple images

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#74]
Whe a records has more than one image, the image metadata is not being shown for the subsequent images (only first image) on the record page JSON. E.g.

http://biocache.ala.org.au/ws/occurrences/0202eaca-e6f3-4ea5-900a-ee178469e88b.json

shows:

![image](https://cloud.githubusercontent.com/assets/532845/10873847/aecfa0aa-816e-11e5-9de8-c13a62e14b44.png)

**Comment by adam-collins** [comment]
This might be another data issue. http://images.ala.org.au/ws/findImagesByMetadata returns only one image for ```{ "key": "occurrenceid", "values": ["0202eaca-e6f3-4ea5-900a-ee178469e88b"] }```

**Comment by adam-collins** [comment]
Found a record with 2 out of 3 images having metadata http://biocache.ala.org.au/ws/occurrence/4264a89d-e7d3-4438-b954-366885844a68

Need to work out how to re-sync cassandra and images.ala

**Comment by adam-collins** [comment]
The above examples are fixed by reindexing in images.ala admin tools.

There are around 3000 exceptions that require more manual correction.
