### ISSUE TITLE
Conservation status issues in Species checklist

### ISSUE THREAD

**Issue by ryonen** [AtlasOfLivingAustralia/biocache-service#740]
In the Species checklist the “Conservation” column doesn't give the actual conservation status of species it just gives the applicable State or Territory name followed by “… : Conservation Status”. It would be far more useful if it said “Endangered” or “Vulnerable” etc.

Also, where a species has more than one infrataxon, and one of those is conservation-listed (e.g. Threatened) and the other isn't, the species name doesn't have an entry in the Conservation Status column unless the species name is EPBC-listed (see attached, highlighted in yellow). E.g. Banksia sphaerocarpa (var. dolichostyla is Threatened Flora in WA: https://florabase.dpaw.wa.gov.au/search/quick?q=banksia+sphaerocarpa but B. sphaerocarpa  [as a species] has no listing).

By comparison, Tetratheca paynterae has two subspp. [paynterae & cremnobata], both in Coolgardie IBRA region, both are Threatened in WA; species name is EPBC-listed so T. paynterae is listed in the Conservation Status column. Tetratheca aphylla has one Threatened subsp. in Coolgardie IBRA + one in an adjacent bioregion, but is EPBC-listed at species rank so is also listed in Conservation Status column. These are in green. Tetratheca harperi (blue) doesn't have any subspecies but is Threatened in WA + EPBC-listed.

All  of these discrepancies can be dealt with if the "Species checklist" is a "Taxon checklist" and all the infrataxa are presented separately with their individual conservation listings.
[Coolgardie_test2.xlsx](https://github.com/AtlasOfLivingAustralia/ala-downloads/files/1056842/Coolgardie_test2.xlsx)

**Comment by nickdos** [comment]
My take on this issue...

User performs a biocache search and clicks the download link. They select the "species checklist" option and reason code, click submit. The resulting CSV file has a column called `Conservation` and the values include a pipe-separated list of values that look like:

```
South Australia : Conservation Status | Queensland : Conservation Status | Victoria : Conservation Status
```

depending on which states the species is located in.

Users are asking for the associated conservation status value to be included here. So it might look like:

```
South Australia : Critically endangered | Queensland : least concern | Victoria : vulnerable
```

The `Conservation status` text can be removed as it is redundant - the column already has `Conservation` label.

**Comment by timhicks-ala** [comment]
Related to user request https://support.ehelp.edu.au/a/tickets/138873

**Comment by adam-collins** [comment]
Replaced by https://github.com/AtlasOfLivingAustralia/biocache-service/issues/538
