### ISSUE TITLE
User assertions details service seems to be broken on test site

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#744]
Only seeing this on the test site.

https://biocache-ws-test.ala.org.au/ws/occurrences/b5f14b18-8a97-4e67-9066-c4195d3848a1 reports hasUserASsertions=true but
https://biocache-ws-test.ala.org.au/ws/occurrences/b5f14b18-8a97-4e67-9066-c4195d3848a1/assertions shows no results (empty JSON array).

So on biocache-test.ala.org.au, I'm not seeing any user assertion (annotations) entries on records, due to the second service always returning an empty array.

**Comment by qifeng-bai** [comment]
Solr returns hasUserAssertions = true, userAssertionStatus: "50003",
Cassandra returns the size of UserAssertions = 0

**Comment by nickdos** [comment]
@djtfmartin any ideas why Cassandra might be out of sync with SOLR?

**Comment by javier-molina** [comment]
Isn't the case that the sync job has not run to update the Solr index with the latest version of assertions in Cassandra? 

Still leaves the question on why, presumably, assertions disappeared from Cassandra, Could it be a database refresh performed recently?

**Comment by adam-collins** [comment]
Looks ok on test.
