### ISSUE TITLE
Add eventID, parentEventID and datasetName into occurrence result 

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/biocache-service#751]
Add eventID, parentEventID and datasetName into occurrence result
linked to EDM project: https://github.com/AtlasOfLivingAustralia/extended-data-model/issues/29

Search by all event fields: event id, parent event id, field number etc
linked to EDM project: https://github.com/AtlasOfLivingAustralia/extended-data-model/issues/43

Enable partial search on datasetName (datasetName in SOLR has been copyTo text_datasetName) - 16/Jun/2022

TODO
Enable partial  search on eventID, parentEventID and field_number 

- Require SOLR schema updates: add text_eventID, text_parentEventID and text_fieldNumber into SOLR schema and ask index rebuilt

**Comment by adam-collins** [comment]
appears done
