### ISSUE TITLE
Add additional description to API documentation

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/biocache-service#762]
Current API swagger docs in  docs test portal include API descriptions added in the biocache-service methods themselves. 

1.  TODO - Add additional descriptions as requied to methods. 
2. TOOD - Export openapi specs file from the application and add new diff(excluding deprecated APIs) to the specs which will be displayed on the docs portal _(New seagger specs JSON file will  be added relevant branch in the aws api gateway [repo](https://github.com/AtlasOfLivingAustralia/aws-apig-cognito ) - which will deploy to the relevant S3 bucket via AWS CICD )_

**Comment by sughics** [comment]
Relevant brach for updates: https://github.com/AtlasOfLivingAustralia/biocache-service/tree/feature/issue-762-api-descriptions

**Comment by adam-collins** [comment]
Further work will be done under https://github.com/AtlasOfLivingAustralia/biocache-service/issues/833
