### ISSUE TITLE
map image snapshot not working

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/biocache-service#763]
Map image snapshot is used by profiles to create image of occurrences. Example requests is

https://biocache-ws-test.ala.org.au/ws/mapping/wms/image?q=lsid:https://id.biodiversity.org.au/node/apni/2917194%20AND%20(data_resource_uid:dr382%20OR%20data_hub_uid:dh2)&extents=69.60937499999999,-49.15296965617039,205.3125,43.58039085560784&outlineColour=0&dpi=300&scale=off&baselayer=aus1&fileName=occurrencemap.jpg&format=jpg&outline=true&popacity=1&pradiuspx=5&pcolour=D47500

**Comment by sughics** [comment]
Included in 3.1.3 release

**Comment by temi** [comment]
Image generation works. However, content-disposition pattern profiles expects is 
"attachment; filename=\"occurrencemap.jpg\"". It currently does not have the quote around filename.

**Comment by temi** [comment]
After testing a bit more, It appears to be an issue with content-type. The production biocache has `application/octet-stream;charset=UTF-8` while test `application/octet-stream`. This causes profiles to behave differently which results in not showing the map image.

**Comment by temi** [comment]
tested on biocache-ws-dev and working with profiles

**Comment by sughics** [comment]
Released with 3.1.4
