### ISSUE TITLE
Issues with download CSV file: newlines, etc.

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#77]
Reported by Bob Mesibov:

From the ALA issues and docs (archived):

"Issue 595:     Issues with occurrence download csv data
Source data with newline characters is something that may need to be addressed in the future.  If this is the case a new issue should be opened."

The problem isn't that the source data has embedded newline characters, it's that ALA doesn't remove them. Instead it faithfully preserves these characters and puts them in the CSV for download, where they become a traffic hazard for data processing.

Excel and R (see issue 595 thread, above) are only two of the frameworks within which downloaded data can be processed. Removing the newlines makes the CSV 'framework-agnostic' and allows for wider re-use of the data.

I process ALA downloads on the command line under Linux. My latest download was the 457076-record 'Coleoptera' data set on 2 December. I converted 'beetles.csv' to a TSV with sed 's/^"//;s/","/\t/g;s/"$//' beetles.csv > beetles, then checked for broken records:

awk -F"\t" '{print NF}' beetles | sort | uniq -c
23  18
17  4
23  57
17  71
457037 74

Not good, and I had to find and fix the 40 broken records manually. 23 of the line breaks are in the 'Locality' field - '/' in this list indicates line break position:

Lloyd Island /{other printed label Claudie River coll'd J.A.Kershaw} (18 records; dr342, Museum Victoria provider for OZCAM)
Strzelecki Ranges, Gunyah - Toora Road, 2km SSW of Gunyah Gunyah/Nothophagus cunninghamii forest (1 record; dr342, Museum Victoria provider for OZCAM)
Puttapa Gap 0 dir, AU SA_/x000D_Mareeba 11NW, AU (1 record; dr742, South Australian Museum Terrestrial Invertebrate Images)
Mount Barker 0 dir, AU WA/Mount Barker 0 dir, AU WA (1 record; dr742, South Australian Museum Terrestrial Invertebrate Images)
141 McBryde Terrace, Whyalla SA 5600, Australia/Across the road in Wilson Park (1 record; dr364, individual sighting)
Wentworth Rd, Vaucluse NSW 2030, /Nielsen Park (1 record; dr364, individual sighting)

Another 16 breaks are in the 'Scientific Name' field:

Ischnosoma/Arthropoda Hexapoda Insecta Coleoptera Polyphaga Staphylinidae (16 records; dr344, Queensland Museum provider for OZCAM)

The last break is also in the 'Scientific Name' field. Here's the record in the original CSV:

"8898779e-a8f5-45ba-9141-9d6fdfec3049","T174974","urn:lsid:biodiversity.org.au:afd.taxon:9877bf9f-8c68-4425-b728-9213b0390f95","Stigmodera (Castiarina) fossoria

Castiarina fossoria","","Stigmodera","genus","","ANIMALIA","ARTHROPODA","INSECTA","COLEOPTERA","BUPRESTIDAE","Stigmodera","","QM","Entomology","Ferntree Gully","-37.883333","145.3","","-37.883333","145.3","","Australia","Victoria","Knox (C)","","","","","Preserved specimen","PreservedSpecimen","Female","","noIssue","dr344","Queensland Museum provider for OZCAM","false","true","false","false","false","false","false","false","false","false","false","false","false","false","false","true","false","false","false","false","false","false","false","false","false","false","false","false","false","false","false","false","false","false","false","false"

This specimen, T174974 in QM, is a paratype of fossoria, but as you can see ALA incorrectly calls it a genus record for Stigmodera. The OZCAM upload gives 'Stigmodera (Castiarina)' for Genus and 'fossoria' for Specific Epithet, but in classifying this record ALA gave priority to its parsing of the broken string 'Stigmodera (Castiarina) fossoria/Castiarina fossoria'. It's not clear why the second line wasn't ignored in this field, as in the 16 Ischnosoma cases above.

Regards,
## Bob

Dr Robert Mesibov
Honorary Research Associate
Queen Victoria Museum and Art Gallery
Launceston, Tasmania, Australia

**Comment by adam-collins** [comment]
fileType=tsv is available for bioache service downloads. Is this enough for this issue?

**Comment by adam-collins** [comment]
api.ala.org.au updated.
