### ISSUE TITLE
DQ assertion COORDINATE_PRECISION_UNCERTAINTY_MISMATCH deprecated but appears in record list

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocache-service#776]
There are no records in biocache: https://biocache.ala.org.au/occurrence/search?q=assertions%3A%22COORDINATE_PRECISION_UNCERTAINTY_MISMATCH%22&qualityProfile=ALA#tab_mapView

The DQ spreadsheet says it's deprecated: https://docs.google.com/spreadsheets/d/1tAfQUsIzUNfa6Tn5Ezq2cfbMVB0QeXIyp7N0We2lBAY/edit?hl=en_US&hl=en_US#gid=820855861

The test appears as Passed on records: https://biocache.ala.org.au/occurrences/f3c71307-c371-491c-83cc-3bd0f05376d8

Same deal with COORDINATE_ACCURACY_INVALID

cc: @peggynewman

**Comment by sat01a** [comment]
Will be addressed in 3.1.6

**Comment by adam-collins** [comment]
Change to exclude all deprecated occurrences.

https://github.com/AtlasOfLivingAustralia/biocache-service/pull/808

**Comment by sughics** [comment]
Released with [3.2.1](https://github.com/AtlasOfLivingAustralia/biocache-service/releases/tag/3.2.1)
