### ISSUE TITLE
BIE map doesn't apply ALA General DQ profile

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocache-service#777]
Example: common brown snake:

15,084 records on bie:
https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/57cc6794-0fd0-4a5d-a18c-18cff323d06b

14,145 records filtered by ALA General DQ profile:
https://biocache.ala.org.au/occurrences/search?q=lsid:https://biodiversity.org.au/afd/taxa/57cc6794-0fd0-4a5d-a18c-18cff323d06b#tab_recordsView

The BIE should apply the DQ profile.

cc: @peggynewman

**Comment by sat01a** [comment]
Feature request added to the backlog.

**Comment by sughics** [comment]
Closing this issue as it has now been moved to BIE hub repo. https://github.com/AtlasOfLivingAustralia/ala-bie-hub/issues/20
