### ISSUE TITLE
Perpetual "Loading legend..." when colouring points on Biocache map

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-service#779]
On any Biocache search, go to the Map tab, then "Colour by:" and select any option. The map dots load in different colours correctly, but the legend only shows "Loading legend...".

Reported in:
https://support.ehelp.edu.au/a/tickets/164422
https://support.ehelp.edu.au/a/tickets/164162
https://support.ehelp.edu.au/a/tickets/163945
https://support.ehelp.edu.au/a/tickets/170771

![Image](https://user-images.githubusercontent.com/57081387/208036209-72b63ccd-397d-42d4-a5ee-0a5ada80289f.png)

**Comment by sughics** [comment]
Also looking into #780

**Comment by sughics** [comment]
Fix currently live on biocache-service dev instance. Legend loading as expected https://biocache-dev.ala.org.au/occurrences/search?q=taxa%3A%22koala%22#tab_mapView

**Comment by sughics** [comment]
Included in release 3.2.0
