### ISSUE TITLE
"Species count: Loading..." performing spatial search on Biocache

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-service#780]
On the Map tab in any Biocache search, if you perform a Spatial search, the pop-up will show the count of occurrence records, but the number of species will always show "Loading...". This happens even for a single-species search.

Reported in:
https://support.ehelp.edu.au/a/tickets/164162

![Image](https://user-images.githubusercontent.com/57081387/208036862-101a2972-fb16-4fe3-903b-9d9406984dbd.png)

**Comment by sughics** [comment]
Issue being addressed in #779

**Comment by sughics** [comment]
This is a biocache-hubs issue and has been addressed here: https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/561

**Comment by sughics** [comment]
Included in release 3.2.0
