### ISSUE TITLE
New dataset downloads aren't currently added to My Downloads list

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/biocache-service#782]
When downloading a set of records from the ALA, no new download is currently recorded in the myDownloads page: https://doi.ala.org.au/myDownloads

The "Download Complete" email is correctly sent/received, and DOI minting appears to work, however there is no reference to new downloads on that page. My last listed download is from 13/11/2022 despite several test downloads in December.

Issue discovered by me, not yet reported by a user.

**Comment by sughics** [comment]
Changes already incorporated in https://github.com/AtlasOfLivingAustralia/biocache-service/pull/785.
