### ISSUE TITLE
BioCache Downloads - Unique queue for each user + Cancelling jobs in queue

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocache-service#786]
- [x] Analysis 
- [x] Design
- [x] Implementation
- [x] Cancelling the jobs [Only with JWT]
- [x] Admin can cancel the jobs
- [x] Users can cancel their job
- [x] Limiting number of jobs per user
- [x] UI to cancel the Job
- [x] Followup - Security for BioCache service authentication 
- [x] Testing

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/doi-service/pull/83
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/788

**Comment by sughics** [comment]
- Changes includes in biocache-service release 3.2.0
- DOI UI Changes included in upcoming release of doi-service - likely 3.0.0

**Comment by sughics** [comment]
Released with [3.2.0](https://github.com/AtlasOfLivingAustralia/biocache-service/releases/tag/3.2.0)
