### ISSUE TITLE
dynamicProperties not shown as Additional Properties in Biocache-hub

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/biocache-service#787]
Some recent records have `dynamicProperties` as one of the fields in their occurrence but the `miscProperties` in biocache-service is empty.
Here is a sample record in Solr https://biocache.ala.org.au/occurrences/a34e2843-6233-4f78-9a8b-b1a408df036f :

![image](https://user-images.githubusercontent.com/532845/227060455-cd23e4dc-02b2-449a-b4d5-426db6b30905.png)

While the `miscProperties` is empty in biocache-service API call:
https://biocache.ala.org.au/ws/occurrences/a34e2843-6233-4f78-9a8b-b1a408df036f

**Comment by nickdos** [comment]
Was looking at a random record just now and saw it has `miscProperties` in the `raw` section: https://biocache-ws.ala.org.au/ws/occurrence/8c98a570-eaa3-44ff-a9b7-31a89980776f so it seems that the bug must be data-related in some way. 

The example in SOLR above seems to be missing a comma, maybe? 
![image](https://user-images.githubusercontent.com/532845/227060061-23144f53-80b9-43da-9343-7c6bb8615412.png)

**Comment by sat01a** [comment]
Thanks @nickdos . @sadeghim did you check the data?

**Comment by sadeghim** [comment]
@sat01a Yes, as @nickdos has pointed out the problem is the incorrect syntax of JSON. But there is no indication anywhere saying that the format is wrong. I don't see it as a bug now, but there should be somewhere in the log mentioning that.
Happy to close this one.

**Comment by sat01a** [comment]
Thanks @sadeghim, please close the ticket.
