### ISSUE TITLE
WMS reflect - no dots showing for matched_name_children queries

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#79]
Bug reported for AVH - no dots showing on maps:

http://avh.ala.org.au/occurrences/search?q=%28matched_name_children%3A%22Cassytha+pubescens+%22+OR+matched_name_children%3A%22Cassytha+filiformis%22%29#tab_mapView

Looks like a bug as the individual records in the records list have lat/lng and show a marker on their map view.

**Comment by adam-collins** [comment]
service.bie.enabled=true makes it work. This was not set on the mapping server.

Looking into SpeciesLookupIndexService to find the reason.

**Comment by adam-collins** [comment]
Fixed by https://github.com/AtlasOfLivingAustralia/biocache-service/commit/b998e55fdded022892a8b81e0245f2b2e1035920
