### ISSUE TITLE
Biocache-service `/cache/refresh` not working as expected

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-service#799]

**Comment by adam-collins** [comment]
https://biocache.ala.org.au/ws/occurrence/facets?q=data_resource_uid%3A%22dr21567%22&facets=data_resource_uid&flimit=100  was failing to lookup the new data resource name.

- Confirm that the ```@Scheduled(fixedDelay = 3600000L) //every hour
    public void updateCache() {``` schedule is working.

- Confirm that `/cache/refresh` is triggering the same.

- Add a script to airflow that will refresh the cache on each biocache-service instance (-1, -2, -downloads)

**Comment by adam-collins** [comment]
- enabled scheduling https://github.com/AtlasOfLivingAustralia/biocache-service/commit/b38852877e5c37da3be35666ce42bf08a442d0b7
- `cache/refresh` appears to be working correctly

**Comment by sughics** [comment]
Released with  [3.2.0](https://github.com/AtlasOfLivingAustralia/biocache-service/releases/tag/3.2.0)
