### ISSUE TITLE
searches on data sets and collections failing

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/biocache-service#80]
http://biocache.ala.org.au/occurrence/search?q=data_resource_uid:dr346

An error has occurred

    Error: unknown

    No record found with id: search

this has also happened with data sets -e.g  http://biocache.ala.org.au/occurrence/search?q=data_resource_uid:dr346

searches by taxa are ok - 
http://biocache.ala.org.au/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A9e6a0bba-de5b-4465-8544-aa8fe3943fab

uptime showing everything is working...

**Comment by djtfmartin** [comment]
i presume this was an operational thing and has been sorted. closing
