### ISSUE TITLE
Biocache not returning same preferred common name as BIE

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/biocache-service#812]
We currently have an issue where the Biocache is not returning the same preferred common name as the BIE. 

For example: _Chenonetta jubata_ comes back as 'Australian Wood Duck' in BIE: https://bie.ala.org.au/species/https://biodiversity.org.au/afd/taxa/7954bd26-ddb3-4e7e-823c-4a692b7bde74
but as 'Australian Wood Duckmaned Goose' in Biocache results - see number 27 on this list: https://biocache.ala.org.au/explore/your-area#-37.7975%7C144.9805%7C12%7CALL_SPECIES

Just to be clear the name in BIE is correct: 'Australian Wood Duckmaned Goose' comes from our friends across the ditch in NZ.

Raised by @Sherrin-ALA

**Comment by adam-collins** [comment]
This is a problem with the name matching service. e.g. `curl -X GET "http://namematching-ws.ala.org.au/api/search?q=Chenonetta%20jubata" -H "accept: application/json"`

The problem resides in the name index generation. The BIE SOLR index is returning a different result than the name matching service.

**Comment by adam-collins** [comment]
- The name matching service returns the first vernacular name match.
- The BIE returns all the vernacular names, sorts with priority and current language, then returns the best match.

For consistency, name matching can do the same if the `priority` value that is in the BIE index is also in the name matching vernacular index.

**Comment by adam-collins** [comment]
For the given example the priority value is `400` (`miscellaneousLiterature`) for the common name that is shown in the BIE. All other common names for the example have a priority value of `300` (`local`).

**Comment by adam-collins** [comment]
It appears that Doug made changes to https://github.com/AtlasOfLivingAustralia/ala-name-matching to do this change.

**Comment by adam-collins** [comment]
This should be addressed by the new names index but a new release of `ala-name-matching` may be required.

Confirming the status of this issue with the data team.

**Comment by adam-collins** [comment]
I can confirm that this is fixed in the names index in development and the `name-matching-service` develop branch.
