### ISSUE TITLE
Date precision is incorrect in many records (pipelines)

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocache-service#815]
eg here precision is MINUTE not DAY
https://biocache-test.ala.org.au/occurrences/4c433838-cace-4ab3-bb01-143d44a9f2af

**Comment by adam-collins** [comment]
Discussion required. 

- `datePrecision` appears to be determined by the length of the `raw_eventDate`.
- Records marked `datePrecision:YEAR` do not have a processed `eventDate`.
- Records marked `datePrecision:MONTH` appear to include records that do have a `day` or `eventDate` value. This `datePrecision` is incorrect for some records and inconsistent with the absence of `eventDate` for records only containing `year`. Initial investigation identified that some have `eventDate` of the form `yyyy-mm` but may also include a `day` value that is used to produce a complete `eventDate` without updating `datePrecision` to `DAY`.
- The alteration of `datePrecision` to `dateTimePrecission` is not recommended as too many assumptions are required. The issue states that the precision is `MINUTE` for the example record but the presence of `00` in the raw second value indicates that the correct precision is `SECOND`. 

I suggest this issue not be addressed beyond fixing the errors identified in the `datePrecision:MONTH` records.

**Comment by djtfmartin** [comment]
I concur with @adam-collins. I also suggest transferring this issue to gbif/pipelines repo.

**Comment by adam-collins** [comment]
Moving to pipelines https://github.com/gbif/pipelines/issues/919

**Comment by adam-collins** [comment]
This is in the current snapshot version
