### ISSUE TITLE
Organism quantity integer is changed to float in record view (biocache)

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocache-service#816]
eg https://biocache-test.ala.org.au/occurrences/4c433838-cace-4ab3-bb01-143d44a9f2af

**Comment by adam-collins** [comment]
Clarification required. There are occurrences without whole number quantities, e.g. https://biocache.ala.org.au/occurrences/search?q=organismQuantity:0.6667

**Comment by adam-collins** [comment]
@peggynewman what are your thoughts?

**Comment by peggynewman** [comment]
<img width="654" alt="image" src="https://github.com/AtlasOfLivingAustralia/biocache-service/assets/1271932/40104ea0-a7c3-459a-8426-eaa7c50885eb">

My thoughts are that it should probably just be displayed as provided, otherwise we are insinuating meaning ourselves.

**Comment by adam-collins** [comment]
The suggestion is to remove the processed organismQuantity value. This is a `Double` value stored as a `String` in SOLR. There is no associated quality assertion when a non-parsable `Double` value is supplied.

Some options that I think are in line with this request:
- Remove the processed `organismQuantity`, deviating from the GBIF pipeline process.
- Remove the processed `organismQuantity` from the GBIF pipeline. This would align GBIF with the example  `BraunBlanquetScale` and similar.
- Alter the processed `organismQuantity` value stored in the SOLR `String` field to remove the `.0`.
- Display only the `raw_organismQuantity` in on biocache page. This would only ignore the processed `organismQuantity` on that one page.
- Use the `biocache-service` field translation to replace all requests of `organismQuantity` with the `raw_organismQuantity`. This avoids pipeline changes but could produce a download with the field duplicated.

Of interest may be the unprocessed `raw_organismQuantity` values https://biocache.ala.org.au/ws/occurrences/search?q=raw_organismQuantity:*&fq=-organismQuantity:*&facet=true&facets=raw_organismQuantity&pageSize=0&flimit=-1

**Comment by peggynewman** [comment]
The above was from the sampling-event docs for the IPT. This is the DwC definition: 
<img width="867" alt="image" src="https://github.com/AtlasOfLivingAustralia/biocache-service/assets/1271932/1c1e927d-a706-41d4-8bff-b04bff947276">

The values that didn't process are a lot of ranges, and those that did are either integers or floats, with quite a few integers being estimates (eg "25000") so to add the precision of a `.0` isn't helpful I don't think.

My take is to follow the standard as closely as we can, so option #2 looks best for me. If the GBIF pipeline needs changing then we can do that. What do you think?

**Comment by adam-collins** [comment]
Moving the issue to https://github.com/gbif/pipelines/issues/922

**Comment by adam-collins** [comment]
pull request https://github.com/gbif/pipelines/pull/1002

**Comment by peggynewman** [comment]
1 is no longer 1.0 https://biocache-test.ala.org.au/occurrences/4c433838-cace-4ab3-bb01-143d44a9f2af
0.667 still works https://biocache-test.ala.org.au/occurrences/search?q=organismQuantity:0.6667#tab_recordsView
raw_organismQuantity is gone
LGTM, tick
