### ISSUE TITLE
Map clicks in biocache UI fail - gateway mapping related error

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-service#819]
When clicking the points on the map in biocache UI, the call to the gateway fails in test.

Underlying call:

https://api.test.ala.org.au/occurrences/occurrences/info?q=*%3A*&qualityProfile=ALA&fq=contentTypes%3A%22GenomicDNA%22&zoom=12&lat=-10.782386474660953&lon=142.4674415588379&radius=0.15&format=json

which gives:

```
 The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing)
```

the successful URL would look like

https://biocache-ws-test.ala.org.au/ws/occurrences/info?q=*%3A*&qualityProfile=ALA&fq=contentTypes%3A%22GenomicDNA%22&zoom=12&lat=-10.782386474660953&lon=142.4674415588379&radius=0.15&format=json

which gives

```json

{
"count": 1,
"occurrences": [
"603312de-1dcb-45df-b536-dfedf178795f"
]
}
```

**Comment by sughics** [comment]
API Gateway specs updated to handle above request.

**Comment by adam-collins** [comment]
appears done
