### ISSUE TITLE
Error on Search for Records in this area

### ISSUE THREAD

**Issue by Tasilee** [AtlasOfLivingAustralia/biocache-service#82]
Search for Lasioglossum
click on Occurrences (55,991)
Map
Zoom/pan to area containing some observations
Rectangle tool to define area
Click on "Search for Records in this area" and you will get

An error has occurred
Error: unknown
data may not be null

![1](https://cloud.githubusercontent.com/assets/6656350/12970361/fd003bc8-d0e1-11e5-9df0-e7beeeaf9f46.png)
![2](https://cloud.githubusercontent.com/assets/6656350/12970371/10550c1c-d0e2-11e5-9f66-c5188ccae139.png)

Error occurs 100% of the time.

**Comment by adam-collins** [comment]
An empty param qc in hubs url is the cause.

**Comment by nickdos** [comment]
Deployed &tested - as version 1.8.6. today.
