### ISSUE TITLE
Investigate why some downloads block the queue

### ISSUE THREAD

**Issue by joe-lipson** [AtlasOfLivingAustralia/biocache-service#820]
Possibly related to or already fixed by https://github.com/AtlasOfLivingAustralia/biocache-service/issues/786

Some biocache downloads take a few hours to complete and have been blocking the queue, often these blocking downloads have a small number of rows and the records and totalRecords values in the queue are the same.

This was most recently reported as an issue on July 4th where the top 3 running queries appeared stuck for over 3 hours.

The top stuck queries were

```
"running",7278,"4a2afd28-b62f-3d99-91b5-c19c9df59c93-1688435701591","wcornwell@gmail.com","Tue Jul 04 11:55:01 AEST 2023"
"running",15,"19f12a0b-1ab2-33e5-bfab-bfc872953967-1688436389397","e.fuaux@bigpond.com","Tue Jul 04 12:06:29 AEST 2023"
"running",180,"36ec76a5-8b47-3ed1-99fe-699316e5fc81-1688438754888","michael.tucak@gmail.com","Tue Jul 04 12:45:54 AEST 2023"

```

When the first one cleared at 3:19pm the remaining 21 jobs completed within around 5 minutes so possibly there was something going on with that one

**Comment by adam-collins** [comment]
With the deployment of the new download related code this is no longer relevant.
