### ISSUE TITLE
Make OFFICIAL_DOI_RESOLVER value configurable

### ISSUE THREAD

**Issue by sughics** [AtlasOfLivingAustralia/biocache-service#822]
Make OFFICIAL_DOI_RESOLVER value in biocache-service configurable - currently it is hardcoded to "https://doi.org/" i.e. valid for prod
On download email sent to user from biocache-service test and dev servers, it still includes the prod value.

**Comment by adam-collins** [comment]
pull request https://github.com/AtlasOfLivingAustralia/biocache-service/pull/864

**Comment by peggynewman** [comment]
DOI in test doi.txt download is https://doi.org/10.80416/
In prod doi/10.26197
seems to be all good
