### ISSUE TITLE
Add the option for POST for select endpoints in the common APIs page

### ISSUE THREAD

**Issue by acbuyan** [AtlasOfLivingAustralia/biocache-service#826]
Endpoints:

```/biocache/occurrences/offline/download```
```/biocache/occurrences/facets/download```
```/biocache/occurrences/search```

**Comment by sughics** [comment]
- `POST /occurrences/offline/download`-   already supported by [biocache-service](https://docs.test.ala.org.au/openapi/index.html?urls.primaryName=occurrences#/Download/occurrenceDownload_1), an additional resource path for the POST option can be added to the common api list 
 - `POST /biocache/occurrences/facets/download` - POST not supported by biocache-service - need to be added to biocache-service and all published API spec list
 - `POST/biocache/occurrences/search`  -  POST not supported by biocache-service - need to be added to biocache-service and all published API spec list

**Comment by adam-collins** [comment]
Pull request https://github.com/AtlasOfLivingAustralia/biocache-service/pull/864

**Comment by peggynewman** [comment]
close when these are added to the docs portal

**Comment by adam-collins** [comment]
Created an issue in the docs portal.
