### ISSUE TITLE
Add `pageSize` for offline downloads API (occurrences/offline/download)

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-service#829]
**1. Add `pageSize` for offline downloads API**

Request to add `pageSize` to offline downloads API to enable galah users to check result output before downloading all records. (Chat thread on [Slack](https://atlaslivingaustralia.slack.com/archives/C03EJ7ARZQW/p1691107057956599?thread_ts=1691039080.758909&cid=C03EJ7ARZQW) if further info required) 

requested by @mjwestgate

**2. Update to API docs**

The API docs on [Swagger](https://docs.ala.org.au/openapi/index.html?urls.primaryName=occurrences#/) show additional arguments that do not work for occurrences/offline/download. These should be removed to avoid confusion.

These arguments include `dir` but there may be others.

**Comment by adam-collins** [comment]
The intended use is to preview results. Some considerations.
- There should be a configurable limit on the maximum number of records permitted in the preview. e.g. 5.
- DOI should not be minted when previewing.
- email notifications should be disabled for previews.
- logging of a download request should be disabled.
- The generated citation can remain.
- The generated header file should remain.
- A new webservice is unnecessary. The download service throttles to one request at a time per user.

Any additional thoughts @djtfmartin ?

**Comment by adam-collins** [comment]
The provided pageSize must differ from the default pageSize of 10

**Comment by djtfmartin** [comment]
@adam-collins I am wondering if this requirement would be better served with a newer version (v2) of the /occurrence/search JSON API that returned the full darwin core record - which would be closer to the set of fields in download. 

Currently the [/occurrences/search](https://biocache-ws.ala.org.au/ws/occurrences/search?pageSize=1) just returns a small number of fields that where there to just support the UI - not very useful as a general application.

@mjwestgate how does this sound ?

this is probably just a different way of thinking of it, but i've thought for some time that we would have a better JSON occurrence search service that allowed access to a bigger range of the fields indexed.
