### ISSUE TITLE
FIRST_OF_YEAR assertion is returned on non first of year dates

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocache-service#831]
During a demo I noticed this record https://biocache.ala.org.au/occurrences/365ab85d-9c18-4030-bf3d-39e9427e7dd7
has eventDate 2004-01-18
but also has incurred a FIRST_OF_YEAR assertion

Then see that it comes up for this date too: 1996-01-19 
see https://biocache-ws.ala.org.au/ws/occurrences/search?q=assertions:FIRST_OF_YEAR&facet=true&facets=eventDate&pageSize=0

Reported by @peggynewman

**Comment by adam-collins** [comment]
This is a pipelines issue

**Comment by adam-collins** [comment]
https://github.com/gbif/pipelines/pull/947

**Comment by adam-collins** [comment]
In version 2.18.0-SNAPSHOT

**Comment by adam-collins** [comment]
Test
https://biocache-test.ala.org.au/occurrences/365ab85d-9c18-4030-bf3d-39e9427e7dd7 does not have first of year assertion.
https://biocache.ala.org.au/occurrences/365ab85d-9c18-4030-bf3d-39e9427e7dd7 has first of year assertion

**Comment by peggynewman** [comment]
All good, this facet is good too: https://biocache-ws.ala.org.au/ws/occurrences/search?q=assertions:FIRST_OF_YEAR&facet=true&facets=eventDate&pageSize=0
