### ISSUE TITLE
change user annotation value

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/biocache-service#832]
Suggest that we change the user assertion status
`Corrected by data custodian`
to 
`Corrected via data refresh`

Also, tick the `Notify me when records I have annotated are updated` by default

Requested by @peggynewman

**Comment by adam-collins** [comment]
commit https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/e91d3a999e6a111e3d8bf94008e460bf9fbc0e90
