### ISSUE TITLE
Application error on download - wkt multi polygons

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-service#834]
An Application error has been reported by a user when attempting a download, and has been replicated by our team - 

![Image](https://user-images.githubusercontent.com/90439797/262180968-15ce60f0-f4ef-47e9-a3dc-892bc5a8811b.png)

The URL is:

https://biocache.ala.org.au/download/options2?searchParams=%3Fq%3D*%253A*%26qualityProfile%3DALA%26fq%3Dspecies_group%253A%2522Reptiles%2522%26qc%3D-_nest_parent_%253A*%26wkt%3DMULTIPOLYGON%28%28%28131.14105224609375%2520-12.229188504764602%252C131.12952410864662%2520-12.229897092656154%252C131.1181775933548%2520-12.232011692769177%252C131.10719146953133%2520-12.235498989772399%252C131.09673884508746%2520-12.240304039903442%252C131.08698444588367%2520-12.246351134165792%252C131.07808202531564%2520-12.253544987973964%252C131.07017194452442%2520-12.26177223875249%252C131.06337896107772%2520-12.27090322818549%252C131.05781026084807%2520-12.280794041353518%252C131.0535537641571%2520-12.291288770950992%252C131.05067673310572%2520-12.302221971214191%252C131.04922470242676%2520-12.31342126316333%252C131.04922075123704%2520-12.324710050322047%252C131.05066512780343%2520-12.335910302265669%252C131.05353523394334%2520-12.346845362198192%252C131.0577859700406%2520-12.357342734290556%252C131.06335043595348%2520-12.36723680674208%252C131.07014097741884%2520-12.376371467455044%252C131.0780505620044%2520-12.384602570830396%252C131.0869544633228%2520-12.391800216479517%252C131.09671222719385%2520-12.39785080357136%252C131.1071698888087%2520-12.402658828052589%252C131.11816240580322%2520-12.406148394036626%252C131.12951626855912%2520-12.408264415192019%252C131.14105224609375%2520-12.408973486897692%252C131.15258822362838%2520-12.408264415192019%252C131.16394208638428%2520-12.406148394036626%252C131.1749346033788%2520-12.402658828052589%252C131.18539226499365%2520-12.39785080357136%252C131.1951500288647%2520-12.391800216479517%252C131.2040539301831%2520-12.384602570830396%252C131.21196351476866%2520-12.376371467455044%252C131.21875405623402%2520-12.36723680674208%252C131.2243185221469%2520-12.357342734290556%252C131.22856925824416%2520-12.346845362198192%252C131.23143936438407%2520-12.335910302265669%252C131.23288374095046%2520-12.324710050322047%252C131.23287978976074%2520-12.31342126316333%252C131.23142775908178%2520-12.302221971214191%252C131.2285507280304%2520-12.291288770950992%252C131.22429423133943%2520-12.280794041353518%252C131.21872553110978%2520-12.27090322818549%252C131.21193254766308%2520-12.26177223875249%252C131.20402246687186%2520-12.253544987973964%252C131.19512004630383%2520-12.246351134165792%252C131.18536564710004%2520-12.240304039903442%252C131.17491302265617%2520-12.235498989772399%252C131.1639268988327%2520-12.232011692769177%252C131.15258038354088%2520-12.229897092656154%252C131.14105224609375%2520-12.229188504764602%29%29%29&targetUri=%2Foccurrences%2Fsearch&downloadType=records&email=&reasonTypeId=4&sourceTypeId=0&downloadFormat=dwc&file=records-2023-08-20&layers=&customHeader=&fileType=csv&layersServiceUrl=
 

I have also tried with a shorter URL, getting the same error.

URL tried:

https://biocache.ala.org.au/download/options2?searchParams=%3Fq%3D*%253A*%26qualityProfile%3DALA%26fq%3Dspecies_group%253A%2522Reptiles%2522%26qc%3D-_nest_parent_%253A*%26wkt%3DMULTIPOLYGON%28%28%28131.14105224609375%2520-12.229188504764602%252C131.12952410864662%2520-12.229897092656154%252C131.1181775933548%2520-12.232011692769177%252C131.10719146953133%2520-12.235498989772399%252C131.09673884508746%2520-[12.229188504764602%29%29%29&targetUri=%2Foccurrences%2Fsearch&downloadType=records&email=&reasonTypeId=4&sourceTypeId=0&downloadFormat=dwc&file=records-2023-08-20&layers=&customHeader=&fileType=csv&layersServiceUrl=](https://biocache.ala.org.au/download/options2?searchParams=%3Fq%3D*%253A*%26qualityProfile%3DALA%26fq%3Dspecies_group%253A%2522Reptiles%2522%26qc%3D-_nest_parent_%253A*%26wkt%3DMULTIPOLYGON%28%28%28131.14105224609375%2520-12.229188504764602%252C131.12952410864662%2520-12.229897092656154%252C131.1181775933548%2520-12.232011692769177%252C131.10719146953133%2520-12.235498989772399%252C131.09673884508746%2520-12.240304039903442%252C131.08698444588367%2520-12.246351134165792%252C131.07808202531564%2520-12.253544987973964%252C131.07017194452442%2520-12.26177223875249%252C131.06337896107772%2520-12.27090322818549%252C131.05781026084807%2520-12.280794041353518%252C131.0535537641571%2520-12.291288770950992%252C131.05067673310572%2520-12.302221971214191%252C131.04922470242676%2520-12.31342126316333%252C131.04922075123704%2520-12.324710050322047%252C131.05066512780343%2520-12.335910302265669%252C131.05353523394334%2520-12.346845362198192%252C131.0577859700406%2520-12.357342734290556%252C131.06335043595348%2520-12.36723680674208%252C131.07014097741884%2520-12.376371467455044%252C131.0780505620044%2520-12.384602570830396%252C131.0869544633228%2520-12.391800216479517%252C131.09671222719385%2520-12.39785080357136%252C131.1071698888087%2520-12.402658828052589%252C131.11816240580322%2520-12.406148394036626%252C131.12951626855912%2520-12.408264415192019%252C131.14105224609375%2520-12.408973486897692%252C131.15258822362838%2520-12.408264415192019%252C131.16394208638428%2520-12.406148394036626%252C131.1749346033788%2520-12.402658828052589%252C131.18539226499365%2520-12.39785080357136%252C131.1951500288647%2520-12.391800216479517%252C131.2040539301831%2520-12.384602570830396%252C131.21196351476866%2520-12.376371467455044%252C131.21875405623402%2520-12.36723680674208%252C131.2243185221469%2520-12.357342734290556%252C131.22856925824416%2520-12.346845362198192%252C131.23143936438407%2520-12.335910302265669%252C131.23288374095046%2520-12.324710050322047%252C131.23287978976074%2520-12.31342126316333%252C131.23142775908178%2520-12.302221971214191%252C131.2285507280304%2520-12.291288770950992%252C131.22429423133943%2520-12.280794041353518%252C131.21872553110978%2520-12.27090322818549%252C131.21193254766308%2520-12.26177223875249%252C131.20402246687186%2520-12.253544987973964%252C131.19512004630383%2520-12.246351134165792%252C131.18536564710004%2520-12.240304039903442%252C131.17491302265617%2520-12.235498989772399%252C131.1639268988327%2520-12.232011692769177%252C131.15258038354088%2520-12.229897092656154%252C131.14105224609375%2520-12.229188504764602%29%29%29&targetUri=%2Foccurrences%2Fsearch&downloadType=records&email=&reasonTypeId=4&sourceTypeId=0&downloadFormat=dwc&file=records-2023-08-20&layers=&customHeader=&fileType=csv&layersServiceUrl=)

- support ticket - https://support.ehelp.edu.au/a/tickets/183003

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/downloads-plugin/pull/91
and 
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/836

**Comment by kylie-m** [comment]
The download is now working for me on biocache-test
