### ISSUE TITLE
Failed download with default settings

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-service#835]
A user has reported the following failed download (see details below)

When replicating the issue, we found the download does indeed fail with the default settings, but choosing a customised download and changing nothing makes the download work. It fails again if you include all DWC core fields, but it's only 63 records, so one particular field in a particular record might be causing it.

Tim has tried quickly with a couple of different additional filters but couldn't rule any records out by date or data resource.

-----
Details from user:

Your ALA download has failed. Please contact support@ala.org.au by replying to this email and we will investigate the cause.

Your search URL was:
[https://biocache.ala.org.au/occurrences/search?&q=*%3A*&fq=%28lsid%3Ahttps%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F2900687%29AND%28stateProvince%3A%22Queensland%22%29&disableAllQualityFilters=true&fq=-basisOfRecord%3A%22FOSSIL_SPECIMEN%22+AND+-%28basisOfRecord%3A%22MATERIAL_SAMPLE%22+AND+contentTypes%3A%22EnvironmentalDNA%22%29&fq=-%28duplicate_status%3A%22ASSOCIATED%22+AND+duplicateType%3A%22DIFFERENT_DATASET%22%29&fq=-assertions%3ATAXON_MATCH_NONE+AND+-assertions%3AINVALID_SCIENTIFIC_NAME+AND+-assertions%3ATAXON_HOMONYM+AND+-assertions%3AUNKNOWN_KINGDOM+AND+-assertions%3ATAXON_SCOPE_MISMATCH&fq=-occurrenceStatus%3AABSENT&fq=-userAssertions%3A50001+AND+-userAssertions%3A50005&fq=-year%3A%5B*+TO+1700%5D&fq=-establishmentMeans%3A%22MANAGED%22+AND+-decimalLatitude%3A0+AND+-decimalLongitude%3A0+AND+-assertions%3A%22PRESUMED_SWAPPED_COORDINATE%22+AND+-assertions%3A%22COORDINATES_CENTRE_OF_STATEPROVINCE%22+AND+-assertions%3A%22COORDINATES_CENTRE_OF_COUNTRY%22+AND+-assertions%3A%22PRESUMED_NEGATED_LATITUDE%22+AND+-assertions%3A%22PRESUMED_NEGATED_LONGITUDE%22&fq=-outlierLayerCount%3A%5B3+TO+*%5D&fq=-spatiallyValid%3A%22false%22&fq=-coordinateUncertaintyInMeters%3A%5B10001+TO+*%5D](https://protect-au.mimecast.com/s/ssW7C1WZxYTprxv4ATLKo41?domain=biocache.ala.org.au)

The reference to quote is:
48f0e7e8-f386-3d11-bdbd-9f68b6810b6a-1692071392527

-----

- support ticket: https://support.ehelp.edu.au/a/tickets/182756

**Comment by adam-collins** [comment]
I get a different error on production, no reference to quote.

This is working on biocache-test, likely the fix for #834 also fixed this issue.

**Comment by kylie-m** [comment]
Thanks Adam, this download is now working for me on biocache-test
