### ISSUE TITLE
Update facet name in backend for spatial validity

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/biocache-service#837]
The spatial validity facet is still showing by its old name (`geospatial_kosher`) in the URL and JSON fields, for eg:

URL:
https://biocache.ala.org.au/occurrences/search?q=taxa%3A%22cassowary%22&qualityProfile=ALA&fq=geospatial_kosher%3A%22true%22#tab_mapView

JSON:
https://biocache.ala.org.au/ws/occurrences/search?q=taxa%3A%22cassowary%22&qualityProfile=ALA&fq=geospatial_kosher%3A%22true%22#tab_mapView

Facet name should now be `spatiallyValid`, as per [https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/spatiallyValid](https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/spatiallyValid)

see also [https://biocache.ala.org.au/fields?filter=spatial](https://biocache.ala.org.au/fields?filter=spatial)

**Comment by adam-collins** [comment]
Updated in a few projects to be included in their next releases
- ala-install
- spatial-hub
- spatial-service
- biocache-hubs (pull request https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/584)
- ala-bie-hub

Did I miss any?

**Comment by kylie-m** [comment]
Thanks Adam - sounds great - I can't think of any others to add

**Comment by adam-collins** [comment]
Everything but spatial has been released. Spatial is blocked by biocollect. Closing this issue so I have one less to look at.

**Comment by kylie-m** [comment]
Hi @adam-collins  - In my biocache-service testing I've noticed the old term is still visible in the JSON, for example is this query: https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=text_datasetName:PPBE

I don't see it in the query URLs, though (eg https://biocache-databox.ala.org.au/occurrences/search?q=taxa%3A%22fish%22&qualityProfile=ALATemp&fq=spatiallyValid%3A%22true%22)
