### ISSUE TITLE
DQ filters not excluding Material Sample / eDNA records

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/biocache-service#838]
Re this URL: https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr23232&disableQualityFilter=record-type&fq=-basisOfRecord%3A%22FOSSIL_SPECIMEN%22&fq=-%28basisOfRecord%3A%22MATERIAL_SAMPLE%22+AND+contentTypes%3A%22EnvironmentalDNA%22%29

This dataset is entirely eDNA records (contentType EnvironmentalDNA), and yet the DQ filters are not filtering them out. 

When I click on the "[0 excluded records](https://biocache.ala.org.au/occurrence/search?q=data_resource_uid%3Adr23232&qualityProfile=ALA&disableAllQualityFilters=true&fq=basisOfRecord%3A%22FOSSIL_SPECIMEN%22+%28%2BbasisOfRecord%3AMATERIAL_SAMPLE+%2BcontentTypes%3AEnvironmentalDNA%29)" link

I get this incomplete URL on screen. Is that just an error display problem, or is it that the URL is being truncated somewhere along the line causing eDNA records to not be obfuscated?

![Image](https://user-images.githubusercontent.com/1271932/267169836-e073a569-e5ca-4f9e-b73c-575713806826.png)

Actually, it's only fossils that are being excluded. [In this search](https://biocache.ala.org.au/occurrence/search?q=*&qualityProfile=ALA&disableAllQualityFilters=true&fq=basisOfRecord%3A%22FOSSIL_SPECIMEN%22+%28%2BbasisOfRecord%3AMATERIAL_SAMPLE+%2BcontentTypes%3AEnvironmentalDNA%29#tab_mapView) you can clearly see the only basisOfRecord being excluded is fossils.

**Comment by adam-collins** [comment]
Filter is wrong `-(basisOfRecord:"MATERIAL_SAMPLE" AND contentTypes:"EnvironmentalDNA")` should be `-(basisOfRecord:"MATERIAL_SAMPLE" OR contentTypes:"EnvironmentalDNA")`

**Comment by adam-collins** [comment]
Working now in production
