### ISSUE TITLE
/images/taxon/{taxonConceptID} API returns 404 for any taxonConceptID

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/biocache-service#842]
<img width="1426" alt="image" src="https://github.com/AtlasOfLivingAustralia/biocache-service/assets/72474143/90b61af3-aef0-4d5f-ac65-ddee3b1a706b">

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/864

**Comment by peggynewman** [comment]
Works with https://api.test.ala.org.au/occurrences/images/taxon/https%3A%2F%2Fid.biodiversity.org.au%2Ftaxon%2Fapni%2F51736328
