### ISSUE TITLE
recordedBy fixes

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/biocache-service#847]
Field is called ‘collector’ in front end and downloads. Change to `recordedBy` term and `Recorded by` label 

When there are multiple recorders, the processed value sorts them alphabetically, rather than in the order in which they have been provided. This will upset certain people in the Collections Community (not me). Leave the sort order intact.

There are some parsing issues (https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/578), for example: 
* The parser has a problem with apostrophes in names. 
* If the surname consists of more than one word the comma is taken as a delimiter between names rather than a separator between surname and first name or initials. 
Remove all parsing on individual names text

**Comment by adam-collins** [comment]
duplicate
