### ISSUE TITLE
Active facet map value substitution has an error

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-service#851]

**Comment by adam-collins** [comment]
biocache-service occurrence/search's activeFacetMap contains incorrect value mapping. 
e.g. https://biocache.ala.org.au/occurrences/search?q=species_list_uid%3Adr652&qualityProfile=ALA&qc=-_nest_parent_%3A*&fq=raw_state_conservation%3A%22R%22#tab_mapView
- In the activeFacetMap `raw_state_conservation:R` does a lookup of the value `R` in the `duplicateStatus` field context.

**Comment by adam-collins** [comment]
@peggynewman This is fixed on biocache-test, please test https://biocache-test.ala.org.au/occurrences/search?q=species_list_uid%3Adr652&qualityProfile=ALA&qc=-_nest_parent_%3A*&fq=raw_state_conservation%3A%22R%22#tab_mapView

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/852

**Comment by peggynewman** [comment]
Tested, that's great, thank you
