### ISSUE TITLE
WMS for longitudes >180 and <360 throwing exception

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-service#861]

**Comment by adam-collins** [comment]
pull request https://github.com/AtlasOfLivingAustralia/biocache-service/pull/862

**Comment by peggynewman** [comment]
error in wms/reflect: 
<img width="837" alt="image" src="https://github.com/AtlasOfLivingAustralia/biocache-service/assets/1271932/fea86655-6598-4e71-a207-6bb50debbd09">

Now resolved in biocache-test
