### ISSUE TITLE
Include identificationVerificationStatus in facets - key field for iNaturalist

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/biocache-service#874]

**Comment by adam-collins** [comment]
I assume this is an addition to the biocache hub's `Customise filters` list.

**Comment by adam-collins** [comment]
ala-install pull request https://github.com/AtlasOfLivingAustralia/ala-install/pull/766

Done, test and prod. It will look nicer when 3.4.0 is deployed, see test.
