### ISSUE TITLE
Update apiKey implmentation

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#88]
Some web services check for an `apiKey` param or value, which is currently hard coded as a certain value. 

We now have an [ALA api key service](https://github.com/AtlasOfLivingAustralia/apikey), so we should be using that.

**Comment by adam-collins** [comment]
The api key service is used to verify apiKey params.  

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/master/src/main/java/au/org/ala/biocache/web/AbstractSecureController.java
