### ISSUE TITLE
Download emails have invalid URL for DOI links

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#913]
Biocache-service generates the download email via a [download-email.html template file](https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/biocache-service/templates/config/download-doi-email.html). There are 2 versions of the DOI link provided in the email, one for the ALA's DOI service (doi.ala.org.au) and the other is the canonical DOI link (doi.org).

The canonical version is currently broken due to containing an internal space character in the URL and thus is not clickable. Its being populated by the variable `officialDoiUrl`, which appears to have the host component populated by a config var of `official.doi.resolver`.

> The [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier) for this download is [https://doi.org /10.26197/ala.0afdc816-ecfa-4a2f-b65f-d269521373e8](https://doi.org%20/10.26197/ala.0afdc816-ecfa-4a2f-b65f-d269521373e8)

The space is just after the `doi.org` string and comes through as encoded space `%20` - `https://doi.org%20/10.26197/ala.0afdc816-ecfa-4a2f-b65f-d269521373e8`

Fix is to remove this space from the variable assignment or config value (`official.doi.resolver` most likely).

**Comment by adam-collins** [comment]
Fixed on server config, to be picked up on a service restart.

Fixed in ala-install https://github.com/AtlasOfLivingAustralia/ala-install/commit/89e58c1978dc9c171161d6fbb475912ff069f427

Should restart and test before closing.
