### ISSUE TITLE
Offline downloads API gateway authentication 

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/biocache-service#927]
[This biocache-ws download url works](https://biocache-ws.ala.org.au/ws/occurrences/offline/download?email=peggy.newman%40csiro.au&reason=testing&fields=id&extra=catalogNumber&sep=%2C&esc=%22&dwcHeaders=false&includeMisc=false&&qa=none&reasonTypeId=10&sourceTypeId=0&fileType=csv&mintDoi=false&q=dataResourceUid:dr1411&fq=recordedBy:Peggy%20Newman) but [this api.ala one does not](https://api.ala.org.au/occurrences/occurrences/offline/download?email=peggy.newman%40csiro.au&reason=testing&fields=id&extra=catalogNumber&sep=%2C&esc=%22&dwcHeaders=false&includeMisc=false&&qa=none&reasonTypeId=10&sourceTypeId=0&fileType=csv&mintDoi=false&q=dataResourceUid:dr1411&fq=recordedBy:Peggy%20Newman).

I get an `Unauthorised` response.

The ask is to 
- fix this so at least the offline download GET works 
- re-enable paging on 'occurrences/search' with a reasonable max page size (should this be a separate issue?)
- author a clear help desk article that outlines how to use those 2 API calls, when a token is required, how to use a token, and users' responsibility to abide by the terms of the license on the data

**Comment by peggynewman** [comment]
Related: https://github.com/AtlasOfLivingAustralia/biocache-service/issues/697

**Comment by kylie-m** [comment]
Adding to this from the [slack discussion](The API documentation and a gateway config needs to be updated to reflect rule A and C. Currently it reflects only rule A):

The API documentation and a gateway config needs to be updated to reflect rule A (JTW with Roles) and C (Email address). Currently it reflects only rule A.

**Comment by adam-collins** [comment]
Upon review, it appears there are no further actions required for this issue, and it is recommended to close it. The following points provide clarification:
1. The initial comment suggests that the service was utilized without consulting the documentation. The Open API specification clearly states that authentication is mandatory.
2. The API documentation site provides comprehensive instructions on authentication.
3. Deep paging will not be re-enabled for the `occurrences/search`. The identified service is the appropriate one for bulk downloads.
4. The offline downloads service includes citation information within the output files.
5. A link to the home page is available from the API page, which provides access to more information, including citation guidelines.

**Comment by peggynewman** [comment]
Disagree with all 4 points. We'll discuss this offline.

**Comment by adam-collins** [comment]
No additional information provided.
