### ISSUE TITLE
Facets issues from Lee

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#99]
> Hi Mahmoud and Nick
> 
> I finally got a little time to check through the biocache 'facets'/index variables and here are my observations of anything odd...
> 
> Family is mostly UPPERCASE but some lower (presume in DwC record?)
> Order is mostly UPPERCASE but some lower
> Class is mostly UPPERCASE but some lower
> Phylum is mostly UPPERCASE but some lower
> Kingdom is mostly UPPERCASE but some lower
> Name match metric needs definitions
> Lifeform - how is it defined?
> Species interaction is only 'infects' and 'infected by'? Not 'predates' etc?
> Country - how is it defined? DwC or map intersect?
> CAPAD should be by category not park as 1st priority (duel needed)
> DIWA by category 1st?
> IMCRA 4 region - ERROR
> Elevation - blank (DwC?)
> Min_elevation_d_rng? Definition, and needs better name
> Spatially valid (valid only?)
> Taxon identification issue: definitions would be helpful
> Location names in Life Stage?
> Month: 10 records with "00 TO 00"
> Occurrence_decade_i: ? Seems to contain years and numbers (e.g., 1700, 30)
> State conservation and unprocessed: "#N/A" definition?
> Sensitive occurs under Spatial and Assertion Categories/Classes. Suggest latter only
> Record issues = 50 but > 50 tests?
> Outlier layer count includes classes 6, 7, 8, 10?
> Assertions by user has ONLY ids (useless)
> Associated records: "D" and "R" need expansion
> User: only has IDs (useless)
> Relationship between dataset (drxxx) and dataset_name needs clarification
> 
> The link to http://spatial.ala.org.au/webportal/resources/FacetFields.htm shows that the file is far from up to date and does not contain class definitions - where it would be helpful. Happy to help, but in most cases, developer definition would be needed as a seed.
> 
> Happy to discuss anytime.
> 
> Lee

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
